# -*- coding: utf-8 -*-
# Part 3: pages 1407-1412 (idx0642-idx0647)

entries = [
# ---- page 1407 (idx0642) ----
(1407, "C2IPS (Command and Control Information Processing System)", "hệ thống xử lý thông tin chỉ huy và kiểm soát"),
(1407, "C2P (command & control processor)", "bộ xử lý dữ liệu chỉ huy và kiểm soát"),
(1407, "C2P (command and control protection)", "sự bảo vệ chỉ huy và kiểm soát"),
(1407, "C2-protect (command and control protect (a defensive form of command and control warfare))", "bảo vệ chỉ huy và kiểm soát (một dạng phòng ngự của tác chiến chỉ huy và kiểm soát)"),
(1407, "C2S (Command and control support)", "sự chi viện chỉ huy và kiểm soát, sự bảo đảm chỉ huy và kiểm soát"),
(1407, "C2W (command and control warfare)", "chiến tranh chỉ huy kiểm soát; tác chiến chỉ huy và kiểm soát"),
(1407, "C2WC (command and control warfare commander)", "tư lệnh (trưởng) chiến tranh chỉ huy và kiểm soát"),
(1407, "C3 (command and control and communication)", "chỉ huy, kiểm soát và thông tin liên lạc"),
(1407, "C3 (Conveyer 340 airplane)", "(k.hiệu) máy bay Convâyơ 340"),
(1407, "C3AG (Command, Control, and Communications Advisory Group)", "nhóm cố vấn chỉ huy, kiểm soát và thông tin liên lạc"),
(1407, "C3CM (command, control, and communications countermeasures)", "các phương tiện đối phó tác chiến chỉ huy, kiểm soát và thông tin liên lạc"),
(1407, "C3I (command and control, communication and intelligence)", "chỉ huy, kiểm soát, thông tin liên lạc và trinh sát; chỉ huy, kiểm soát, thông tin liên lạc và tình báo"),
(1407, "C3IC (coalition coordination, communications, and Integration center)", "trung tâm hiệp đồng, thông tin liên lạc và hợp nhất liên quân"),
(1407, "C3SMP (Command, Control, and Communications Systems Master Plan)", "kế hoạch tổng thể các hệ thống chỉ huy, kiểm soát và thông tin liên lạc"),
(1407, "C4 (command, control, communications, and computers)", "chỉ huy, kiểm soát, thông tin liên lạc và máy tính"),
(1407, "C4 (Conveyer 440 airplane)", "(k.hiệu) máy bay Convâyơ 440"),
(1407, "C4 systems (command, control, communications, and computer systems)", "các hệ thống chỉ huy, kiểm soát, thông tin liên lạc và máy tính"),
(1407, "C4CM (command, control, communications, and computer countermeasures)", "các biện pháp chống chiến tranh chỉ huy, kiểm soát, thông tin liên lạc và máy tính"),
(1407, "C4I (command, control, communications, computers, and Intelligence)", "chỉ huy, kiểm soát, thông tin liên lạc, máy tính và tình báo"),
(1407, "C4IFTW (command, control, communications, computers, and intelligence for the warrior)", "chỉ huy, kiểm soát, thông tin liên lạc, máy tính và tình báo đối với người lính"),
(1407, "C4ISR (command, control, communications, computers, intelligence, surveillance and reconnaissance)", "chỉ huy, kiểm soát, thông tin liên lạc, máy tính, tình báo, quan sát và trinh sát"),
(1407, "C4S (command, control, communications, and computer systems)", "các hệ thống chỉ huy, kiểm soát, thông tin liên lạc và máy tính"),
(1407, "C5 (Conveyer 580 turboprop airplane)", "(k.hiệu) máy bay tuabin cánh quạt Convâyơ 580"),
(1407, "C-5A (Lockheed military cargo transport airplane)", "(k.hiệu) máy bay vận tải quân sự của hãng Lốchít"),
(1407, "C-123 (Provider twin-engine assault transport)", "(k.hiệu) máy bay vận tải xung kích, động cơ kép, mang tên \"Người cung cấp\""),

# ---- page 1408 (idx0643) ----
(1408, "C-124 (Globemaster heavy cargo four-engine transport airplane)", "(k.hiệu) máy bay vận tải hạng nặng bốn động cơ mang tên \"Chủ địa cầu\""),
(1408, "C-130 (Hercules medium-range cargo and troop transport airplane powered by four turboprop engines)", "(k.hiệu) máy bay vận tải và chở quân tầm trung, bốn động cơ tuabin cánh quạt, mang tên \"Hercule\""),
(1408, "C-133 (Cargomaster heavy four-engine turboprop cargo transport airplane)", "(k.hiệu) máy bay vận tải hạng nặng, bốn động cơ tuabin cánh quạt, mang tên \"Kiện tướng vận tải\""),
(1408, "C-140 (Jet Star support - type transport aircraft powered by four turbojet engines)", "(k.hiệu) máy bay vận tải yểm trợ, bốn động cơ tuabin phản lực, mang tên \"Ngôi sao phản lực\""),
(1408, "C-141 (Starlifter large cargo transport aircraft powered by four turbojet engines)", "(k.hiệu) máy bay vận tải hạng nặng, bốn động cơ tua bin phản lực, mang tên \"cầu nâng hàng không\""),
(1408, "CA (Canada)", "Canada"),
(1408, "CA (Civil Affairs (Administration))", "cục hành chính về vấn đề dân sự; cơ quan dân vận"),
(1408, "CA (civil affairs)", "các vấn đề dân vận, công tác dân vận"),
(1408, "CA (combat assessment)", "đánh giá kết quả trận đánh"),
(1408, "CA (controller aircraft)", "máy bay chỉ huy bắn (pháo)"),
(1408, "CA (heavy cruiser)", "tàu khu trục hạng nặng; tuần dương hạm hạng nặng, tuần dương hạm có trang bị pháo"),
(1408, "CA Co (civil affairs company)", "đại đội công tác dân vận"),
(1408, "CA/MG; CAMG (civil affairs military government)", "hành chính quân sự và dân sự"),
(1408, "CAA (civil air augmentation)", "sự nâng cấp hàng không dân dụng"),
(1408, "CAA (Civil Aviation Authority)", "(UK) nhà chức trách hàng không dân dụng; cục hàng không dân dụng (Anh)"),
(1408, "CAA (Command Arrangement Agreements)", "các thoả thuận sắp xếp chỉ huy"),
(1408, "CAAIS (computer aided action information system)", "hệ thống thu thập thông tin chiến đấu có máy tính hỗ trợ"),
(1408, "CAB (Canadian Armoured Brigade)", "lữ đoàn tăng thiết giáp Canada"),
(1408, "CAB (combat aviation brigade)", "lữ đoàn không quân chiến đấu (của lục quân)"),
(1408, "CAC (Canadian Armoured Corps)", "quân đoàn tăng thiết giáp Canada"),
(1408, "CAC (civil air control)", "sự kiểm tra hàng không dân dụng, sự kiểm soát hàng không dân dụng"),
(1408, "CAC (coast artillery corps)", "quân đoàn pháo binh bờ biển"),
(1408, "CAC (combat air command)", "bộ tư lệnh không quân chiến đấu"),
(1408, "CAC (combined arms center)", "trung tâm binh chủng hợp thành của lục quân"),
(1408, "CAC (Continental Air Command)", "bộ tư lệnh không quân lục địa"),
(1408, "CAC (control and coordination)", "sự chỉ huy và hiệp đồng tác chiến"),
(1408, "CACS (computer assisted command system)", "hệ thống chỉ huy có máy tính hỗ trợ"),
(1408, "CAD (Canadian Armoured Division)", "sư đoàn tăng thiết giáp Canada"),
(1408, "CAD (cartridge-activated device)", "thiết bị kích hoạt quả đạn"),
(1408, "CAD (cartridge actuated device)", "thiết bị kích hoạt quả đạn"),
(1408, "CAD (close-in air defence)", "phòng không tầm cực gần"),
(1408, "CAD (computer-assisted design)", "sự thiết kế bằng máy tính, sự thiết kế tự động hoá; sự thiết kế có sự trợ giúp của máy tính"),

# ---- page 1409 (idx0644) ----
(1409, "CAD (combat assault dory)", "thuyền đổ bộ xung kích"),
(1409, "CAD/CAM (computer-assisted design/computer-assisted manufacture)", "sự thiết kế có trợ giúp của máy tính; sản xuất có trợ giúp của máy tính"),
(1409, "CADB (composite air defense battalion)", "tiểu đoàn phòng không hỗn hợp"),
(1409, "CADC (Canada Air Defense Command)", "bộ tư lệnh phòng không Canada"),
(1409, "CADF (Central Air Defense Force)", "lực lượng phòng không trung ương"),
(1409, "CADF (commucated antenna direction finding)", "tìm phương bằng anten chuyển mạch, định phương bằng anten chuyển mạch"),
(1409, "CADS (containerized ammunition distribution system)", "hệ thống phân phối đạn dược đóng thùng"),
(1409, "CADWS (close air defence weapon system)", "tổ hợp vũ khí phòng không tầm gần"),
(1409, "CAEMS (Computer-aided Embarkation Management System)", "hệ thống điều hành bốc xếp trang thiết bị được hỗ trợ bằng máy tính"),
(1409, "CAF (Canadian Air Force)", "không quân Canada"),
(1409, "CAF (Canadian Armed Forces)", "lực lượng vũ trang Canada, quân đội Canada"),
(1409, "CAF (Combat Air Forces)", "lực lượng không quân chiến đấu"),
(1409, "CAFE (conventional armed forces in Europe)", "lực lượng vũ trang thông thường ở châu Âu, lực lượng vũ trang phi hạt nhân ở châu Âu"),
(1409, "CAFMS (Computer-assisted force management system)", "hệ thống quản lý lực lượng được hỗ trợ bằng máy tính"),
(1409, "CAG (carrier air group)", "nhóm không quân (trên) tàu sân bay"),
(1409, "CAG (close approach indicator)", "bộ chỉ báo tiếp cận (mục tiêu)"),
(1409, "CAGE (Canada automatic ground environment)", "hệ thống điều khiển phòng không mặt đất bán tự động Canada"),
(1409, "CAGRA (Commander, Army Group, Royal Artillery)", "(Anh) chỉ huy trưởng pháo binh dã chiến tập đoàn quân"),
(1409, "CAGRE (Commander, Army Group, Royal Engineers)", "chỉ huy trưởng công binh dã chiến tập đoàn quân"),
(1409, "CAIMS (conventional ammunition integrated management system)", "hệ thống quản lý thống nhất đạn dược thông thường"),
(1409, "CAINS (carrier aircraft inertial navigation system)", "hệ thống dẫn đường quán tính cho máy bay trên tàu sân bay"),
(1409, "CAIRC (Caribbean Air Command)", "bộ chỉ huy không quân Mỹ ở khu vực biển Caribê, bộ tư lệnh không quân vùng Caribê"),
(1409, "cal (caliber; calibre)", "cỡ (nòng, đạn); lần cỡ (đo độ dài trong súng pháo)"),
(1409, "CAL; cal (calibration)", "sự định cỡ; sự hiệu chỉnh"),
(1409, "Cal. 30 MG (caliber. 30 machine gun)", "súng máy cỡ 7,62mm"),
(1409, "Cal. 50 AAMG (caliber. 50 antiaircraft machine gun)", "súng máy phòng không 12,7mm, súng máy cao xạ cỡ 12,7mm"),
(1409, "CALCM (conventional air-launched cruise missile)", "tên lửa có cánh thông thường phóng từ trên không"),
(1409, "CALSU (combat airlift support unit)", "đơn vị bảo đảm vận chuyển đường không ở khu vực tác chiến; phân đội bảo đảm vận chuyển đường không ở khu vực chiến đấu"),
(1409, "cam (camouflage)", "ngụy trang; vật chất và khí tài ngụy trang"),
(1409, "CAM (chemical agent monitor)", "máy phát hiện chất độc hoá học"),
(1409, "CAM (chemical agent munition)", "đạn hóa học"),
(1409, "CAM (cockpit-angle measure (crew field of view))", "giới hạn góc buồng lái (phạm vi quan sát của kíp lái máy bay)"),

# ---- page 1410 (idx0645) ----
(1410, "CAM (conventional attack missile)", "tên lửa tiến công (mang đầu đạn) thông thường"),
(1410, "CAMBS (command activated multi-beam sonobuoy)", "phao thủy âm nhiều tia kích hoạt bằng lệnh"),
(1410, "CAMDS (chemical agent munitions disposal system)", "hệ thống hủy bom đạn hóa học"),
(1410, "CAML (cargo aircraft minelayer)", "phương tiện rải mìn từ trên máy bay vận tải; (hq) thiết bị thả thủy lôi (đặt) trên máy bay vận tải"),
(1410, "CAMPS (consolidated air mobility planning system)", "hệ thống lập kế hoạch cơ động đường không hợp nhất"),
(1410, "CAMS (combat aviation management system)", "hệ thống điều hành không quân chiến đấu"),
(1410, "CAMT (countering air and missile threats)", "sự đối phó với các mối đe doạ trên không và tên lửa"),
(1410, "CAN 5 (Committee on Aircraft Noise (ICAO - rules for new designs of aircraft))", "uỷ ban về tiếng ồn của máy bay 5 (luật dùng cho mẫu thiết kế máy bay mới)"),
(1410, "CANA (convalescent antidote for nerve agent)", "thuốc giải chất độc thần kinh"),
(1410, "canc (canceled)", "huỷ bỏ, bãi bỏ, xoá bỏ; thủ tiêu"),
(1410, "CANE (computer aided navigation equipment)", "thiết bị dẫn đường có máy tính hỗ trợ"),
(1410, "CANR (Canadian NORAD region)", "vùng phòng thủ không gian vũ trụ Bắc Mỹ thuộc Canada"),
(1410, "CANUKUS (Canada-United Kingdom-United States)", "Canada - Anh - Mỹ"),
(1410, "CANUS (Canada-United States)", "Canada - Mỹ"),
(1410, "CAO (chief administrative officer)", "sĩ quan chỉ huy trưởng quản lý hành chính"),
(1410, "CAO (contract administration office)", "cơ quan quản lí hợp đồng"),
(1410, "CAO (counterair operations)", "tác chiến phòng không"),
(1410, "CAO SOP (standing operating procedures for coordination of atomic operations)", "quy trình thực hiện thường xuyên về hiệp đồng tác chiến nguyên tử"),
(1410, "CAOC (combat air operations center)", "trung tâm chỉ huy tác chiến của không quân chiến đấu"),
(1410, "CAOC (combined air operations center)", "trung tâm chỉ huy tác chiến của không quân hợp thành"),
(1410, "cap (capacity)", "dung tích"),
(1410, "CAP (carrier air patrol)", "tuần tiễu bằng máy bay trên tàu sân bay"),
(1410, "Cap (Civil Air Patrol)", "đội tuần tiễu hàng không dân dụng"),
(1410, "CAP (combat air patrol)", "tuần tiễu chiến đấu trên không; đội tuần tiễu chiến đấu trên không"),
(1410, "CAP (crisis action planning)", "sự lập kế hoạch giải quyết khủng hoảng"),
(1410, "CAPES (capability evaluation system)", "hệ thống đánh giá khả năng; hệ thống đánh giá trạng thái sẵn sàng của lực lượng và trang bị kỹ thuật"),
(1410, "Capt (captain)", "đại uý; thuyền trưởng, hạm trưởng; cơ trưởng (máy bay); đại tá không quân"),
(1410, "car (carrier)", "phương tiện vận tải; xe vận tải (bọc thép); máy bay vận tải; tàu sân bay, hàng không mẫu hạm"),
(1410, "CAR (Chief of the Army Reserve)", "tư lệnh (trưởng) lực lượng dự bị lục quân"),
(1410, "CAR (Civil Airworthiness Regulations)", "quy tắc tính khả phi dân dụng, quy định về khả năng đủ điều kiện bay của hàng không dân dụng"),
(1410, "CARDA (Continental United States airborne reconnaissance for damage assessment)", "sự trinh sát đường không phần lục địa nước Mỹ để đánh giá tổn thất"),
(1410, "CARDA (Continental United States area reconnaissance for damage assessment)", "sự trinh sát khu vực phần lục địa nước Mỹ để đánh giá tổn thất"),

# ---- page 1411 (idx0646) ----
(1411, "CARDE (Canadian Armament Research and Development Establishment)", "viện nghiên cứu vũ khí Canada"),
(1411, "CARIBCOM (Caribbean Command)", "bộ chỉ huy quân đội Mỹ ở khu vực biển Caribê; bộ tư lệnh vùng Caribê"),
(1411, "CARIBROC (Caribbean Regional Operations Center)", "trung tâm chỉ huy tác chiến vùng Caribê"),
(1411, "CARP (computed air release point)", "điểm cắt bom trên không được tính sẵn"),
(1411, "CARP (contingency alternate route plan)", "kế hoạch đường cơ động dự bị trong tình huống bất ngờ"),
(1411, "carr (carrier)", "phương tiện vận tải; xe vận tải (bọc thép); máy bay vận tải; tàu sân bay, hàng không mẫu hạm"),
(1411, "CARROTC (Chief, United States Army Reserve and ROTC Affairs)", "chủ nhiệm ngành lực lượng dự bị và huấn luyện lục quân Mỹ"),
(1411, "CARS (combat arms regimental system)", "hệ thống vũ khí cấp trung đoàn"),
(1411, "CART (combat aircraft repair team)", "đội sửa chữa máy bay chiến đấu"),
(1411, "CAS (calibrated airspeed)", "tốc độ bay hiệu chỉnh"),
(1411, "cas (casualty)", "bị thương, bị tiêu diệt; bị giết; thương vong"),
(1411, "CAS (casualty assessment system)", "phương pháp đánh giá thương vong"),
(1411, "CAS (Chief of the Air Staff)", "tham mưu trưởng không quân; tham mưu trưởng binh đoàn không quân; tham mưu trưởng liên binh đoàn không quân"),
(1411, "CAS (close air support)", "chi viện hoả lực không quân trực tiếp; chi viện không quân trực tiếp"),
(1411, "CASC (Canadian Army Service Corps)", "ngành hậu cần lục quân Canada"),
(1411, "CASCAD (close air support cargo dispenser)", "(kq) thiết bị tự động thả giấy bạc gây nhiễu vô tuyến điện chi viện trực tiếp cho không quân; máy tự động thả giấy tráng kim chống rada bảo đảm trực tiếp cho máy bay"),
(1411, "Casevac (casualty evacuation)", "sự tản thương"),
(1411, "CASEX (combined anti-submarine exercise)", "cuộc diễn tập hiệp đồng binh chủng hợp thành chống ngầm"),
(1411, "CASF (Composite Air Strike Forces)", "lực lượng không quân cường kích hỗn hợp, lực lượng tập kích đường không hỗn hợp"),
(1411, "CASP (casualty staging point)", "trạm chuyển thương"),
(1411, "CASP (computer-aided search planning)", "sự lập kế hoạch tìm kiếm được hỗ trợ bằng máy tính"),
(1411, "CASREP (casualty report)", "báo cáo tình hình thương vong"),
(1411, "CASREQ (close air support request)", "yêu cầu chi viện hoả lực không quân trực tiếp"),
(1411, "CASS (camouflage support system)", "phương pháp bảo đảm ngụy trang"),
(1411, "CASS (close air support system)", "hệ thống chi viện đường không trực tiếp"),
(1411, "CASS (command active sonobuoy)", "phao thủy âm chủ động kích hoạt bằng lệnh"),
(1411, "CAST (combined arms staff trainer)", "thiết bị huấn luyện tham mưu binh chủng hợp thành"),
(1411, "CASTOR (corps airborne stand-off radar)", "rada ngoài tầm hỏa lực phòng thủ (cấp) quân đoàn đặt trên máy bay"),
(1411, "CasuRC (casualty reception center)", "trạm tiếp nhận thương bệnh binh"),
(1411, "CASWS (close air support weapon system)", "tổ hợp vũ khí chi viện đường không trực tiếp"),
(1411, "CASY (carrier aircraft service unit)", "đơn vị phục vụ không quân vận tải; phân đội phục vụ không quân vận tải"),

# ---- page 1412 (idx0647) ----
(1412, "CAT (category)", "thứ; loại; hạng"),
(1412, "CAT (combat aircraft technology)", "công nghệ máy bay chiến đấu"),
(1412, "CAT (control and assessment team)", "đội đánh giá kết quả đòn tiến công hạt nhân"),
(1412, "CAT/FCS (command adjusted trajectory/fire control system)", "tổ hợp điều chỉnh đạn đạo / chỉ huy hỏa lực theo lệnh"),
(1412, "CAT/LCV (Combined Arms Team/Lightweight Combat Vehicle)", "(US) xe chiến đấu hạng nhẹ và phân đội binh chủng hợp thành"),
(1412, "CATAC (Central Allied Tactical Air Command)", "bộ chỉ huy không quân chiến thuật của liên quân NATO ở khu vực Trung Âu, bộ tư lệnh không quân chiến thuật của liên quân NATO ở khu vực Trung Âu"),
(1412, "CATCC (carrier air traffic control center)", "trung tâm kiểm soát không lưu trên tàu sân bay"),
(1412, "CATF (commander, amphibious task force)", "chỉ huy trưởng lực lượng đặc nhiệm xe lội nước đổ bộ"),
(1412, "CATFAE (catapult launched fuel-air explosive)", "lượng nổ nhiên liệu khí phóng bằng máy (phóng)"),
(1412, "catk (counterattack)", "phản công; phản kích"),
(1412, "CATO (combat arms training organization)", "sự tổ chức huấn luyện binh chủng chiến đấu"),
(1412, "CATT-B (Component Advanced Technology Test-Bed)", "(US) giá thử nghiệm công nghệ tiên tiến hợp thành"),
(1412, "CATTS (combined arms tactical training simulator)", "thiết bị mô phỏng huấn luyện chiến thuật binh chủng hợp thành"),
(1412, "CAU (central alarm unit)", "khối báo động trung tâm"),
(1412, "CAU (crypto auxiliary unit)", "thiết bị mã hoá phụ"),
(1412, "CAU (cryptographic auxiliary unit)", "thiết bị mã hoá bổ trợ"),
(1412, "CAV (cavalry)", "kỵ binh bọc thép; kỵ binh bay"),
(1412, "CAV (composite armored vehicle)", "(Mỹ) xe thiết giáp compôzit"),
(1412, "Cav (Brig) (Div) (cavalry (brigade), (division))", "(sư đoàn), (lữ đoàn) kỵ binh bọc thép"),
(1412, "Cav DHQ (cavalry division headquarters)", "sở chỉ huy sư đoàn kỵ binh bay; bộ chỉ huy sư đoàn kỵ binh bọc thép"),
(1412, "CAV SQDN (cavalry squadron)", "tiểu đoàn kỵ binh bọc thép; tiểu đoàn kỵ binh bay"),
(1412, "CAVU (ceiling and visibility unlimited)", "trần mây và tầm nhìn không hạn chế"),
(1412, "CAW (carrier air wing)", "phi đoàn không quân tàu sân bay"),
(1412, "CAW/ESS (crisis action weather and environmental support system)", "hệ thống bảo đảm khí tượng và môi trường cho hoạt động giải quyết khủng hoảng"),
(1412, "CAWS (cannon artillery weapons systems)", "pháo nòng dài thuộc hệ thống vũ khí pháo binh"),
(1412, "CAWS (close assault weapon system)", "hệ thống vũ khí tiến công (công kích) trực tiếp"),
(1412, "CAX (computer-assisted exercise)", "cuộc diễn tập chỉ huy - tham mưu được hỗ trợ bằng máy tính"),
(1412, "CB (chemical-biological)", "(thuộc) hoá - sinh"),
(1412, "CB (confinement to barracks)", "cấm trại; giam giữ trong doanh trại"),
(1412, "CB (construction battalion)", "tiểu đoàn xây dựng, tiểu đoàn công binh công trình"),
(1412, "CB (construction battalion (SEABEES))", "tiểu đoàn công binh công trình hải quân"),
(1412, "CB (counterbattery)", "(thuộc) phản pháo"),
(1412, "CBBLS (hundreds of barrels)", "hàng trăm thùng; hàng trăm nòng súng"),
(1412, "CBD (Canadian Brigade)", "lữ đoàn Canada"),
(1412, "CBD (chemical, biological defense)", "phòng thủ hoá học, sinh học"),
(1412, "CBF (Commander, British Forces)", "tư lệnh (trưởng) các lực lượng của Anh"),
]
