# -*- coding: utf-8 -*-
# Part 2: pages 1401-1406 (idx0636-idx0641)

entries = [
# ---- page 1401 (idx0636) ----
(1401, "bkry (bakery)", "bếp ăn"),
(1401, "BKS; bks (barracks)", "vị trí đóng quân, doanh trại; trại lính"),
(1401, "BL (battery leader)", "đại đội trưởng pháo binh"),
(1401, "BL (blank)", "vị trí trống, chỗ trống; (lỗ) tâm của đầu ngắm vòng; (đạn) giả, đạn không đầu"),
(1401, "BL (bombline)", "tuyến ném bom"),
(1401, "BL (breech-loading)", "sự nạp (đạn) bằng khóa nòng"),
(1401, "BL gun (breech loading gun)", "súng nạp đạn bằng khóa nòng"),
(1401, "BLCP (beach lighterage control point)", "điểm kiểm soát sà lan chở hàng trên bến"),
(1401, "BICS (battlefield information control system)", "hệ thống kiểm soát thông tin (cấp) chiến thuật"),
(1401, "BLDG (building)", "công trình xây dựng; nhà cửa"),
(1401, "BIDS (battlefield information distribution system)", "hệ thống phân phối thông tin (cấp) chiến thuật"),
(1401, "BLDSHIPREP (blood shipment report)", "báo cáo việc chuyên chở tiếp tế máu"),
(1401, "BLEU system (blind landing experimental unit system)", "hệ thống thiết bị thử nghiệm hạ cánh bằng khí cụ"),
(1401, "BIFF (battlefield identification friend or foe)", "sự nhận biết địch - ta (cấp) chiến thuật"),
(1401, "BLL (billet)", "nhà ở"),
(1401, "BLM (Bureau of Land Management)", "cục quản lý đất đai"),
(1401, "BIM (ballistic intercept missile)", "tên lửa đánh chặn tên lửa đạn đạo"),
(1401, "BLN (balloon)", "khí cầu, bóng thám không"),
(1401, "BLOS (beyond line of sight)", "nằm ngoài tầm ngắm; nằm ngoài tuyến quan sát"),
(1401, "BIP (blown in place)", "kích nổ tại chỗ (bãi mìn)"),
(1401, "BLS (beach landing site)", "vị trí bãi đổ bộ đường biển"),
(1401, "BLT (battalion landing team)", "nhóm đổ bộ của tiểu đoàn; cụm đổ bộ cấp tiểu đoàn"),
(1401, "BL-T (blank tracer)", "đạn vạch đường giả"),
(1401, "BLU (bomb live unit)", "khối chiến đấu trong bom"),
(1401, "BM (ballistic missile)", "tên lửa đạn đạo, tên lửa đường đạn"),
(1401, "BM (battle management)", "sự điều hành chiến đấu"),
(1401, "BM (beachmaster)", "người chỉ huy trạm đổ quân đổ bộ đường biển; sĩ quan chuyên trách về bảo đảm bãi đổ bộ đường biển"),
(1401, "BM (brigade major)", "(Anh) trưởng ban trinh sát lữ đoàn; trưởng ban tác chiến - trinh sát (cơ quan tham mưu) lữ đoàn"),
(1401, "BMA (beach maintenance area)", "khu vực bảo đảm bờ biển (cho đổ bộ đường biển)"),
(1401, "BMB (Ballistic Missile Branch)", "ngành tên lửa đạn đạo"),
(1401, "BMC (Ballistic Missile Center)", "trung tâm tên lửa đạn đạo"),
(1401, "BMC (Ballistic Missile Committee)", "ủy ban tên lửa đạn đạo"),
(1401, "BMC3 (Battle Management Command, Control and Communications)", "quản lý chỉ huy, kiểm soát và thông tin liên lạc chiến đấu"),
(1401, "BMC4I (Battle Management Command, Control, Communications, Computers, and Intelligence)", "quản lý chỉ huy, kiểm soát, thông tin liên lạc, máy tính và tình báo chiến đấu"),
(1401, "BMCO (Ballistic Missile Construction Office)", "cục xây dựng căn cứ tên lửa đạn đạo"),
(1401, "BMCT (begin morning civil twilight)", "thời điểm bắt đầu bình minh dân sự"),
(1401, "BMD (ballistic missile defence)", "sự phòng thủ tên lửa đạn đạo, sự phòng chống tên lửa đường đạn"),
(1401, "BMD (Ballistic Missile Division)", "sư đoàn tên lửa đạn đạo"),
(1401, "BMD (Boyevaya mashina desantnya (airborne fighting vehicle))", "(Nga) xe chiến đấu đổ bộ đường không"),

# ---- page 1402 (idx0637) ----
(1402, "BMDC (Ballistic Missile Defense Committee)", "uỷ ban phòng thủ tên lửa đạn đạo"),
(1402, "BMDCP (Battalion Mortar and Davy Crockett Platoon)", "trung đội pháo cối và tên lửa Đavi Crôkét (trong tiểu đoàn)"),
(1402, "BMD-FO (Ballistic Missile Division-Field Office)", "phòng dã chiến cục tên lửa đạn đạo"),
(1402, "BMDO (Ballistic Missile Defense Organization)", "tổ chức phòng thủ tên lửa đạn đạo"),
(1402, "bmdr (bombardier)", "(Anh) hạ sĩ pháo binh; (Mỹ) nhân viên cắt bom"),
(1402, "BMDS (ballistic missile defense system)", "hệ thống phòng thủ tên lửa đạn đạo"),
(1402, "BMDSCOM (Ballistic Missile Defence Systems Command)", "(Mỹ) bộ tư lệnh các hệ thống phòng thủ tên lửa đạn đạo"),
(1402, "BMDSS (ballistic missile defense support system)", "hệ thống bảo đảm phòng thủ tên lửa đạn đạo"),
(1402, "BMEWS (ballistic missile early warning system)", "hệ thống phát hiện từ xa tên lửa đạn đạo, hệ thống cảnh báo sớm tên lửa đạn đạo"),
(1402, "BMNT (begining of morning nautical twilight)", "thời điểm bắt đầu bình minh hàng hải"),
(1402, "BMO (Ballistic Missile Office)", "viện nghiên cứu tên lửa đạn đạo"),
(1402, "BMP (boevaya mashina pekhoty (armored vehicle, infantry))", "(Nga) xe chiến đấu bộ binh BMP"),
(1402, "BMR; bmr (bomber)", "máy bay ném bom, máy bay cường kích"),
(1402, "BMRA (brigade major, Royal Artillery)", "(Anh) trưởng ban trinh sát tác chiến lữ đoàn pháo binh"),
(1402, "BMS (ballistic missile specification)", "thông số kỹ thuật tên lửa đạn đạo"),
(1402, "BMS (battalion mortar system)", "tổ hợp súng cối (cấp) tiểu đoàn"),
(1402, "BMS (battlefield maintenance system)", "hệ thống bảo dưỡng (cấp) chiến thuật"),
(1402, "BMTS (ballistic missile target system)", "hệ thống mục tiêu (huấn luyện bắn) tên lửa đạn đạo"),
(1402, "BMU (beachmaster unit)", "đơn vị chuyên trách bảo đảm bãi đổ bộ"),
(1402, "BN; bn (battalion)", "tiểu đoàn"),
(1402, "BN HQ (battalion headquarters)", "sở chỉ huy tiểu đoàn; ban chỉ huy tiểu đoàn"),
(1402, "BNES (British Nuclear Energy Society)", "hội năng lượng hạt nhân Anh"),
(1402, "BO (bad order)", "toa xe cũ hỏng"),
(1402, "BOB (bureau of the budget)", "phòng ngân sách"),
(1402, "BOBS (beacon-only bombing system)", "hệ thống ném bom theo vật chuẩn"),
(1402, "BOC (base operations centre)", "trung tâm chỉ huy tác chiến cơ bản"),
(1402, "BOCCA (Bureau of Coordination of Civil Aircraft)", "(NATO) cục điều phối máy bay dân sự NATO"),
(1402, "BOCV (battery operations centre vehicle)", "xe chỉ huy tác chiến của đại đội pháo binh"),
(1402, "BOG (beach operations group)", "cụm tác chiến bảo đảm bãi đổ bộ"),
(1402, "BOH (bottom of hill)", "chân đồi"),
(1402, "BOI (basis of issue)", "bảng biên chế định mức tiếp tế"),
(1402, "BOL (bearing only launch)", "sự phóng theo phương vị"),
(1402, "BOLD (battlefield operations laser designator)", "máy lade chỉ thị mục tiêu chiến thuật"),
(1402, "Bomb (bombardment)", "oanh tạc, oanh kích"),
(1402, "Bomb (Sq) (GP) (WG) (L) (M) (H) (bomber (squadron), (group), (wing), (light), (medium), (heavy))", "máy bay ném bom (phi đội), (liên phi đội), (phi đoàn), (hạng nhẹ), (hạng trung), (hạng nặng)"),
(1402, "BOMREP (bombing report)", "(bản) báo cáo về oanh tạc của không quân địch"),
(1402, "BOP (basic operations plan)", "kế hoạch tác chiến cơ bản, kế hoạch chiến dịch cơ bản"),

# ---- page 1403 (idx0638) ----
(1403, "BOQ (bachelor officer's quarters)", "nhà ở cho sĩ quan độc thân"),
(1403, "BOR (British other ranks)", "đội ngũ binh sĩ quân đội Anh"),
(1403, "BOS (base operating support)", "sự bảo đảm vận hành căn cứ"),
(1403, "BOS (battlefield operating systems)", "tổ hợp vũ khí tác chiến (cấp) chiến thuật"),
(1403, "BOSG (base operations support group)", "cụm chi viện tác chiến phòng thủ căn cứ"),
(1403, "BOSO (bureau of ordnance shipment order)", "lệnh gửi hàng của phòng quân dụng"),
(1403, "BOSS (ballistic optimizing shooting system)", "hệ thống ngắm bắn theo đường đạn tối ưu"),
(1403, "BOW (basic operating weight)", "trọng lượng tác chiến cơ bản; khối lượng hoạt động cơ bản"),
(1403, "BP (base point)", "mốc định hướng chính; vật chuẩn chính, điểm chuẩn; điểm đáy"),
(1403, "BP (battle position)", "vị trí chiến đấu; trận địa chiến đấu"),
(1403, "BP (beach party)", "đội bờ biển, nhóm bờ biển; toán gần bờ; (hq) phân đội bảo đảm đổ bộ đường biển"),
(1403, "BP (black powder)", "thuốc (súng) đen, thuốc phóng có khói"),
(1403, "BPD (blood products depot)", "kho sản phẩm máu"),
(1403, "BPDMS (base point defence missile system)", "hệ thống tên lửa phòng thủ cứ điểm"),
(1403, "BPE (bomber penetration evaluation)", "(bản) đánh giá khả năng xâm nhập (của) máy bay ném bom"),
(1403, "BPO (base pay office)", "trạm phát tiền của căn cứ"),
(1403, "BPO (blood program office)", "văn phòng chương trình máu"),
(1403, "BPPBS (bi-annual planning, programming, and budget system)", "hệ thống lập kế hoạch, lập trình và ngân sách một năm hai lần"),
(1403, "BPR (bypass ratio)", "hệ số phân luồng"),
(1403, "BPRF (bulletproof)", "(thuộc) chống đạn, (thuộc) đạn không xuyên qua"),
(1403, "BPS (basic psychological operations study)", "nghiên cứu hoạt động tâm lý chiến cơ bản"),
(1403, "BPSK (bi-phase shift keying)", "thiết bị tạo mã dịch pha nhị phân"),
(1403, "BPT (beach party team)", "đội bảo đảm bãi đổ bộ"),
(1403, "BPWRR (bulk petroleum war reserve requirement)", "nhu cầu dự trữ xăng dầu cho chiến tranh"),
(1403, "BPWRS (bulk petroleum war reserve stocks)", "các kho dự trữ xăng dầu cho chiến tranh"),
(1403, "BQMS (battery quartermaster sergeant)", "trung sĩ hậu cần đại đội pháo binh"),
(1403, "Br (branch)", "binh chủng; ngành (nghiệp vụ); phòng; ban; cục; đơn vị (tham mưu)"),
(1403, "Br (bridge)", "cầu"),
(1403, "BR (budget review)", "xem xét lại ngân sách; duyệt ngân sách"),
(1403, "br tr (bridge train)", "đội cầu; trạm cầu phao; trạm cầu vượt"),
(1403, "BRA (Brigadier, Royal Artillery)", "(Anh) lữ đoàn trưởng pháo binh; chuẩn tướng pháo binh"),
(1403, "BRA (British Regular Army)", "quân đội chính quy Anh, quân đội chủ lực liên hiệp Anh"),
(1403, "BRAAA (Brigadier, Royal Antiaircraft Artillery)", "(Anh) lữ đoàn trưởng pháo phòng không; chuẩn tướng pháo phòng không"),
(1403, "BRAC (Brigadier, Royal Armoured Corps)", "(Anh) thiếu tướng tư lệnh quân đoàn tăng thiết giáp"),
(1403, "branne (bombing radar navigation equipment)", "thiết bị dẫn đường ném bom bằng rađa"),
(1403, "BRASCO (Brigade Royal Army Service Corps Officer)", "người chỉ huy ngành bảo đảm và tiếp vận lữ đoàn; sĩ quan ngành bảo đảm và tiếp vận lữ đoàn"),
(1403, "BRC (base recovery course)", "quá trình khôi phục căn cứ"),

# ---- page 1404 (idx0639) ----
(1404, "BRD (bomb release distance)", "khoảng cách ném bom"),
(1404, "BRDM (bronirovannaya razvedyvatyelno dozornaya (armored reconnaissance patrol vehicle))", "(Nga) xe tuần tiễu trinh sát bọc thép BRDM"),
(1404, "BRE (battlefield recovery & evacuation)", "(hoạt động) cứu kéo trên chiến trường"),
(1404, "brev (brevet)", "quyết định phong quân hàm (nhưng không lên lương)"),
(1404, "brg (bearing)", "phương vị, góc phương vị, góc hướng"),
(1404, "brg (bridge)", "cầu"),
(1404, "Brg Co (bridge company)", "đại đội cầu, đại đội công binh bắc cầu"),
(1404, "BRGHD; Brh; brhd (bridgehead)", "đầu cầu; căn cứ đầu cầu; vị trí đầu cầu"),
(1404, "brig (brigade)", "lữ đoàn"),
(1404, "brig (brigadier)", "lữ đoàn trưởng; (Anh) chuẩn tướng"),
(1404, "Brig Gen (brigadier general)", "tướng cấp lữ đoàn"),
(1404, "Brig. Comdr. (brigade commander)", "lữ đoàn trưởng, chỉ huy trưởng lữ đoàn"),
(1404, "Brig-Gen (brigadier-general)", "tướng cấp lữ đoàn; (Mỹ) chuẩn tướng không quân"),
(1404, "BRL (bomb release line)", "tuyến ném bom, tuyến cắt bom"),
(1404, "BRP (braked retarded parachute)", "dù hãm"),
(1404, "Brs (bridges)", "những chiếc cầu"),
(1404, "BS Trc (bomb service truck)", "xe chở bom"),
(1404, "BS (battle staff)", "binh đội chiến đấu (của) cơ quan tham mưu"),
(1404, "BSA (beach support area)", "khu vực chi viện bãi đổ bộ"),
(1404, "BSA (brigade support area)", "khu vực chi viện của lữ đoàn"),
(1404, "BSC (black station clock)", "lịch liên lạc tại trạm mật"),
(1404, "BSC ro (black station clock receive out)", "không được liên lạc với trạm mật"),
(1404, "BSD (Ballistic Systems Division)", "cục hệ thống đạn đạo"),
(1404, "BSFV (Bratley Stinger fighting vehicle)", "xe chiến đấu Brátlây Stingơ"),
(1404, "BSL (bomb safety line)", "tuyến ném bom an toàn"),
(1404, "BSM (battery sergeant major)", "chuẩn uý đại đội pháo binh"),
(1404, "BSM (Bronze Star Medal)", "huy chương \"Sao đồng\" (vì tham gia một trận đánh)"),
(1404, "BSP (base support plan)", "kế hoạch chi viện hoả lực của căn cứ; kế hoạch bảo đảm chi viện của căn cứ"),
(1404, "bsr (balloon-supported rockets)", "tên lửa đặt trên khí cầu"),
(1404, "BSSG (brigade service support group)", "nhóm bảo đảm hậu cần chiến đấu của lữ đoàn"),
(1404, "BSU (blood supply unit)", "đơn vị tiếp tế máu"),
(1404, "BT (ballast tank)", "khoang chứa nước (trong tàu ngầm để giữ cho tàu thăng bằng)"),
(1404, "BT (base trainer)", "(kq) máy bay huấn luyện bay cơ bản"),
(1404, "BT (basic training)", "sự huấn luyện cơ bản, sự huấn luyện mở đầu; khoá huấn luyện chiến đấu cơ bản"),
(1404, "BT (bullet trap)", "bẫy đạn, bộ giữ đạn"),
(1404, "BTA (best technical approach)", "(kq) sự tiếp cận hạ cánh bằng kỹ thuật tối ưu; sự tiếp cận mục tiêu bằng kỹ thuật tối ưu"),
(1404, "BTB (believed-to-be)", "tin là có; tin là đúng"),
(1404, "BTC (blood transshipment center)", "trung tâm truyền máu"),
(1404, "BTE (brake thermal efficiency)", "nhiệt năng của phanh"),
(1404, "BTF (ballistic test facility)", "thiết bị thử nghiệm đường đạn"),
(1404, "BTG (basic target graphic)", "sơ đồ mục tiêu chủ yếu"),
(1404, "BTO (bombing through overcast)", "sự ném bom từ sau đám mây"),
(1404, "BTOC (battalion tactical operations center)", "trung tâm chỉ huy tác chiến chiến thuật tiểu đoàn"),

# ---- page 1405 (idx0640) ----
(1405, "BTR (brone transporter (armored transporter))", "(Nga) xe vận tải bọc thép BTR, xe thiết giáp vận tải"),
(1405, "BTRY; Btry; btry (battery)", "pin; ắc quy; (Mỹ) khẩu đội pháo; đại đội pháo"),
(1405, "Btry comdr (battery commander)", "đại đội trưởng pháo binh; (Mỹ) khẩu đội trưởng"),
(1405, "BTRY HQ (battery headquarters)", "sở chỉ huy đại đội pháo; ban chỉ huy đại đội pháo binh"),
(1405, "BTT (basic training target)", "bia huấn luyện cơ bản"),
(1405, "BTU (beach termination unit)", "đơn vị chuẩn bị hoàn chỉnh bãi đổ bộ đường biển"),
(1405, "BTU (British thermal unit)", "đơn vị nhiệt của Anh (bằng 252 calo)"),
(1405, "BTU (bullet trap, universal)", "bẫy đạn thông dụng"),
(1405, "BTWC (Biological & Toxin Weaponry Convention)", "công ước (quốc tế) về vũ khí sinh học và chất độc"),
(1405, "Bu (bureau)", "cục; nha; vụ; phòng"),
(1405, "Bu; bush (bushel)", "thùng 35 lít"),
(1405, "BUIC (back-up intercep control)", "(thiết bị) điều khiển đánh chặn dự phòng (phòng không)"),
(1405, "BUIC (back-up interceptor control)", "hệ thống điều khiển các phương tiện đánh chặn đường không dự bị; tổ hợp điều khiển máy bay đánh chặn đường không dự bị"),
(1405, "BUL (bulletin)", "thông cáo, thông báo; bản tin"),
(1405, "BULK (bulk cargo)", "hàng hoá đóng thùng"),
(1405, "BV (boost vehicle)", "thiết bị tăng tốc"),
(1405, "BVR (beyond visual range)", "ngoài tầm quan sát, ngoài tầm nhìn thấy được, vượt tầm nhìn"),
(1405, "BW (bacteriological warhead)", "(tl) phần chiến đấu mang đầu đạn vi trùng; phần chiến đấu mang đầu đạn sinh học"),
(1405, "BW (bacteriological weapons)", "vũ khí vi trùng"),
(1405, "BW (basic weapons)", "vũ khí chủ yếu, vũ khí cơ bản"),
(1405, "BW (biological warfare)", "chiến tranh sinh học, tác chiến vi trùng"),
(1405, "BW (biological weapons)", "vũ khí sinh học; phương tiện chiến tranh sinh học"),
(1405, "BWC (Biological Weapons Convention)", "công ước Liên hiệp quốc về cấm và thủ tiêu vũ khí sinh học"),
(1405, "bw-cw (biological warfare-chemical warfare)", "chiến tranh sinh - hóa; tác chiến hóa học và sinh học"),
(1405, "BWM (British War Medal)", "huy chương quân sự vương quốc Anh"),
(1405, "Bx (box)", "hộp, gói"),
(1405, "BY (budget year)", "năm tài chính"),
(1405, "BZ (buffer zone)", "vùng đệm"),

# ---- page 1406 (idx0641) ----
(1406, "C (camp)", "(k. hiệu) vị trí đóng quân; doanh trại; lối sống kiểu \"trại lính\""),
(1406, "C (carrier)", "(k. hiệu) phương tiện vận tải; xe vận tải (bọc thép); máy bay vận tải; tàu sân bay"),
(1406, "C (combat)", "trận chiến đấu, trận đánh; (thuộc) chiến đấu"),
(1406, "C (commandant)", "(k. hiệu) người chỉ huy, tư lệnh (trưởng); hiệu trưởng nhà trường"),
(1406, "C (corps)", "(k. hiệu) quân đoàn; (thuộc) quân đoàn"),
(1406, "C and EWD (clothing and equipment war dept)", "quân trang và quân dụng"),
(1406, "C and F (cost and freight)", "đơn giá bao gồm cả cước vận chuyển"),
(1406, "C bomb (cobalt bomb)", "bom côban"),
(1406, "C car (combat car)", "(k. hiệu) xe chiến đấu"),
(1406, "C&A (certification and accreditation)", "chứng chỉ và công nhận chính thức"),
(1406, "C&C (command & control)", "chỉ huy và điều khiển, hệ thống C2"),
(1406, "C&L (command and liaison)", "chỉ huy và thông tin liên lạc"),
(1406, "C&LAT (cargo and loading analysis table)", "bảng phân tích hàng hoá và bốc xếp"),
(1406, "C&N (communication and navigation)", "thông tin liên lạc và dẫn đường"),
(1406, "C&T (conversion and training)", "sự huấn luyện và đào tạo lại"),
(1406, "C&WCh (caution and warning system check)", "kiểm tra hệ thống cảnh báo và phòng ngừa"),
(1406, "C.M.S. (center of mass system)", "trọng tâm; hệ khối tâm"),
(1406, "C.of G.S. (chief of general staff)", "tổng tham mưu trưởng"),
(1406, "C.R. (compression ratio)", "tỷ số nén"),
(1406, "C/A (counterattack)", "phản kích, phản công"),
(1406, "C/C (cabin cruiser)", "tàu tuần dương có khoang lái kín"),
(1406, "C/C (cast off and clear)", "nhổ neo và rời bến"),
(1406, "C/R (certificate of retirement)", "giấy chứng nhận về hưu; sổ hưu"),
(1406, "C/R (counter-rotating (propellers))", "cơ cấu phản lực chống quay"),
(1406, "C/S (chief of staff)", "tham mưu trưởng"),
(1406, "C1 (counterintelligence)", "phản gián, chống gián điệp"),
(1406, "C2 (command and control)", "(hệ thống) chỉ huy và kiểm soát, hệ thống C2"),
(1406, "C2 (Conveyer 240 airplane)", "(k.hiệu) máy bay Convâyơ 240"),
(1406, "C2-attack (an offensive form of command and control warfare)", "hình thức tiến công của tác chiến chỉ huy và kiểm soát"),
(1406, "C2E (command and control element)", "thành phần chỉ huy và kiểm soát"),
(1406, "C2IP (Command and Control Initiatives Program)", "kế hoạch giành thế chủ động chỉ huy và kiểm soát"),
]
