"""Build chunk_0618_0632.csv from manual vision transcription of
docs/db/import/tudien_abbr_pages/idx0618.png .. idx0632.png
(printed pages 1383-1397 of Tu_dien.pdf, printed_page = idx + 765).

Each tuple is (printed_page, word, meaning_vi).
"""
import csv

DICTIONARY_NAME = "Military Dictionary"

# (printed_page, word, meaning_vi)
ENTRIES = [
    # ---- page 1383 (idx0618) ----
    (1383, "ARM (antiradar missile)", "tên lửa chống rada, tên lửa chống vô tuyến định vị"),
    (1383, "ARM (anti-radiation missile)", "tên lửa chống bức xạ"),
    (1383, "ARM (armament)", "vũ khí trang bị"),
    (1383, "ARM (artillery rearm module)", "môđun nạp đạn pháo"),
    (1383, "ARM (availability, reliability, maintainability)", "(khả năng) sẵn có, đáng tin cậy, dễ bảo dưỡng"),
    (1383, "Arm. C (armor command)", "bộ chỉ huy tăng thiết giáp, bộ tư lệnh tăng thiết giáp"),
    (1383, "ARMAD (Armoured and Mechanised Unit Air Defence)", "(hệ thống) phòng không của đơn vị bọc thép và cơ giới"),
    (1383, "armd (armored)", "bọc thép, thiết giáp; tăng thiết giáp"),
    (1383, "armd cav sqdn (armored cavalry squadron)", "tiểu đoàn trinh sát; tiểu đoàn kỵ binh bọc thép; tiểu đoàn tăng thiết giáp"),
    (1383, "armd div arty (armored division artillery)", "pháo binh của sư đoàn kỵ binh bọc thép"),
    (1383, "armd div tn (armored division trains)", "căn cứ hậu cần sư đoàn kỵ binh bọc thép"),
    (1383, "armd heptr (armored helicopter)", "máy bay trực thăng bọc thép"),
    (1383, "armd TF (armored task force)", "lực lượng đặc nhiệm (xe) bọc thép"),
    (1383, "armd veh (armored vehicle)", "xe bọc thép, xe thiết giáp"),
    (1383, "ARM-D (anti-radiation missile decoy)", "mồi bẫy đánh lừa tên lửa chống bức xạ"),
    (1383, "armd cav regt (armored cavalry regiment)", "trung đoàn trinh sát; trung đoàn kỵ binh bọc thép; trung đoàn tăng thiết giáp"),
    (1383, "armd cav trp (armored cavalry troop)", "đại đội trinh sát; đại đội kỵ binh bọc thép; đại đội tăng thiết giáp"),
    (1383, "Armd Div (armored division)", "sư đoàn tăng thiết giáp"),
    (1383, "Armd. C (armored car)", "xe bọc thép, xe thiết giáp"),
    (1383, "Armd-F (armored force)", "đơn vị tăng thiết giáp; lực lượng tăng thiết giáp"),
    (1383, "ARMLO (army liaison officer)", "sĩ quan liên lạc hiệp đồng lục quân"),
    (1383, "ARMS (armored resupply maintenance system)", "hệ thống bảo đảm hậu cần kỹ thuật tăng thiết giáp"),
    (1383, "ARMSCOR (Armament Manufacturing Corporation (South Africa))", "tổng công ty chế tạo vũ khí trang bị (Nam Phi)"),
    (1383, "ARMT (armament)", "sự vũ trang, sự trang bị vũ khí; vũ khí trang bị; súng lớn; pháo (tàu)"),
    (1383, "ARNA (Army with Navy)", "đơn vị lục quân phối thuộc với hải quân"),
    (1383, "ARNG (Army National Guard)", "đội cận vệ quốc gia lục quân"),
    (1383, "ARNGUS (Army National Guard of the United States)", "đội cận vệ quốc gia lục quân Mỹ"),
    (1383, "ARO (Army Research Office)", "cục nghiên cứu lục quân"),
    (1383, "ARO (army routine order)", "điều lệnh nội vụ quân đội"),
    (1383, "AROTC (Air Reserve Officers Training Corps)", "ngành huấn luyện sĩ quan dự bị không quân"),
    (1383, "ARP (air raid precautions)", "phòng tránh tập kích đường không"),
    (1383, "ARP (air-raid protection (precaution))", "sự ngăn chặn tiến công đường không, sự đề phòng không kích, phòng chống tập kích đường không"),
    (1383, "ARP (air refueling point)", "điểm tiếp dầu trên không"),
    (1383, "ARP (ammunition refilling point)", "trạm đổi đạn dược"),
    (1383, "ARP (anti-radiation projectile)", "đạn (pháo) chống phóng xạ"),
    (1383, "ARP (Armoured Repair Plates)", "bộ đồ sửa chữa xe thiết giáp"),

    # ---- page 1384 (idx0619) ----
    (1384, "ARPA (Advanced Research Projects Agency)", "cục dự án nghiên cứu triển vọng (vũ khí trang bị), cục lập kế hoạch nghiên cứu khoa học dài hạn"),
    (1384, "ARPERCEN (United States Army Reserve Personnel Center)", "trung tâm quản lục lực lượng dự bị lục quân Mỹ"),
    (1384, "ARQ (automatic request-repeat)", "(cơ chế) tự động lặp lại yêu cầu"),
    (1384, "ARRADCOM (Armament Research and Development Command)", "bộ tư lệnh nghiên cứu và phát triển vũ khí trang bị"),
    (1384, "ARRC (Allied Command Europe Rapid Reaction Corps (NATO))", "quân đoàn phản ứng nhanh thuộc bộ tư lệnh liên quân NATO ở châu Âu"),
    (1384, "ARRV (armored recovery and repaire vehicle)", "xe bọc thép cứu kéo và sửa chữa"),
    (1384, "ARRV (Armoured Repair and Recovery Vehicle)", "xe bọc thép sửa chữa và thu hồi vũ khí trang bị; xe bọc thép sửa chữa và cứu kéo"),
    (1384, "ARS (aerial radiac system)", "hệ thống chỉ báo phóng xạ trên máy bay"),
    (1384, "ars (aerospace research satellite)", "vệ tinh nghiên cứu vũ trụ"),
    (1384, "ARS (air reinforcement squadron)", "tiểu đoàn không quân tăng cường"),
    (1384, "ARS (American Rocket Society)", "hội tên lửa Hoa Kỳ"),
    (1384, "ARS (Army Recreational Service)", "ngành tổ chức nghỉ ngơi cho quân nhân, ngành giải trí quân đội"),
    (1384, "ARS (automatic frequency selection)", "sự chọn tần số tự động; tự động chọn tần số"),
    (1384, "ARS (automatic reporting system)", "hệ thống tự động báo cáo"),
    (1384, "ARSOA (Army special operations aviation)", "không quân thuộc lực lượng tác chiến đặc biệt lục quân"),
    (1384, "ARSOC (army special operations commander)", "chỉ huy trưởng lực lượng tác chiến đặc biệt lục quân"),
    (1384, "ARSOC (Army special operations component)", "binh chủng thuộc lực lượng tác chiến đặc biệt lục quân"),
    (1384, "ARSOF (Army special operations forces)", "các lực lượng tác chiến đặc biệt lục quân"),
    (1384, "ARSOTF (Army special operations task force)", "lực lượng đặc nhiệm tác chiến đặc biệt của lục quân"),
    (1384, "ARSPACE (Army Space Command)", "bộ tư lệnh vũ trụ của lục quân"),
    (1384, "ARSPOC (Army space operations center)", "trung tâm chỉ huy tác chiến vũ trụ của lục quân"),
    (1384, "ARSR (air-route surveillance radar)", "rada giám sát đường bay, rada giám sát lộ trình bay"),
    (1384, "ARSV (armored reconnaissance scout vehicle)", "(Mỹ) xe bọc thép tuần tiễu trinh sát"),
    (1384, "ARSV (Armored Reconnaissance Scout Vehicle (US))", "xe bọc thép trinh sát do thám (Mỹ)"),
    (1384, "ART (air-refuelling transport)", "(máy bay) tiếp nhiên liệu trên không"),
    (1384, "ART (air reserve technician)", "kỹ thuật viên lực lượng dự bị không quân"),
    (1384, "Art (artillery)", "pháo binh"),
    (1384, "ARTCC (air route traffic control center)", "trung tâm kiểm soát giao thông đường không; trung tâm kiểm soát không lưu"),
    (1384, "ARTOC (Army Tactical Operation Center)", "trung tâm thử nghiệm tác chiến chiến thuật lục quân"),
    (1384, "ARTS (Automated Radar Tracking System)", "hệ thống rada tự động phát hiện và bám sát mục tiêu"),
    (1384, "ARTY; arty (artillery)", "pháo binh"),
    (1384, "arty bn (artillery battalion)", "tiểu đoàn pháo binh"),
    (1384, "Arty Brig. (artillery brigade)", "lữ đoàn pháo binh"),
    (1384, "Arty C (artillery command)", "bộ chỉ huy pháo binh, bộ tư lệnh pháo binh"),

    # ---- page 1385 (idx0620) ----
    (1385, "arty gp (artillery group)", "cụm pháo binh"),
    (1385, "Arty How Bn (artillery howitzer battalion)", "tiểu đoàn lựu pháo"),
    (1385, "arty msl bn (artillery missile battalion)", "tiểu đoàn tên lửa của pháo binh"),
    (1385, "arty psn (artillery position)", "trận địa pháo binh"),
    (1385, "arty spt (artillery support)", "sự chi viện hoả lực pháo binh"),
    (1385, "arty stf sec (artillery staff section)", "phân đội tham mưu pháo binh"),
    (1385, "arty wpn (artillery weapon)", "vũ khí pháo binh, pháo binh"),
    (1385, "arty wpns sys (artillery weapons system)", "tổ hợp pháo binh"),
    (1385, "ARV (air reconnaissance vehicle)", "phương tiện trinh sát đường không"),
    (1385, "ARV (armored recovery vehicle)", "xe bọc thép cứu kéo; xe tăng kéo"),
    (1385, "ARWC (Army War College)", "trường chiến tranh lục quân"),
    (1385, "AS (air-to-surface)", "không đối mặt (đất, biển)"),
    (1385, "AS (ammunition storage)", "kho đạn dược"),
    (1385, "AS (analog secure)", "sự bảo đảm an toàn theo thuật tương tự"),
    (1385, "AS (anti-submarine)", "chống tàu ngầm, chống ngầm"),
    (1385, "AS; ASW (Anti-submarine (warfare))", "chiến tranh chống ngầm; tác chiến chống ngầm"),
    (1385, "AS (army security)", "ngành an ninh quân đội; ngành an ninh lục quân"),
    (1385, "ASA (Advanced Security Agency)", "cơ quan an ninh cấp cao"),
    (1385, "ASA (Army Satcom Agency)", "cục thông tin liên lạc vệ tinh quân đội; cục thông tin liên lạc vệ tinh lục quân"),
    (1385, "ASA (Army Security Agency)", "cục an ninh quân đội; cục an ninh lục quân"),
    (1385, "ASA (Assistant Secretary of the Army)", "trợ lý bộ trưởng bộ lục quân"),
    (1385, "ASALM (advanced strategic air-launched missile)", "tên lửa chiến lược cải tiến được phóng từ trên không"),
    (1385, "ASAP (Army Scientific Advisory Panel)", "hội đồng tư vấn khoa học lục quân"),
    (1385, "ASAP (as soon as possible)", "càng sớm càng tốt"),
    (1385, "ASARS (Advanced Synthetic Aperture Radar System)", "hệ thống rada ống kính bằng chất dẻo tổng hợp cải tiến"),
    (1385, "ASAS (all source analysis system)", "(Mỹ) hệ thống phân tích mọi nguồn thông tin"),
    (1385, "ASAT (air search attack team)", "phi đội không quân tìm diệt"),
    (1385, "ASAT (anti-satellite systems)", "hệ thống phòng thủ vệ tinh, hệ thống phòng chống vệ tinh"),
    (1385, "ASAT (anti-satellite)", "chống vệ tinh"),
    (1385, "ASAU (air search attack unit)", "phân đội không quân tìm diệt"),
    (1385, "ASBCCC (Airborne Battlefield command Control Centre)", "sở chỉ huy của bộ tư lệnh chiến trường đặt trên máy bay; máy bay chỉ huy chiến trường"),
    (1385, "ASBM (air-to-surface ballistic missile)", "tên lửa đạn đạo không đối mặt (đất, biển)"),
    (1385, "ASC (Acting Service Chief)", "quyền tham mưu trưởng quân chủng"),
    (1385, "ASC (Aeronautical Systems Center)", "trung tâm các hệ thống hàng không"),
    (1385, "ASC (Air Systems Command)", "bộ chỉ huy các hệ thống không quân"),
    (1385, "ASC (Armed Services Committee)", "hội đồng các ngành phục vụ lực lượng vũ trang (thuộc hạ nghị viện Mỹ)"),
    (1385, "ASC (Automatic Digital Network switching center)", "tổng đài thông tin liên lạc mạng kỹ thuật số tự động"),
    (1385, "ASC(A) (assault support coordinator (airborne))", "sĩ quan hiệp đồng chi viện xung phong (ngồi trên máy bay)"),
    (1385, "ASCC (Air Standardization Coordinating Committee)", "ủy ban phối hợp tiêu chuẩn hoá không quân"),
    (1385, "ASCIET (all services combat identification evaluation team)", "đội đánh giá dấu hiệu chiến đấu khác nhau của tất cả các quân binh chủng"),

    # ---- page 1386 (idx0621) ----
    (1386, "ASCII (American Standard Code for Information Interchange)", "bộ quy tắc tiêu chuẩn Mỹ về sự trao đổi tương hỗ thông tin"),
    (1386, "ASCM (anti-ship cruise missile)", "tên lửa hành trình đối hạm"),
    (1386, "ASCOM (Army Service Command)", "bộ chỉ huy phục vụ lục quân; bộ tư lệnh hậu cần của quân đội"),
    (1386, "ASCP (Army Strategic Capabilities Plan)", "kế hoạch sử dụng các phương tiện chiến lược lục quân"),
    (1386, "ASCS (air support control section)", "phân đội điều khiển chi viện hỏa lực đường không"),
    (1386, "ASD (Aeronautical Systems Division)", "cục hệ thống hàng không của không quân"),
    (1386, "ASD (Assistant Secretary of Defense)", "trợ lý bộ trưởng bộ quốc phòng; thứ trưởng bộ quốc phòng"),
    (1386, "ASD(A&L) (Assistant Secretary of Defense (Acquisition and Logistics))", "trợ lý bộ trưởng bộ quốc phòng (về mua sắm và hậu cần); thứ trưởng bộ quốc phòng (về mua sắm và hậu cần)"),
    (1386, "ASD(C) (Assistant Secretary of Defense (Comptroller))", "trợ lý bộ trưởng bộ quốc phòng (về tài chính); thứ trưởng bộ quốc phòng (về tài chính)"),
    (1386, "ASD(C3I) (Assistant Secretary of Defense (Command, Control, Communications, and Intelligence))", "trợ lý bộ trưởng bộ quốc phòng (về chỉ huy, kiểm soát, thông tin liên lạc và tình báo); thứ trưởng bộ quốc phòng (về chỉ huy, kiểm soát, thông tin liên lạc và tình báo)"),
    (1386, "ASD(FM&P) (Assistant Secretary of Defense (Force Management and Personnel))", "trợ lý bộ trưởng bộ quốc phòng (về quản lý lực lượng và quân lực); thứ trưởng bộ quốc phòng (về quản lý lực lượng và quân lực)"),
    (1386, "ASD(FMP) (Assistant Secretary of Defense (Force Management Policy))", "trợ lý bộ trưởng bộ quốc phòng (về chính sách quản lý và điều hành lực lượng); thứ trưởng bộ quốc phòng (về chính sách quản lý và điều hành lực lượng)"),
    (1386, "ASD(HA) (Assistant Secretary of Defense (Health Affairs))", "trợ lý bộ trưởng bộ quốc phòng (về các vấn đề y tế); thứ trưởng bộ quốc phòng (về các vấn đề y tế)"),
    (1386, "ASD(ISA) (Assistant Secretary of Defense (International Security Affairs))", "trợ lý bộ trưởng bộ quốc phòng (về các vấn đề an ninh quốc tế); thứ trưởng bộ quốc phòng (về các vấn đề an ninh quốc tế)"),
    (1386, "ASD(ISP) (Assistant Secretary of Defense (International Security Policy))", "trợ lý bộ trưởng bộ quốc phòng (về chính sách an ninh quốc tế); thứ trưởng bộ quốc phòng (về chính sách an ninh quốc tế)"),
    (1386, "ASD(LA) (Assistant Secretary of Defense (Legislative Affairs))", "trợ lý bộ trưởng bộ quốc phòng (về các vấn đề tư pháp); thứ trưởng bộ quốc phòng (về các vấn đề tư pháp)"),
    (1386, "ASD(P&L) (Assistant Secretary of Defense (Production and Logistics))", "trợ lý bộ trưởng bộ quốc phòng (về sản xuất và hậu cần); thứ trưởng bộ quốc phòng (về sản xuất và hậu cần)"),
    (1386, "ASD(PA) (Assistant Secretary of Defense (Public Affairs))", "trợ lý bộ trưởng bộ quốc phòng (về các vấn đề công cộng); thứ trưởng bộ quốc phòng (về các vấn đề công cộng)"),
    (1386, "ASD(PA&E) (Assistant Secretary of Defense (Program Analysis and Evaluation))", "trợ lý bộ trưởng bộ quốc phòng (về đánh giá và phân tích các chương trình); thứ trưởng bộ quốc phòng (về đánh giá và phân tích các chương trình)"),
    (1386, "ASD(RA) (Assistant Secretary of Defense (Reserve Affairs))", "trợ lý bộ trưởng bộ quốc phòng (về các vấn đề lực lượng dự bị); thứ trưởng bộ quốc phòng (về các vấn đề lực lượng dự bị)"),

    # ---- page 1387 (idx0622) ----
    (1387, "ASD(RSA) (Assistant Secretary of Defense (Regional Security Affairs))", "trợ lý bộ trưởng bộ quốc phòng (về các vấn đề an ninh khu vực); thứ trưởng bộ quốc phòng (về các vấn đề an ninh khu vực)"),
    (1387, "ASD(S&R) (Assistant Secretary of Defense (Strategy and Requirements))", "trợ lý bộ trưởng bộ quốc phòng (về chiến lược và các nhu cầu); thứ trưởng bộ quốc phòng (về chiến lược và các nhu cầu)"),
    (1387, "ASD(SO/LIC) (Assistant Secretary of Defense (Special Operations and Low Intensity Conflict))", "trợ lý bộ trưởng bộ quốc phòng (về tác chiến đặc biệt và xung đột cường độ thấp); thứ trưởng bộ quốc phòng (về tác chiến đặc biệt và xung đột cường độ thấp)"),
    (1387, "ASDC (alternative space defence centre)", "trung tâm phòng thủ vũ trụ dự phòng"),
    (1387, "ASDI (analog simple data interface)", "giao diện dữ liệu đơn giản theo kỹ thuật tương tự"),
    (1387, "ASE (aircraft survivability equipment)", "thiết bị duy trì sự an toàn của máy bay, thiết bị bảo đảm sự sống còn của máy bay; thiết bị (tự) khắc phục sự cố của máy bay"),
    (1387, "ASE (automatic stabilisation equipment)", "thiết bị ổn định tự động, thiết bị tự động ổn định"),
    (1387, "ASF (airsuperiority fighter)", "máy bay tiêm kích giành ưu thế trên không"),
    (1387, "ASG (area support group)", "cụm chi viện hỏa lực khu vực"),
    (1387, "ASG (assigned)", "được bổ nhiệm, được giao nhiệm vụ, được phiên chế"),
    (1387, "ASG (assignment)", "sự bổ nhiệm"),
    (1387, "ASGS (Assistant Secretary, General Staff)", "phó tổng tham mưu trưởng; trợ lý tổng tham mưu trưởng"),
    (1387, "ashp (airship)", "khí cầu máy"),
    (1387, "ASI (airspeed indicator)", "đồng hồ chỉ báo tốc độ bay"),
    (1387, "ASI (assign and display switch initialization)", "phân bổ và bố trí công tác tắt mở"),
    (1387, "ASIR (airspeed indicator reading)", "chỉ số tốc độ bay trên mặt đồng hồ"),
    (1387, "ASL (allowable supply list)", "danh sách cơ số cấp phát"),
    (1387, "ASL (assign switch locator routing)", "chỉ định lộ trình bằng công tác định vị"),
    (1387, "ASL (atomic safety line)", "tuyến an toàn sử dụng vũ khí hạt nhân, tuyến an toàn hạt nhân"),
    (1387, "ASL (authorized stockage list (army))", "danh mục lưu kho được phê chuẩn (lục quân)"),
    (1387, "aslt (assault)", "cuộc tiến công; trận xung kích; đổ bộ; trận chiến đấu để đổ quân đổ bộ"),
    (1387, "aslt acft (assault aircraft)", "máy bay tiến công"),
    (1387, "aslt brg (assault bridge)", "cầu tiến công"),
    (1387, "aslt ech (assault echelon)", "thê đội xung phong, thê đội một"),
    (1387, "ASM (armored scout mission)", "đội trinh sát bằng xe bọc thép"),
    (1387, "ASM (automated scheduling message)", "lịch trình lập điện văn tự động hoá"),
    (1387, "ASM (air-to-surface missile)", "tên lửa không đối mặt (đất, biển); tên lửa không đối hạm"),
    (1387, "ASM (Antarctica Service Medal)", 'huy chương "Vì phục vụ ở Antarctica"'),
    (1387, "ASM (anti-ship missile)", "tên lửa chống tàu chiến"),
    (1387, "ASM (Armored Systems Modernisation (US))", "sự hiện đại hoá hệ thống xe bọc thép (Mỹ)"),
    (1387, "ASM radar (airfield surface movement radar)", "rada giám sát sân bay; rada giám sát mọi hoạt động mặt đất của sân bay"),
    (1387, "ASMA (air staff management aid)", "(Anh) phương tiện quản lý nhân lực bộ tham mưu không quân"),

    # ---- page 1388 (idx0623) ----
    (1388, "ASMD (antiship missile defense)", "phòng thủ tên lửa chống tàu chiến"),
    (1388, "ASMI (airfield service movement indication)", "sự chỉ thị mọi hoạt động trên sân bay"),
    (1388, "ASMP (Air-Sol Moyenne Portée (air-to-surface, medium-range missile))", "tên lửa không đối mặt (đất-biển) tầm trung"),
    (1388, "ASN (army serial number)", "số hiệu quân nhân của lực lượng lục quân"),
    (1388, "ASN (atomic strike net)", "mạng thông tin liên lạc tiến công hạt nhân"),
    (1388, "ASO (air support operations)", "tác chiến chi viện đường không"),
    (1388, "ASOC (air support operations center)", "trung tâm tác chiến chi viện đường không"),
    (1388, "ASOFA (assistant secretary of the army)", "trợ lý bộ trưởng bộ lục quân; thứ trưởng bộ lục quân"),
    (1388, "ASofAF (Assistant Secretary of the Air Force)", "trợ lý bộ trưởng bộ không quân; thứ trưởng bộ không quân"),
    (1388, "ASOFDTG (as of date/time group)", "theo số liệu tính đến ngày.../ tháng.../ năm..."),
    (1388, "ASOP (Army Strategic Objectives Plan)", "kế hoạch thực hiện nhiệm vụ chiến lược lục quân, kế hoạch mục tiêu chiến lược lục quân"),
    (1388, "ASP (ammunition supply point)", "trạm cung cấp đạn dược, điểm tiếp tế đạn dược"),
    (1388, "ASP (antisubmarine patrol)", "tuần dương hạm chống tàu ngầm, tàu tuần tiễu chống ngầm; sự tuần tiễu chống ngầm"),
    (1388, "ASP (arms strategic plan)", "kế hoạch chiến lược quân sự"),
    (1388, "ASP (atomic strike plan)", "kế hoạch tiến công hạt nhân; kế hoạch đột kích hạt nhân"),
    (1388, "ASPB (Armed Services Petroleum Board)", "ủy ban nhiên liệu và dầu mỡ quân sự; ủy ban nhiên liệu lực lượng vũ trang"),
    (1388, "ASPB (assault support patrol boat)", "tuần dương hạm chi viện quân đổ bộ"),
    (1388, "ASPJ (advanced self-protection jammer)", "máy gây nhiễu tự vệ cải tiến"),
    (1388, "ASPJ (airborne self-protection jammer)", "máy gây nhiễu tự vệ trên máy bay"),
    (1388, "ASPP (acquisition systems protection program)", "chương trình bảo hộ mua sắm các hệ thống"),
    (1388, "ASPPO (Armed Service Production Planning Office)", "phòng kế hoạch sản xuất của quân chủng"),
    (1388, "ASPR (Armed Services Procurement Act Regulations)", "quy định về trạng thái sẵn sàng chiến đấu của lực lượng vũ trang"),
    (1388, "ASR (acoustic self-ranging system)", "hệ thống tự định tầm (bằng) âm thanh"),
    (1388, "ASR (air-sea rescue)", "hoạt động cứu hộ trên biển của không quân"),
    (1388, "ASR (air surveillance radar)", "trạm rada kiểm soát trên không"),
    (1388, "ASR (airfield surveillance radar)", "rada giám sát sân bay"),
    (1388, "ASR (airport surveillance radar)", "trạm rada kiểm soát sân bay, rada giám sát cảng hàng không"),
    (1388, "ASR (automatic sent-receive)", "sự thu - phát tự động"),
    (1388, "ASRAAM (advanced short range air-to-air missile)", "tên lửa không đối không tầm trung cải tiến"),
    (1388, "ASRAP (acoustic sensor range and prediction)", "sự định tầm và bắn đón bằng bộ cảm biến âm; xenxơ âm thanh (để) định tầm và bắn đón"),
    (1388, "ASROC (antisubmarine rocket)", "tên lửa chống ngầm; tên lửa chống tàu ngầm"),
    (1388, "ASRT (air support radar team)", "phân đội rada bảo đảm không quân"),
    (1388, "ASS (ammunition storage sites)", "vị trí kho đạn dược"),
    (1388, "ASS (aviation support ship)", "tàu bảo đảm hàng không (cho máy bay trên tàu sân bay)"),

    # ---- page 1389 (idx0624) ----
    (1389, "Ass Ord (assignment order)", "quyết định bổ nhiệm"),
    (1389, "assd (assigned)", "được bổ nhiệm; được đưa vào biên chế"),
    (1389, "ASSETREP (transportation assets report)", "báo cáo vật chất và trang thiết bị vận tải"),
    (1389, "asslt (assault)", "cuộc tiến công; trận xung kích; đổ bộ; trận chiến đấu để đổ quân đổ bộ"),
    (1389, "ASSM (anti-ship supersonic missile)", "tên lửa siêu âm đối hạm"),
    (1389, "asst (assignment)", "sự bổ nhiệm; phiên chế; chức trách"),
    (1389, "ASST (assist)", "giúp, giúp đỡ"),
    (1389, "asst (assistant)", "trợ lý; người giúp việc, cấp phó"),
    (1389, "ASSW (anti-surface ship warfare)", "tác chiến chống tàu nổi"),
    (1389, "ASSY; assy (assembly)", "sự tập hợp; sự tập trung quân; sự tập kết; sự lắp ráp; bộ phận lắp ráp; tổ hợp; cơ cấu"),
    (1389, "AST (Air Staff Target (UK))", "ký hiệu tham mưu không quân (Anh)"),
    (1389, "ASTAR (airborne search target attack radar)", "rada tìm diệt mục tiêu (đặt) trên máy bay"),
    (1389, "ASTIA (Armed Services Technical Information Agency)", "cục thông tin kỹ thuật quân sự"),
    (1389, "ASTOR (airborne stand-off radar)", "rada ngoài tầm (hỏa lực phòng thủ) đặt trên máy bay"),
    (1389, "ASTOR (antisubmarine torpedo)", "ngư lôi chống ngầm; ngư lôi chống tàu ngầm"),
    (1389, "ASTROS (artillery saturation rocket system)", "tổ hợp pháo phản lực bắn loạt"),
    (1389, "ASTS (aeromedical staging squadron)", "phi đội chuyển thương đường không"),
    (1389, "ASTT (anti-submarine TT)", "súng phóng ngư lôi chống ngầm"),
    (1389, "ASTU (army specialized training unit)", "đơn vị đào tạo chuyên môn của lục quân; đơn vị huấn luyện chuyên môn của lục quân"),
    (1389, "ASU (area service unit)", "đơn vị phục vụ khu vực"),
    (1389, "ASU-85 (Soviet airborne assault gun)", "pháo tiến công đường không Liên Xô, pháo chống tăng của lực lượng cơ động đường không"),
    (1389, "ASUSSR (Academy of Science of the USSR)", "viện hàn lâm khoa học Liên Xô"),
    (1389, "ASUW (anti-surface-unit warfare)", "tác chiến chống mục tiêu mặt đất (biển)"),
    (1389, "ASV (active service)", "phục vụ tại ngũ, tại ngũ"),
    (1389, "ASV (Air-to-surface vessel)", "tàu trang bị tên lửa không đối mặt (đất, biển)"),
    (1389, "ASV (ammunition supply vehicle)", "phương tiện cung cấp đạn dược, phương tiện tiếp tế đạn dược"),
    (1389, "ASV (anti-surface vessel)", "chống tàu nổi"),
    (1389, "ASV (armored security vehicle)", "(Mỹ) xe bọc thép cảnh giới"),
    (1389, "ASV (Armored Security Vehicle (US))", "xe bọc thép bảo vệ (Mỹ), xe thiết giáp tuần tiễu (Mỹ)"),
    (1389, "ASVEH (air-surveillance vehicle)", "máy bay giám sát trên không"),
    (1389, "ASVW (anti-surface vessel warfare)", "tác chiến chống tàu nổi"),
    (1389, "ASW (anti-submarine warfare)", "tác chiến chống ngầm"),
    (1389, "ASW (antisatellite weapon)", "vũ khí chống vệ tinh, vũ khí tiêu diệt vệ tinh"),
    (1389, "ASW (antisubmarine weapon)", "tên lửa chống ngầm; vũ khí chống tàu ngầm"),
    (1389, "ASW (assistant secretary of war)", "trợ lý bộ trưởng bộ chiến tranh; thứ trưởng bộ chiến tranh"),
    (1389, "ASW/SOW (anti-submarine warfare/stand-off weapon)", "vũ khí chống ngầm (đặt) ngoài tầm (hỏa lực phòng thủ)"),
    (1389, "ASWAF (arms and services on duty with Air Force)", "các đơn vị và các ngành được phối thuộc với không quân; các đơn vị và các ngành được tăng cường cho không quân"),

    # ---- page 1390 (idx0625) ----
    (1390, "ASWBPL (Armed Services Whole Blood Processing Laboratories)", "các phòng thí nghiệm xử lý máu chung của tất cả các quân chủng"),
    (1390, "ASWC (antisubmarine warfare commander)", "tư lệnh (trưởng) tác chiến chống ngầm"),
    (1390, "ASWD (army special weapons depot)", "kho đạn dược chuyên dụng lục quân"),
    (1390, "ASWH (advice soldier write home)", "khuyến khích binh sĩ viết thư về nhà; động viên chiến sĩ viết thư về nhà"),
    (1390, "AT (annual training)", "sự huấn luyện hàng năm"),
    (1390, "AT (anti-tank)", "(thuộc) chống tăng"),
    (1390, "AT (antiterrorism tug)", "tàu chống khủng bố"),
    (1390, "AT defense (antitank defense)", "phòng ngự chống tăng"),
    (1390, "at mfld (antitank minefield)", "bãi mìn chống tăng"),
    (1390, "at obs (antitank obstacle)", "vật cản chống tăng"),
    (1390, "AT plat (antitank platoon)", "trung đội chống tăng"),
    (1390, "AT (Soviet anti-tank guided missile)", "tên lửa chống tăng có điều khiển của Liên Xô"),
    (1390, "AT sqd (antitank squad)", "đội chống tăng"),
    (1390, "At total (attainable search area)", "toàn bộ khu vực có thể trinh sát tìm kiếm được"),
    (1390, "AT wpns (antitank weapons)", "vũ khí chống tăng"),
    (1390, "at.ht. (atomic heat)", "nhiệt (dung) nguyên tử"),
    (1390, "ATA (advanced tactical aircraft)", "máy bay chiến thuật kiểu mới; máy bay chiến thuật cải tiến"),
    (1390, "ATA (Air Transport Association of America)", "hiệp hội vận tải hàng không Mỹ"),
    (1390, "ATA (airport traffic area)", "khu vực kiểm soát không lưu của sân bay"),
    (1390, "ATAAC (anti-torpedo air-launched acoustic countermeasures)", "tổ hợp thiết bị thủy âm chống ngư lôi phóng từ máy bay"),
    (1390, "ATAC (all-terrain all climate)", "mọi địa hình, mọi thời tiết"),
    (1390, "ATAC (all-terrain amphibious carrier)", "xe lội nước chạy trên mọi địa hình"),
    (1390, "ATAC (Allied Tactical Air Command)", "bộ chỉ huy không quân chiến thuật liên quân NATO"),
    (1390, "ATAC (antiterrorism alert center (Navy))", "trung tâm cảnh báo chống khủng bố (hải quân)"),
    (1390, "ATACC (advanced tactical air command center)", "trung tâm chỉ huy không quân chiến thuật tiền phương"),
    (1390, "ATACMS (Army Tactical Missile System)", "hệ thống tên lửa chiến thuật lục quân"),
    (1390, "ATACNS (Army Tactical Command and Control System)", "hệ thống chỉ huy và kiểm soát chiến thuật lục quân"),
    (1390, "ATACO (air tactical actions control officer)", "sĩ quan chỉ huy tác chiến chiến thuật (của) không quân, sĩ quan chỉ huy không quân tiến công quân địch (trên) mặt đất"),
    (1390, "ATACS (Advanced Tank Cannon System (US))", "tổ hợp pháo trên xe tăng cải tiến (Mỹ)"),
    (1390, "ATACS (Army Tactical Communications System)", "hệ thống thông tin liên lạc chiến thuật của lục quân"),
    (1390, "ATAF (Allied Tactical Air Force)", "lực lượng không quân chiến thuật liên quân NATO"),
    (1390, "ATAFCS (airborne target acquisition and fire control system)", "tổ hợp bắt bám và điều khiển hỏa lực (đặt) trên máy bay, máy bay bắt bám mục tiêu và điều khiển hỏa lực"),
    (1390, "ATAR (air-to-air recognition device)", "thiết bị nhận biết mục tiêu trên không"),
    (1390, "ATAR; atar (antitank aircraft rocket)", "tên lửa không quân chống tăng, tên lửa chống tăng trên máy bay"),
    (1390, "ATAS (automatic target acquisition system)", "hệ thống tự động bắt bám mục tiêu"),

    # ---- page 1391 (idx0626) ----
    (1391, "ATB (advanced technology bomber)", "(Mỹ) máy bay ném bom công nghệ tiên tiến"),
    (1391, "ATBM (anti-tactical ballistic missile)", "tên lửa chống tên lửa đạn đạo chiến thuật"),
    (1391, "ATC (acoustic torpedo countermeasures)", "tổ hợp thiết bị thủy âm chống ngư lôi"),
    (1391, "ATC (air target chart)", "sơ đồ mục tiêu của không quân"),
    (1391, "ATC (Air Threat Conference)", "hội nghị về các mối đe doạ trên không"),
    (1391, "ATC (air traffic control)", "sự kiểm soát không lưu"),
    (1391, "ATC (Air Training Command)", "bộ chỉ huy đào tạo không quân, bộ tư lệnh huấn luyện không quân"),
    (1391, "ATC (air transportable clinic (USAF))", "phòng khám cơ động bằng đường không (của không quân Mỹ)"),
    (1391, "ATCA (advanced tanker cargo aircraft)", "máy bay vận tải cải tiến"),
    (1391, "ATCA (Allied Tactical Communications Agency)", "cục thông tin liên lạc chiến thuật liên quân"),
    (1391, "ATCAA (air traffic control assigned airspace)", "khoảng không được xác định kiểm soát không lưu"),
    (1391, "ATCALS (air traffic control and landing system)", "hệ thống kiểm soát không lưu và hạ cánh"),
    (1391, "ATCAS (Advanced Towed Cannon System)", "tổ hợp pháo xe kéo cải tiến"),
    (1391, "ATCC (air traffic control center)", "trung tâm kiểm soát không lưu"),
    (1391, "atch (attach)", "tăng cường, phối thuộc; bổ sung quân; điều thêm quân; tạm thời đưa vào biên chế"),
    (1391, "atch and det (attachments and detachments)", "các đơn vị phối thuộc tăng cường và biệt phái"),
    (1391, "atchd (attached)", "được phối thuộc"),
    (1391, "ATCRBS (Air Traffic Control Radar Beacon System)", "hệ thống rada dẫn hướng kiểm soát không lưu"),
    (1391, "ATCS (air traffic control section)", "phân đội kiểm soát không lưu; bộ phận kiểm soát không lưu"),
    (1391, "ATD (Advanced Technology Demonstration)", "cuộc thao diễn công nghệ tiên tiến; cuộc trình diễn công nghệ tiên tiến"),
    (1391, "ATD (Advanced Technology Demonstrator (US))", "người thao tác công nghệ tiên tiến, người trình diễn công nghệ tiên tiến"),
    (1391, "ATD (Automatic Target Detection)", "sự phát hiện mục tiêu tự động; tự động phát hiện mục tiêu"),
    (1391, "ATDL (army tactical data link)", "đường truyền dữ liệu chiến thuật (của) lục quân"),
    (1391, "ATDL1 (army tactical data link 1)", "đường truyền dữ liệu chiến thuật 1 của lục quân"),
    (1391, "ATDLS (Advanced Tactical Data Link System)", "hệ thống liên kết dữ liệu chiến thuật cải tiến"),
    (1391, "ATDM (adaptive time division multiplexer)", "máy phát tín hiệu nén có phân phối thời gian thích ứng"),
    (1391, "ATDS (airborne tactical data system)", "(Mỹ) hệ thống xử lý dữ liệu chiến thuật (đặt) trên máy bay"),
    (1391, "ATDT (automatic target detection and tracking)", "sự phát hiện và bám sát mục tiêu tự động; tự động bắt bám mục tiêu"),
    (1391, "ATE (automatic test equipment)", "thiết bị tự động đo kiểm (vũ khí trang bị)"),
    (1391, "ATF (advanced technology fighter)", "máy bay tiêm kích công nghệ tiên tiến"),
    (1391, "ATF (air transport force)", "lực lượng vận tải đường không, không quân vận tải"),
    (1391, "ATF (amphibious task force)", "cụm chiến dịch đổ bộ đường biển; lực lượng đặc nhiệm đổ bộ đường biển"),
    (1391, "atg (air-to-ground)", "không đối đất"),
    (1391, "ATG (anti-tank gun)", "súng chống tăng, pháo chống tăng"),
    (1391, "ATG (aviation turbine gasoline)", "nhiên liệu dùng cho tuabin máy bay"),

    # ---- page 1392 (idx0627) ----
    (1392, "atgar (anti-tank guided air rocket)", "tên lửa hàng không chống tăng có điều khiển"),
    (1392, "ATGL (anti-tank grenade launcher)", "súng phóng lựu chống tăng"),
    (1392, "ATGM (antitank guided missile)", "tên lửa chống tăng có điều khiển"),
    (1392, "ATGW (anti-tank guided weapon)", "vũ khí chống tăng có điều khiển"),
    (1392, "ATH (air transportable hospital)", "quân y viện cơ động đường không"),
    (1392, "ATHS (Airborne Target Handover System)", "hệ thống bàn giao mục tiêu đường không"),
    (1392, "ATI (air target indication)", "sự chỉ thị mục tiêu trên không; sự chỉ thị mục tiêu cho không quân, sự chỉ thị mục tiêu tiến công đường không"),
    (1392, "ATK; Atk (anti-tank)", "chống tăng"),
    (1392, "ATK; atk (attack)", "sự tiến công; sự công kích; cuộc đột kích"),
    (1392, "ATK (attacking)", "đang tiến công (chỉ dùng trên sơ đồ)"),
    (1392, "atk ech (attack(ing) echelon)", "thê đội tiến công, thê đội một"),
    (1392, "atk pos (attack position)", "khu vực xuất phát tiến công, vị trí xuất phát tiến công"),
    (1392, "Atl Fleet (Atlantic Fleet)", "hạm đội Đại Tây Dương"),
    (1392, "ATLAS (Advanced Technology Light Artillery System)", "tổ hợp pháo binh hạng nhẹ công nghệ tiên tiến"),
    (1392, "ATIS (anti-tank influence sensor)", "xenxơ chống tăng dựa trên tác động trường vật lí"),
    (1392, "ATLV (artillery target location vehicle)", "xe định vị mục tiêu (cho) pháo binh"),
    (1392, "ATM (air target material)", "phần tử mục tiêu cho không quân; (giao) nhiệm vụ mục tiêu cho không quân; phần tử mục tiêu trên không"),
    (1392, "ATM (anti-tactical missile)", "tên lửa chống tên lửa chiến thuật"),
    (1392, "ATM (asynchronous transfer mode)", "phương thức chuyển phát không đồng bộ"),
    (1392, "ATM (anti-tank mine)", "mìn chống tăng"),
    (1392, "ATM (antitank missile)", "tên lửa chống tăng"),
    (1392, "ATM (Army Training Memorandum)", "chỉ thị về huấn luyện chiến đấu của lục quân"),
    (1392, "ATMCT (air terminal movement control team)", "đội kiểm soát cơ động đường không sân bay cuối"),
    (1392, "ATMDS (anti-tank mine-dispensing system)", "hệ thống rải mìn chống tăng"),
    (1392, "ATMP (Air Target Materials Program)", "chương trình các phần tử mục tiêu cho không quân; chương trình các phần tử mục tiêu trên không"),
    (1392, "ATMP (all-terrain mobile platform)", "(xe) giàn phóng cơ động trên mọi địa hình"),
    (1392, "ATN (assign thresholds)", "ấn định ngưỡng cất hạ cánh"),
    (1392, "ATO (air tasking order)", "hạ (đạt) mệnh lệnh cho không quân"),
    (1392, "ATOC (air tactical operations center)", "trung tâm chỉ huy tác chiến chiến thuật không quân"),
    (1392, "ATOC (air terminal operations center)", "trung tâm điều hành trạm vận tải đường không đầu cuối; trung tâm chỉ huy sân bay bảo đảm trang bị kỹ thuật"),
    (1392, "ATP (airliner transport pilot)", "phi công (lái) máy bay vận tải"),
    (1392, "ATP (allied tactical publication)", "xuất bản phẩm về chiến thuật của liên quân NATO"),
    (1392, "ATP (antitank platoon)", "trung đội chống tăng"),
    (1392, "ATP (army training program)", "chương trình huấn luyện lục quân"),
    (1392, "ATPOS (atomic post-strike analysis report)", "báo cáo phân tích số liệu trinh sát sau tiến công hạt nhân"),
    (1392, "ATR (attrition reserve)", "nguồn dự bị bổ sung tiêu hao"),
    (1392, "ATR (Automotive Test Rig)", "thiết bị thí nghiệm tự hành"),
    (1392, "ATR-EDS (Automotive Test Rig-Electric Drive System)", "hệ thống thiết bị thử nghiệm tự hành - dẫn động bằng điện"),

    # ---- page 1393 (idx0628) ----
    (1393, "ATS (acoustic tracking system)", "hệ thống bám mục tiêu (phát ra) âm thanh"),
    (1393, "ats (air-to-ship)", "không đối tàu, không đối hạm"),
    (1393, "ATS (air transport support)", "bảo đảm vận tải đường không"),
    (1393, "ATSD(AE) (Assistant to the Secretary of Defense (Atomic Energy))", "trợ lý bộ trưởng bộ quốc phòng (về năng lượng nguyên tử); thứ trưởng bộ quốc phòng (về năng lượng nguyên tử)"),
    (1393, "ATSD(IO) (Assistant to the Secretary of Defense (Intelligence Oversight))", "trợ lý bộ trưởng bộ quốc phòng (về giám sát tình báo); thứ trưởng bộ quốc phòng (về giám sát tình báo)"),
    (1393, "ATT (assign terminal type)", "xác định kiểu trạm đầu cuối"),
    (1393, "att (attach)", "tăng cường, phối thuộc; bổ sung quân, điều thêm quân; tạm thời đưa vào biên chế"),
    (1393, "ATTC (All Terrain Tracked Carrier)", "xe tải bánh xích chạy trên mọi địa hình, xe tải bánh xích có sức cơ động cao"),
    (1393, "attn (attention)", "sự chú ý; chú ý"),
    (1393, "ATTS (air transportable towed system)", "tổ hợp pháo binh xe kéo vận chuyển (được bằng) đường không"),
    (1393, "ATTU (air transportable treatment unit)", "đơn vị điều trị quân y cơ động đường không"),
    (1393, "ATTU (Atlantic to the Urals)", "khu vực từ Đại Tây Dương đến Uran"),
    (1393, "ATTV (all-terrain tow vehicle)", "xe kéo pháo việt dã, xe kéo pháo cơ động mọi địa hình"),
    (1393, "ATV (all terrain vehicle)", "xe việt dã, xe chạy trên mọi địa hình, phương tiện có sức cơ động cao"),
    (1393, "ATV (Armoured TOW Vehicle (Turkey))", "xe bọc thép trang bị đạn phản lực phóng bằng ống, theo dõi bằng khí cụ quang học và được điều khiển bằng dây (thu tín hiệu từ xa)"),
    (1393, "AU (Air University)", "trường đại học hàng không"),
    (1393, "AUEL (automated unit equipment list)", "danh mục tự động thống kê thiết bị đơn vị"),
    (1393, "Aug (august)", "tháng tám"),
    (1393, "AUIC (active duty unit identification code)", "mã nhận biết đơn vị quân thường trực"),
    (1393, "AUM; aum (air-to-underwater missile)", "tên lửa không đối ngầm"),
    (1393, "AURA (autonomous un-manned reconnaissance aircraft)", "máy bay trinh sát không người lái tự điều khiển"),
    (1393, "AUS (Army of the United States)", "lục quân Mỹ"),
    (1393, "AUSA (Association of the United States Army)", "hiệp hội lục quân Mỹ"),
    (1393, "AUT (advanced unit training)", "(phương pháp) huấn luyện phân đội trong thành phần đơn vị"),
    (1393, "auth (authorized)", "được phép"),
    (1393, "AUTMV (automotive)", "ô tô; (thuộc) tự hành"),
    (1393, "AUTO; auto (automatic)", "súng tự động; (thuộc) tự động"),
    (1393, "AUTODIN (Automatic Digital Network)", "mạng tự động kỹ thuật số"),
    (1393, "AUTOSEVOCOM (Automatic Secure Voice Communications Network)", "mạng bảo đảm an ninh thông tin liên lạc thoại tự động, mạng tự động bảo đảm bí mật hoạt động thông tin liên lạc thoại"),
    (1393, "AUTOVON (Automatic Voice Network)", "mạng đàm thoại tự động"),
    (1393, "AUV (autonomous undersea vehicle)", "tàu ngầm tự hoạt"),
    (1393, "AUW (all-up weight)", "tổng trọng tải bay tức thời (trong điều kiện xác định hoặc tại thời điểm đặc biệt khi đang bay)"),
    (1393, "Aux; aux (auxiliary)", "bổ trợ, phụ; (thuộc) phụ trợ, (thuộc) bổ trợ"),
    (1393, "AV (air vehicle)", "phương tiện bay"),
    (1393, "AV (anti-vehicle)", "chống xe, chống chiến xa"),
    (1393, "av (aviation)", "hàng không"),

    # ---- page 1394 (idx0629) ----
    (1394, "Av. (average)", "mức trung bình, số trung bình"),
    (1394, "AV/VI (audiovisual/visual information)", "thông tin nghe nhìn/nhìn"),
    (1394, "AVAL; aval (available)", "sẵn có để dùng, sẵn sàng để dùng; có thể dùng được, có thể có được; có hiệu lực, có giá trị"),
    (1394, "AVC (Army Veterinary Corps)", "ngành thú y quân sự"),
    (1394, "AVER (available for reassignment)", "sẵn có để sử dụng lại"),
    (1394, "AVGAS; AvGas (aviation gasoline)", "nhiên liệu máy bay, xăng máy bay"),
    (1394, "AVGP (Armoured Vehicle General Purpose (Canada))", "xe bọc thép đa năng (Canada)"),
    (1394, "AVH (Armoured Vehicle Heavy)", "xe bọc thép hạng nặng"),
    (1394, "Avionics (Aviation Electronics)", "các thiết bị điện tử hàng không, điện tử hàng không"),
    (1394, "AVL (Armoured Vehicle Light)", "xe bọc thép hạng nhẹ"),
    (1394, "AVLB (armored vehicle launched bridge)", "xe bọc thép bắc cầu"),
    (1394, "avlb (available)", "hiện có, có sẵn (trong tay)"),
    (1394, "AVLB sec (armored vehicle launched bridge section)", "bộ phận xe bọc thép bắc cầu; phân đội xe bọc thép bắc cầu"),
    (1394, "AVLM (antivehicle land mine)", "mìn chống phương tiện đổ bộ"),
    (1394, "AVM (guided-missile ship)", "ký hiệu tàu mang tên lửa có điều khiển"),
    (1394, "AVM (Armoured Vehicle Medium)", "xe bọc thép hạng trung"),
    (1394, "avn (aviation)", "hàng không; không quân"),
    (1394, "avn bn (aviation battalion)", "tiểu đoàn không quân (của lục quân hoặc hải quân)"),
    (1394, "avn co (lt trans) (aviation company, light transport)", "đại đội không quân vận tải hạng nhẹ (của lục quân hoặc hải quân)"),
    (1394, "avn gp (aviation group)", "cụm không quân (của lục quân hoặc hải quân)"),
    (1394, "avn sec (aviation section)", "bộ phận không quân (của lục quân hoặc hải quân)"),
    (1394, "AVOU (analog voice orderwire unit)", "bộ mạch vòng liên lạc thoại theo thuật tương tự"),
    (1394, "AVOW (analog voice orderwire)", "mạch vòng liên lạc thoại theo thuật tương tự"),
    (1394, "AVR (armoured vehicle reconnaissance)", "xe bọc thép trinh sát; sự trinh sát bằng xe bọc thép"),
    (1394, "AVRE (Armoured Vehicle, Royal Engineers (UK))", "xe bọc thép của binh chủng công binh (Anh)"),
    (1394, "AVRE (Assault Vehicle, Royal Engineers (UK))", "phương tiện đổ bộ của binh chủng công binh (Anh)"),
    (1394, "AVS (audiovisual squadron)", "tiểu đoàn thông tin liên lạc nghe nhìn"),
    (1394, "AVS plane (advanced vertical and short take-off and landing plane)", "máy bay cải tiến cất hạ cánh thẳng đứng trên đường băng ngắn"),
    (1394, "AVUM (aviation unit maintenance)", "sự bảo dưỡng của đơn vị không quân (của lục quân hoặc hải quân)"),
    (1394, "AW (acoustic warfare)", "chiến tranh âm thanh (ngầm dưới nước)"),
    (1394, "AW (air warfare)", "tác chiến đường không"),
    (1394, "AW (all-weather)", "mọi thời tiết"),
    (1394, "AW (amphibious warfare ship)", "tàu chiến đổ quân đổ bộ đường biển; tàu đổ bộ mẹ"),
    (1394, "AW (army-wide)", "trong toàn quân"),
    (1394, "AW (Articles of War)", "bộ luật quân sự (của lục quân)"),
    (1394, "AW (atomic warfare)", "tác chiến nguyên tử"),
    (1394, "AW (atomic weapon)", "vũ khí nguyên tử"),
    (1394, "AW (automatic weapons)", "vũ khí tự động"),
    (1394, "AW Bn, SP (automatic weapon battalion, self-propelled)", "tiểu đoàn vũ khí tự động - tự hành"),
    (1394, "AWACS (Airborne Warning and Control System)", "hệ thống kiểm soát và báo động đường không đặt trên máy bay; máy bay cảnh báo và kiểm soát"),

    # ---- page 1395 (idx0630) ----
    (1395, "AWADS (adverse weather aerial delivery system)", "hệ thống phóng vũ khí từ máy bay trong điều kiện thời tiết xấu"),
    (1395, "AWAF (Army with Air Force)", "lực lượng lục quân tăng cường cho không quân"),
    (1395, "AWAS (Australian Women's Army Service)", "ngành phụ nữ trợ giúp quân đội Ôxtrâylia"),
    (1395, "AWC (Air War College)", "trường không quân"),
    (1395, "AWC (air warfare commander)", "tư lệnh (trưởng) tác chiến đường không"),
    (1395, "AWC (Army War College)", "trường lục quân"),
    (1395, "AWCAP (airborne weapons corrective action program)", "chương trình hiệu chỉnh vũ khí đường không; chương trình hiệu chỉnh vũ khí lắp trên máy bay"),
    (1395, "AWCCM (acoustic warfare counter-countermeasures)", "các biện pháp chống phản tác chiến âm thanh; các phương tiện đối phó với thủ đoạn phản tác chiến âm thanh"),
    (1395, "AWCLS (all-weather carrier landing system)", "hệ thống hỗ trợ hạ cánh mọi thời tiết trên tàu sân bay"),
    (1395, "AWCM (acoustic warfare countermeasures)", "các biện pháp phản tác chiến âm thanh; các phương tiện đối phó với tác chiến âm thanh (của địch)"),
    (1395, "AWCS (Air Weapons Control System)", "hệ thống điều khiển vũ khí trên máy bay"),
    (1395, "AWDATS (automatic weapon data transmission system)", "tổ hợp tự động truyền phần tử bắn (của) vũ khí"),
    (1395, "AWG (air weapons group)", "nhóm vũ khí không quân"),
    (1395, "AWLS (All-Weather Landing System)", "hệ thống hỗ trợ hạ cánh trong mọi thời tiết"),
    (1395, "AWN (Automated Weather Network)", "mạng nghiên cứu thời tiết tự động, mạng tự động theo dõi thời tiết"),
    (1395, "AWOL (absent without leave)", "vắng mặt không có lý do; đào ngũ"),
    (1395, "AWS (Air Weather Service)", "ngành khí tượng không quân"),
    (1395, "AWS (automatic warning system)", "hệ thống cảnh báo tự động, tổ hợp tự động báo động"),
    (1395, "AWSAS (all-weather stand-off attack system)", "tổ hợp vũ khí tiến công ngoài tầm hỏa lực phòng thủ mọi thời tiết"),
    (1395, "AWSCOM (Atomic Weapons Support Command)", "bộ chỉ huy bảo đảm vũ khí hạt nhân, bộ tư lệnh bảo đảm vũ khí hạt nhân"),
    (1395, "AWSE (armament weapons support equipment)", "thiết bị hỗ trợ nạp đạn của vũ khí"),
    (1395, "AWSIM (air warfare simulation model)", "mô hình mô phỏng tác chiến trên không"),
    (1395, "AWSVC (air warning service)", "cục báo động phòng không"),
    (1395, "AWTSS (all-weather tactical strike system)", "tổ hợp vũ khí tiến công chiến thuật mọi thời tiết"),
    (1395, "AWX (all-weather interceptor)", "máy bay đánh chặn mọi thời tiết; tên lửa đánh chặn mọi thời tiết; tên lửa phòng không mọi thời tiết"),
    (1395, "AxiSigComm (axis of signal communication)", "trục thông tin liên lạc"),
    (1395, "AXP (air exchange point)", "địa điểm chuyển máy bay"),
    (1395, "AXP (ambulance exchange point)", "địa điểm chuyển xe cứu thương"),
    (1395, "AXSIGCOMM (axis or axes of signal communication)", "trục thông tin liên lạc (một hay nhiều chiều)"),
    (1395, "az (azimuth)", "phương vị, góc phương vị"),
    (1395, "AZR (assign zone restriction lists)", "ấn định danh mục khu vực cấm; bảng ấn định danh mục khu vực cấm"),

    # ---- page 1396 (idx0631) ----
    (1396, "B (ballistic)", "(k.hiệu) đường đạn, đạn đạo"),
    (1396, "B (base)", "(k.hiệu) căn cứ"),
    (1396, "B; btry (battery (pieces to fire))", "đại đội pháo binh; (Mỹ) khẩu đội pháo"),
    (1396, "B (battle)", "(k.hiệu) trận đánh, cuộc chiến đấu; (thuộc) chiến đấu"),
    (1396, "B (bomb)", "(k.hiệu) bom"),
    (1396, "B (bomber)", "(k.hiệu) máy bay ném bom; máy bay cường kích"),
    (1396, "B (cross-over barrier pattern)", "hình mẫu vượt vật cản"),
    (1396, "B and QA (barracks and quarters, army)", "nhà ở và doanh trại quân đội"),
    (1396, "B&A (boat and aircraft)", "tàu thuyền và máy bay"),
    (1396, "B&C (biological/bacteriological & chemical weapons)", "vũ khí sinh học, vi trùng và hóa học"),
    (1396, "B&GS (bombing & gunnery school)", "trường huấn luyện ném bom và bắn pháo"),
    (1396, "B.A.U. (British Engineering Standard Association Unit)", "đơn vị (đo) của hội tiêu chuẩn kỹ thuật Anh"),
    (1396, "B/B (baseband)", "dải tần cơ bản"),
    (1396, "B/C (battle casualties)", "tổn thất chiến đấu, thiệt hại trong chiến đấu; tiêu hao trong trận đánh"),
    (1396, "B/L (bill of lading)", "vận đơn, phiếu vận chuyển"),
    (1396, "B/U (backup)", "(thuộc) lực lượng dự bị"),
    (1396, "B-1B (supersonic strategic bomber)", "máy bay ném bom chiến lược siêu âm B-1B"),
    (1396, 'B-2 ("stealth" bomber)', "máy bay ném bom tàng hình B-2"),
    (1396, "B2F (Boeing 720 fan jet airplane)", "(k.hiệu) máy bay phản lực cánh quạt Bôinh 720"),
    (1396, "B3F (Boeing 320 fan jet airplane)", "(k.hiệu) máy bay phản lực cánh quạt Bôinh 320"),
    (1396, "B-47 (Stratojet all-weather strategic medium bomber)", '(k.hiệu) máy bay ném bom chiến lược mọi thời tiết, tầm trung, mang tên "Stratojet"'),
    (1396, "B-52 (stratofortress)", '(k.hiệu) máy bay ném bom chiến lược B-52 mang tên "pháo đài bay"'),
    (1396, "B-52 (Stratofortress all-weather intercontinental strategic heavy bomber)", '(k.hiệu) máy bay ném bom chiến lược hạng nặng mọi thời tiết, tầm xa, mang tên "Pháo đài bay"'),
    (1396, "B-57 (Canberra two-place twin-engine turbojet all-weather tactical bomber)", '(k.hiệu) máy bay ném bom chiến thuật mọi thời tiết, động cơ tuabin phản lực kép, hai chỗ ngồi, mang tên "Canberra" đơn vị của Hội liên hiệp tiêu chuẩn kỹ thuật Anh'),
    (1396, "B-58 (Hustler strategic all-weather supersonic bomber)", '(k.hiệu) máy bay ném bom chiến lược siêu âm, mọi thời tiết, mang tên "Người khẩn trương"'),
    (1396, "B-66 (Destroyer twin-engine turbojet tactical all-weather light-bombardment aircraft)", '(k.hiệu) máy bay ném bom chiến thuật hạng nhẹ mọi thời tiết, động cơ tuabin phản lực kép, mang tên "kẻ huỷ diệt"'),

    # ---- page 1397 (idx0632) ----
    (1397, "B7F (Boeing 707 fan jet airplane)", "(k.hiệu) máy bay phản lực cánh quạt Bôinh 707"),
    (1397, "BA (base area)", "khu vực căn cứ"),
    (1397, "ba (branch)", "binh chủng; ngành"),
    (1397, "BA (British Army)", "quân đội vương quốc Anh, lục quân Anh"),
    (1397, "BA (Budget Authority)", "cơ quan ngân sách"),
    (1397, "Bac (basic)", "cơ bản"),
    (1397, "bact (bacteriological)", "(thuộc) vi trùng, (thuộc) vi khuẩn"),
    (1397, "BAD (base air depot)", "kho không quân vùng tiếp giáp mặt trận, kho căn cứ không quân"),
    (1397, "BADGE (Base Air Defense Ground Environment)", "trang bị kỹ thuật mặt đất của hệ thống phòng không căn cứ"),
    (1397, "BAF (backup alert force)", "lực lượng cảnh giới dự bị"),
    (1397, "Bag (baggage)", "hành lý"),
    (1397, "BAH (basic allowance for housing)", "phụ cấp cơ bản về nhà ở"),
    (1397, "BAI (backup aircraft inventory)", "kho dự trữ máy bay"),
    (1397, "BAI (battlefield air interdiction)", "sự ngăn chặn (hoạt động) không quân địch trên chiến trường"),
    (1397, "BALM1 (ballistic missile)", "tên lửa đạn đạo, tên lửa đường đạn"),
    (1397, "BALOG (base logistical command)", "bộ tư lệnh hậu cần cơ bản; bộ chỉ huy hậu cần căn cứ"),
    (1397, "BALTAP (Baltic Approaches Command)", "bộ tư lệnh vùng Bantích của liên quân NATO"),
    (1397, "BAOR (British Army on the Rhine)", "quân đội Anh ở Rin"),
    (1397, "BAP (bombes anti-personnel)", "(Pháp) bom chống bộ binh, bom sát thương sinh lực"),
    (1397, "BAPREPT (beds and patients report)", "báo cáo (của quân y viện) về số giường bệnh và thương bệnh binh"),
    (1397, "bar (barrage)", "hoả lực ngăn chặn; vật chướng ngại; (kq) sự tuần tiễu (trên không)"),
    (1397, "Bar; bbl (Baren)", "baren (đơn vị đo lường dầu lửa bằng 159 lít)"),
    (1397, "Bar Bln (barrage balloon)", "khí cầu chướng ngại hàng không, vật cản bằng khí cầu trên không"),
    (1397, "BAR (Browning automatic rifle)", "súng trung liên Braoning"),
    (1397, "BARC (beach amphibious resupply cargo)", "hàng tiếp tế đổ bộ đường biển cập bờ"),
    (1397, "BARV (beach armored recovery vehicle)", "xe bọc thép cứu kéo và sửa chữa đổ bộ đường biển"),
    (1397, "BAS (basic allowance for subsistence)", "phụ cấp cơ bản về nhu yếu phẩm"),
    (1397, "BAS (battalion aid station)", "trạm cứu thương tiểu đoàn"),
    (1397, "BAS (battlefield automated systems)", "tổ hợp vũ khí tự động chiến thuật"),
    (1397, "BASEDAM (base damage report)", "báo cáo tổn thất của đơn vị; báo cáo thiệt hại cơ bản"),
    (1397, "BASO (brigade air support officer)", "sĩ quan bảo đảm không quân (không trợ) lữ đoàn"),
    (1397, "BAT (basic aviation trainer)", "máy bay huấn luyện không quân cơ bản"),
    (1397, "bat (battalion)", "tiểu đoàn"),
    (1397, "BAT (battalion antitank)", "chống tăng cấp tiểu đoàn"),
    (1397, "bat (battery)", "đại đội pháo binh; (Mỹ) khẩu đội pháo"),
    (1397, "BAT; bat (battle)", "trận đánh, cuộc chiến đấu"),
    (1397, "BAT (battleship)", "chiến hạm, chủ lực hạm, thiết giáp hạm"),
    (1397, "bat intel (battle intelligence)", "tình báo chiến trường; trinh sát chiến trường"),
    (1397, "bat pos (battle position)", "vị trí chiến đấu; trận địa chiến đấu"),
    (1397, "batrecon (battle reconnaissance)", "sự trinh sát chiến đấu; trinh sát trong quá trình chiến đấu"),
]


def main():
    out_path = "docs/db/import/tudien_abbr_chunks/chunk_0618_0632.csv"
    fieldnames = [
        "source_page", "dictionary_name", "word", "phonetic",
        "part_of_speech_raw", "part_of_speech_code", "meaning_vi",
        "is_subentry", "example_en", "example_vi", "image_path", "reviewed",
    ]
    with open(out_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for page, word, meaning in ENTRIES:
            writer.writerow({
                "source_page": page,
                "dictionary_name": DICTIONARY_NAME,
                "word": word,
                "phonetic": "",
                "part_of_speech_raw": "",
                "part_of_speech_code": "",
                "meaning_vi": meaning,
                "is_subentry": "FALSE",
                "example_en": "",
                "example_vi": "",
                "image_path": f"img_{page}.jpg",
                "reviewed": "FALSE",
            })
    print(f"Wrote {len(ENTRIES)} entries to {out_path}")


if __name__ == "__main__":
    main()
