# -*- coding: utf-8 -*-
"""
Build chunk_0738_0752.csv from manually transcribed (by-eye) entries of
Tu_dien.pdf pages idx0738-idx0752 (printed pages 1503-1517).
"""
import csv

# Each tuple: (printed_page, word, meaning_vi)
entries = [
    # ---------------- idx0738 / page 1503 ----------------
    (1503, "GVW (Gross Vehicle Weight)", "tải trọng của xe"),
    (1503, "GW; gw (guerilla warfare)", "chiến tranh du kích; hoạt động đổ bộ biệt kích"),
    (1503, "GW (guided weapon)", "tên lửa có điều khiển; vũ khí phản lực có điều khiển"),
    (1503, "GWC (Global Weather Center)", "trung tâm thời tiết toàn cầu"),
    (1503, "GWEN (ground wave emergency network)", "(Mỹ) mạng sóng đất (dùng trong tình trạng) khẩn cấp (liên lạc với tàu ngầm chiến lược)"),
    (1503, "GWS (guided weapon station)", "(Anh) trạm tên lửa có điều khiển; căn cứ tên lửa có điều khiển"),
    (1503, "GWS (guided weapon system)", "tổ hợp vũ khí có điều khiển"),
    (1503, "GZ (ground zero)", "tâm nổ hạt nhân trên mặt đất, chiếu tâm nổ hạt nhân trên mặt đất"),

    # ---------------- idx0739 / page 1504 ----------------
    (1504, "H (hard)", "phòng chống hạt nhân; được thiết bị phòng chống hạt nhân"),
    (1504, "H (headquarters)", "bộ tư lệnh; bộ chỉ huy; sở chỉ huy, hành dinh, bản doanh"),
    (1504, "H (heavy)", "(thuộc) hạng nặng"),
    (1504, "H (height)", "độ cao"),
    (1504, "H (helicopter)", "máy bay trực thăng, máy bay lên thẳng"),
    (1504, "H (hill)", "điểm cao; quả đồi"),
    (1504, "H (homing)", "tự dẫn"),
    (1504, "H (hospital)", "viện quân y"),
    (1504, "H (hour)", "giờ"),
    (1504, "H (howitzer)", "lựu pháo"),
    (1504, "H (hydrazine)", "hiđrozin H2N.NH2; RHN, NH2"),
    (1504, "H (hydrobomb)", "(k.hiệu) bom khinh khí, bom H"),
    (1504, "H (hydrogen)", "hydro"),
    (1504, "H (mustard gas)", "(k.hiệu) hơi cay"),
    (1504, "H and S (headquarters and service)", "sở chỉ huy và phân đội bảo đảm (chỉ huy)"),
    (1504, "H Bty RA (heavy battery, Royal Artillery)", "đại đội pháo binh hạng nặng"),
    (1504, "H&D (hardened and dispersed)", "phòng chống và phân giải tác động của vụ nổ hạt nhân"),
    (1504, "H&I (harassing and interdicting)", "(hoả lực) quấy rối và cấm chỉ"),
    (1504, "H&S (headquarters and service)", "sở chỉ huy và phân đội bảo đảm (chỉ huy)"),
    (1504, "H&S Co (headquarters and service company)", "sở chỉ huy và đại đội phục vụ (chỉ huy)"),
    (1504, "H.T (high tension)", "cao áp"),
    (1504, "HA (heavy artillery)", "pháo binh hạng nặng, trọng pháo"),
    (1504, "HA (holding area)", "khu vực chiếm giữ để chặn địch, khu vực chốt"),
    (1504, "HA (hostile aircraft)", "máy bay địch"),
    (1504, "HA (hour angle)", "góc giờ, thời giác"),
    (1504, "haa (heavy antiaircraft artillery)", "pháo phòng không hạng nặng"),
    (1504, "HAA (height above airport)", "độ cao so với sân bay"),
    (1504, "HAARS (high-altitude airdrop resupply system)", "hệ thống tiếp tế thả dù ở độ cao lớn"),
    (1504, "haaw (heavy anti-tank assault weapon)", "vũ khí chống tăng hạng nặng"),
    (1504, "HAB (Heavy Assault Bridge)", "(US) cầu vượt sông hạng nặng"),
    (1504, "HAB (high altitude burst)", "vụ nổ (hạt nhân) ở độ cao lớn"),
    (1504, "HAC (helicopter aircraft commander)", "chỉ huy trưởng lực lượng máy bay trực thăng"),
    (1504, "HACC (humanitarian assistance coordination center)", "trung tâm hiệp đồng hỗ trợ nhân đạo"),
    (1504, "HACV (heavy armament combat vehicle)", "xe chiến đấu mang vũ khí hạng nặng"),

    # ---------------- idx0740 / page 1505 ----------------
    (1505, "HADM (heavy atomic demolition munition)", "đạn nổ hạt nhân có công suất lớn"),
    (1505, "HAFCE (Headquarters, Allied Forces, Central Europe)", "bộ tư lệnh lực lượng liên quân NATO ở khu vực Trung Âu"),
    (1505, "HAFMED (Headquarters, Allied Forces, Mediterranean)", "sở chỉ huy lực lượng liên quân NATO ở khu vực Địa Trung Hải"),
    (1505, "HAFNE (Headquarters, Allied Forces, Northern Europe)", "sở chỉ huy lực lượng liên quân NATO ở khu vực Bắc Âu"),
    (1505, "HAFSE (Headquarters, Allied Forces, Southern Europe)", "sở chỉ huy lực lượng liên quân NATO ở khu vực Nam Âu"),
    (1505, "HAG (heavy artillery group)", "cụm pháo binh hạng nặng"),
    (1505, "HAHO (high-altitude high-opening parachute technique)", "phương pháp nhảy và mở dù ở độ cao lớn (trên tầm hỏa lực pháo phòng không)"),
    (1505, "HALO (high-altitude low-opening parachute technique)", "phương pháp nhảy dù từ độ cao lớn (trên tầm hỏa lực pháo phòng không) và mở dù ở độ cao thấp"),
    (1505, "HAM (heavy automotive maintenance)", "sửa chữa lớn xe tăng bọc thép (cấp 4, 5), đại tu tăng thiết giáp"),
    (1505, "HAMD (helicopter ambulance medical detachment)", "đội máy bay trực thăng cứu thương"),
    (1505, "HAR (harbor)", "hải cảng; quân cảng"),
    (1505, "HARM (high-speed antiradiation missile)", "tên lửa cao tốc chống bức xạ"),
    (1505, "HARP (high altitude release point)", "điểm ném bom ở độ cao lớn; điểm phóng tên lửa ở độ cao lớn"),
    (1505, "HAS (helicopter armament subsystem)", "phân hệ máy bay trực thăng vũ trang"),
    (1505, "HAST (humanitarian assistance survey team)", "đội khảo sát hỗ trợ nhân đạo"),
    (1505, "HAT (height above touch-down)", "độ cao so với tầm đáp xuống"),
    (1505, "HAT (high-altitude target)", "mục tiêu (ở) độ cao lớn"),
    (1505, "HATR (hazardous air traffic report)", "sự báo cáo nguy hiểm giao thông đường không; báo cáo nguy hiểm không lưu"),
    (1505, "HAW (heavy anti-tank weapon)", "vũ khí chống tăng hạng nặng"),
    (1505, "HAZ (hazardous cargo)", "hàng hoá nguy hiểm (phóng xạ, cháy, nổ...)"),
    (1505, "HAZMAT (hazardous materials)", "vật chất nguy hiểm"),
    (1505, "HB (heavy barrel)", "nòng pháo dày; nòng súng dày"),
    (1505, "HB (heavy boat)", "tàu thuyền hạng nặng"),
    (1505, "HB (hostile battery)", "đại đội pháo binh địch"),
    (1505, "HBAR (heavy barrel assault rifle)", "súng trường xung kích nòng dày"),
    (1505, "HBC (human body counter)", "máy đo độ nhiễm phóng xạ ở người"),
    (1505, "H-bomb (hydrogen bomb)", "bom khinh khí, bom H"),
    (1505, "HC (high capacity)", "uy lực mạnh, uy lực lớn"),
    (1505, "HC (high command)", "bộ chỉ huy tối cao, bộ tư lệnh tối cao"),
    (1505, "HC (hollow charge)", "lượng nổ lõm"),
    (1505, "HC (Home Command)", "(Anh) quân khu mẫu quốc; bộ tư lệnh không quân mẫu quốc; bộ tư lệnh không quân lục địa"),
    (1505, "HC (Humanitarian Coordinator)", "sĩ quan phối hợp hoạt động nhân đạo"),
    (1505, "HCA (humanitarian and civic assistance)", "sự hỗ trợ nhân đạo và dân sự"),
    (1505, "HCAS (hostile casualty)", "thương vong của quân địch"),
    (1505, "HCER (high-capacity extended range)", "(đạn) bắn tầm xa có uy lực mạnh, (đạn pháo) tăng tầm uy lực lớn"),
    (1505, "HCHE (high-capacity high explosive)", "(đạn) nổ phá có uy lực mạnh; (đạn) nổ lõm uy lực mạnh"),
    (1505, "HCO (helicopter control officer)", "sĩ quan điều khiển máy bay trực thăng"),
    (1505, "HCP (hardcopy printer)", "máy in trên giấy"),
    (1505, "HCPTR (helicopter)", "máy bay trực thăng, máy bay lên thẳng"),

    # ---------------- idx0741 / page 1506 ----------------
    (1506, "HCS (helicopter combat support)", "(Navy) sự chi viện chiến đấu bằng máy bay trực thăng (hải quân)"),
    (1506, "HCS (helicopter control station)", "trạm dẫn đường máy bay trực thăng"),
    (1506, "HCS (helicopter coordination section)", "bộ phận hiệp đồng (tác chiến) với máy bay trực thăng"),
    (1506, "HCSA (House Committee of Science and Astronautics)", "ủy ban khoa học và vũ trụ của hạ nghị viện"),
    (1506, "HCT (heavy crawler tractor)", "xe kéo (pháo) bánh xích hạng nặng"),
    (1506, "HD (harbor defense)", "phòng vệ hải cảng, phòng thủ quân cảng"),
    (1506, "HD (high definition)", "độ rõ nét, độ phân giải cao"),
    (1506, "HDB (high density bombing)", "sự ném bom mật độ cao"),
    (1506, "HDC (harbor defense commander)", "chỉ huy trưởng (khu vực) phòng thủ cảng"),
    (1506, "HDC (helicopter direction center)", "trung tâm chỉ huy máy bay trực thăng"),
    (1506, "HDD (head-down display)", "(màn) hiển thị dưới tầm mắt (trên máy bay, hạm tàu)"),
    (1506, "Hdg (heading)", "hướng; hướng chuyển động"),
    (1506, "HDNCW (high density nuclear chock wave)", "sóng xung kích hạt nhân có mật độ cao"),
    (1506, "HDRV (heavy duty recovery vehicle)", "xe cứu kéo phương tiện nặng"),
    (1506, "HDY (heavy duty)", "hiệu suất cao, công suất lớn; dùng cho chế độ làm việc nặng nhọc"),
    (1506, "HE (heavy equipment)", "thiết bị nặng; (cb) xe công trình hạng nặng"),
    (1506, "HE (high explosive)", "thuốc nổ mạnh; lượng nổ lõm; công phá mạnh"),
    (1506, "HE bomb (high explosive bomb)", "bom nổ phá mạnh"),
    (1506, "HE/PR (high-explosive practice)", "đạn nổ dùng bắn tập"),
    (1506, "HEAA; Heaa (high-explosive anti-aircraft (shell))", "đạn phòng không công phá mạnh"),
    (1506, "HEAP (high explosive armor-piercing)", "(đạn) xuyên thép liều nổ lõm, (đạn) nổ lõm xuyên giáp"),
    (1506, "HE-APERS (high-explosive anti-personnel)", "(đạn) sát thương bộ binh liều nổ mạnh, đạn nổ phá mạnh sát thương bộ binh"),
    (1506, "HEAP-T (high-explosive anti-personnel-tracer)", "đạn vạch đường sát thương bộ binh liều nổ mạnh"),
    (1506, "heat (heating)", "đốt nóng"),
    (1506, "HEAT (helicopter external air transport)", "máy bay trực thăng vận chuyển treo (ngoài), vận chuyển đường không bằng máy bay trực thăng treo (ngoài)"),
    (1506, "HEAT (high explosive antitank)", "(đạn) nổ lõm chống tăng"),
    (1506, "heat (high-explosive anti-tank (projectile))", "đạn chống tăng liều nổ lõm, đạn nổ lõm chống tăng"),
    (1506, "HEAT rkt (high explosive antitank rocket)", "rốckét chống tăng (sử dụng) liều nổ lõm"),
    (1506, "HEAT-FS (high-explosive anti-tank fin-stabilised)", "(đạn) nổ lõm chống tăng ổn định bằng cánh đuôi, (đạn) nổ lõm chống tăng có cánh đuôi ổn định"),
    (1506, "HEAT-MP (high-explosive anti-tank multipurpose)", "(đạn) nổ lõm chống tăng đa năng"),
    (1506, "HEAT-MP(P) (high-explosive anti-tank multipurpose (practice))", "(đạn) nổ lõm chống tăng đa năng (dùng cho) huấn luyện"),
    (1506, "HEAT-T (high-explosive anti-tank-tracer)", "(đạn) nổ lõm chống tăng vạch đường"),
    (1506, "HEAT-T-HVY (high-explosive anti-tank-tracer-heavy)", "(đạn) nổ lõm chống tăng vạch đường cỡ lớn"),
    (1506, "HEAT-T-MP (high-explosive anti-tank-tracer-multipurpose)", "(đạn) nổ lõm chống tăng vạch đường đa năng"),
    (1506, "HEAT-TP-T (high-explosive anti-tank-target practice-tracer)", "(đạn) nổ lõm vạch đường chống tăng dùng cho huấn luyện"),

    # ---------------- idx0742 / page 1507 ----------------
    (1507, "HEC (helicopter element coordinator)", "sĩ quan hiệp đồng với phân đội máy bay trực thăng"),
    (1507, "HEDCOM (Headquarters Command)", "sở chỉ huy binh đoàn không quân"),
    (1507, "HEDP (high-explosive dual-purpose)", "(đạn) nổ phá mạnh công dụng kép"),
    (1507, "HEDUSAFE (Headquarters, United States Air Force in Europe)", "sở chỉ huy không quân Mỹ ở châu Âu"),
    (1507, "HEER (High-Explosive Extended Range)", "(US) (đạn) tăng tầm nổ phá mạnh (Mỹ), (đạn) nổ phá mạnh tầm mở rộng (Mỹ)"),
    (1507, "HEF (high-explosive fragmentation)", "sự nổ phá văng mảnh (đạn)"),
    (1507, "HEFOE (hydraulic, electrical, fuel, oxygen engine)", "động cơ thuỷ lực, điện, nhiên liệu và ôxy"),
    (1507, "HE-FRAG (high-explosive fragmentation)", "(đạn) nổ phá mảnh"),
    (1507, "HE-FRAG-FS (high-explosive fragmentation-fin-stabilised)", "(đạn) nổ phá mảnh được ổn định bằng cánh đuôi, (đạn) nổ phá mảnh có cánh đuôi ổn định"),
    (1507, "HE-FS (high-explosive-fin-stabilised)", "(đạn) nổ lõm được ổn định bằng cánh đuôi, (đạn) nổ lõm có cánh đuôi ổn định"),
    (1507, "HEFT (high-explosive follow through)", "(đạn) nổ lõm xuyên tiếp"),
    (1507, "HEI (high-explosive incendiary)", "(đạn) nổ chiếu sáng"),
    (1507, "HEIT (high-explosive incendiary tracer)", "đạn nổ chiếu sáng vạch đường"),
    (1507, "HEL (high energy laser)", "lade năng lượng cao"),
    (1507, "HEL (Human Engineering Laboratory)", "(US) phòng thí nghiệm kỹ thuật sử dụng yếu tố quân nhân"),
    (1507, "hel (helicopter)", "máy bay trực thăng, máy bay lên thẳng"),
    (1507, "HEL-H (heavy helicopter)", "máy bay trực thăng hạng nặng"),
    (1507, "HEL-L (light helicopter)", "máy bay trực thăng hạng nhẹ"),
    (1507, "HEL-M (medium helicopter)", "máy bay trực thăng hạng trung"),
    (1507, "HELO (helicopter)", "máy bay trực thăng, máy bay lên thẳng"),
    (1507, "helo (heliport)", "sân bay trực thăng"),
    (1507, "HELP (Helicopter Electronic Landing Path)", "đường hạ cánh có thiết bị điện tử dùng cho máy bay lên thẳng"),
    (1507, "HELP (Howitzer Extended Life Program)", "(US) chương trình nghiên cứu kéo dài tuổi thọ của lựu pháo (Mỹ)"),
    (1507, "helps (helicopter protection & support)", "bảo vệ và chi viện bằng máy bay trực thăng"),
    (1507, "HelRon (helicopter squadron)", "phi đội máy bay trực thăng, phi đội máy bay lên thẳng"),
    (1507, "HEMAT (Heavy Expanded Mobility Ammunition Trailer)", "(US) xe moóc hạng nặng chở đạn cơ động đường dài"),
    (1507, "HEMP (high-altitude electromagnetic pulse)", "xung điện từ ở độ cao lớn"),
    (1507, "HEMP (high-explosive multi-purpose)", "(đạn) nổ phá đa dụng"),
    (1507, "HEMTT (Heavy Expanded Mobility Tactical Truck)", "(US) xe vận tải chiến thuật hạng nặng cơ động đường dài"),
    (1507, "HEO (highly elliptical orbit)", "quỹ đạo êlíp cao"),
    (1507, "HEP; hep (high-explosive plastic)", "chất nổ dẻo có uy lực mạnh"),
    (1507, "HEPD (high-explosive point detonating)", "(đạn) nổ phá kích nổ điểm"),
    (1507, "hept (helicopter)", "máy bay trực thăng, máy bay lên thẳng"),
    (1507, "HEP-T (high explosive plastic tracer)", "đạn nổ vạch đường liều nổ dẻo có uy lực mạnh"),
    (1507, "HEP-T (high-explosive practice-tracer)", "đạn nổ vạch đường bắn tập"),
    (1507, "heptr (helicopter)", "máy bay trực thăng, máy bay lên thẳng"),
    (1507, "HERA (high-explosive rocket-assisted)", "(đạn) nổ phá tăng tầm bằng phản lực"),
    (1507, "HERC (Nike Hercules)", "tên lửa Hécquyn"),

    # ---------------- idx0743 / page 1508 ----------------
    (1508, "HERF (hazards of electromagnetic radiation to fuel)", "các mối nguy hiểm của bức xạ điện từ đối với nhiên liệu"),
    (1508, "HERO (electromagnetic radiation hazards)", "các mối nguy hiểm của bức xạ điện từ"),
    (1508, "HERO (hazards of electromagnetic radiation to ordnance)", "các mối nguy hiểm của bức xạ điện từ đối với vũ khí đạn dược"),
    (1508, "HERP (hazards of electromagnetic radiation to personnel)", "các mối nguy hiểm của bức xạ điện từ đối với quân nhân"),
    (1508, "HE-S (high-explosive spotting)", "hiệu chỉnh bắn bằng đạn nổ"),
    (1508, "HE-S (high explosive with spotting charge)", "chất nổ mạnh có chỉnh liều thay đổi"),
    (1508, "HESD (high explosive, self-destroying)", "(đạn) nổ phá tự hủy"),
    (1508, "HESH (high explosive, squash head (antitank projectile))", "liều nổ lõm đầu mềm (đạn chống tăng)"),
    (1508, "HESH-T (high - explosive squash head-tracer)", "đạn nổ lõm vạch đường đầu mềm"),
    (1508, "HET (heavy equipment transporter)", "xe chuyên chở trang bị nặng"),
    (1508, "HE-T (high - explosive tracer)", "đạn nổ vạch đường"),
    (1508, "HE-T SD (high - explosive tracer - self-destruct)", "đạn nổ vạch đường ngòi tự huỷ"),
    (1508, "HET-PF (high - explosive tracer - percussion fuze)", "đạn nổ vạch đường ngòi chạm nổ"),
    (1508, "HETS (heavy equipment transporter semitrailer)", "xe nửa moóc chuyên chở trang bị nặng"),
    (1508, "HETSD (high explosive with tracer, self-destroying)", "đạn nổ vạch đường ngòi tự huỷ"),
    (1508, "HF (harassing fire)", "hoả lực quấy rối"),
    (1508, "HF (high frequency)", "cao tần; tần số cao"),
    (1508, "HF; H/F (human factors)", "các yếu tố con người, các yếu tố tổ chức và huấn luyện lực lượng"),
    (1508, "HFCC (Howitzer Fire-Control Computer)", "(US) máy tính điều khiển hoả lực lựu pháo (Mỹ)"),
    (1508, "HFDF (high frequency direction-finding)", "sự tìm phương bằng cao tần"),
    (1508, "HFM (Heavy Force Modernisation)", "(US) sự hiện đại hoá lực lượng (Mỹ)"),
    (1508, "HG (Home Guard)", "(Anh) lực lượng phòng thủ địa phương"),
    (1508, "HGV (heavy goods vehicle)", "xe chở hàng hạng nặng"),
    (1508, "HH (homing pattern)", "sơ đồ dẫn (tên lửa)"),
    (1508, "HHB (headquarters and headquarters battery)", "sở chỉ huy và đại đội chỉ huy pháo binh"),
    (1508, "HHC (headquarters and headquarters company)", "sở chỉ huy và đại đội chỉ huy"),
    (1508, "HHCL (\"H\" hour coordinating line)", "tuyến hiệp đồng cho giờ \"H\""),
    (1508, "HHD (headquarters and headquarters detachment)", "sở chỉ huy và phân đội chỉ huy"),
    (1508, "HHLR (hand-held laser rangefinder)", "máy định tầm bằng lade xách tay, thiết bị lade định tầm xách tay"),
    (1508, "H-hour (seaborne assault landing hour)", "giờ bắt đầu đổ quân đổ bộ đường biển"),
    (1508, "H-hour (specific time an operation or exercise begins)", "giờ mở màn chiến dịch hoặc cuộc tập trận"),
    (1508, "H-hr (H-hour)", "giờ G (bắt đầu đổ bộ)"),
    (1508, "HHT (headquarters and headquarters troop)", "sở chỉ huy và nhóm chỉ huy"),
    (1508, "HICAP (high-capacity firefighting foam station)", "trạm bọt cứu hoả công suất cao"),
    (1508, "HICAPCOM (high capacity communications system)", "hệ thống thông tin liên lạc hiệu suất cao"),
    (1508, "HIDACZ (high-density airspace control zone)", "khu vực kiểm soát không gian vũ trụ mật độ cao"),
    (1508, "HIDS (headquarters information distribution system)", "hệ thống điều phối thông tin sở chỉ huy"),
    (1508, "HIFR (helicopter in-flight refueling)", "máy bay trực thăng tiếp dầu trên không; sự tiếp dầu trên không của máy bay trực thăng"),

    # ---------------- idx0744 / page 1509 ----------------
    (1509, "HIMAD (high-to-medium-altitude air defence)", "phòng không ở độ cao lớn và trung bình"),
    (1509, "HIMARS (High-Mobility Artillery Rocket System)", "(US) tổ hợp pháo phản lực cơ động nhanh"),
    (1509, "HIMEZ (high-altitude missile engagement zone)", "khu vực đánh chặn của tên lửa ở độ cao lớn"),
    (1509, "HIP (Howitzer Improvement Program)", "(US) chương trình cải tiến lựu pháo (Mỹ)"),
    (1509, "HIPAR (high power acquisition radar)", "rađa bắt bám mục tiêu công suất cao, rađa phát hiện và bám sát mục tiêu công suất cao"),
    (1509, "HIRSS (hover infrared suppressor subsystem)", "phân hệ chế áp bằng hồng ngoại trên máy bay"),
    (1509, "HIT (homing intercept technology)", "công nghệ đánh chặn tự dẫn"),
    (1509, "HITP (high ignition temperature propellant)", "thuốc phóng bền nhiệt"),
    (1509, "HIU (heading indicator unit)", "bộ chỉ thị hướng đi (máy bay, hạm tàu)"),
    (1509, "HJ (crypto key change)", "thay đổi khoá mật mã"),
    (1509, "HJ (Honest John)", "tên lửa Ônít Giôn"),
    (1509, "HJ lchr (Honest John launcher)", "bệ phóng tên lửa Ônít Giôn"),
    (1509, "HJ/DELTA 5KT (Honest John/Delta 5KT)", "tên lửa Ônít Giôn có đầu đạn hạt nhân Đenta công suất 5 kilôtôn"),
    (1509, "HL (horizontal line)", "đường chân trời"),
    (1509, "HLH (heavy lift helicopter)", "máy bay trực thăng vận tải hạng nặng"),
    (1509, "HLLV (heavy lift launch vehicle)", "xe giàn phóng các thiết bị nặng vào không gian"),
    (1509, "HLPS (heavy-lift pre-position ship)", "tàu sức tải lớn triển khai trước"),
    (1509, "HLWE (helicopter laser warning equipment)", "thiết bị cảnh báo lade (trên) máy bay trực thăng"),
    (1509, "HLZ (helicopter landing zone)", "khu vực đổ bộ của máy bay trực thăng; khu vực hạ cánh của máy bay lên thẳng"),
    (1509, "HM Co (heavy maintenance company)", "đại đội sửa chữa và bảo dưỡng lớn, đại đội đại tu, đại đội sửa chữa lớn"),
    (1509, "HMC (howitzer motor carriage)", "bệ lựu pháo tự hành"),
    (1509, "HMCN (Her Majesty's Canadian Navy)", "hạm đội hải quân Canada"),
    (1509, "HMCS (Her Majesty's Canadian ship)", "tàu hải quân Canada"),
    (1509, "HMD (helicopter mine dispenser)", "thiết bị rải thủy lôi (từ) máy bay trực thăng"),
    (1509, "HMD (Helmet-mounted display)", "màn hiển thị lắp trên mũ phi công; màn hiển thị lắp trên mũ sắt"),
    (1509, "HMG (heavy machine gun)", "súng máy hạng nặng; súng đại liên; trọng liên; thượng liên"),
    (1509, "HMH (Marine heavy helicopter squadron)", "phi đội máy bay trực thăng hạng nặng của thủy quân lục chiến"),
    (1509, "HMLA (Marine light/attack helicopter squadron)", "phi đội máy bay trực thăng tiến công hạng nhẹ của thủy quân lục chiến"),
    (1509, "HMLC (High-Mobility Load Carrier)", "xe vận tải đạn cơ động nhanh, xe tiếp đạn cơ động cao"),
    (1509, "HMM (Marine medium helicopter squadron)", "phi đội máy bay trực thăng hạng trung của thủy quân lục chiến"),
    (1509, "HMMHE (high mobility matériel handling equipment)", "phương tiện bốc dỡ vũ khí trang bị cơ động cao"),
    (1509, "HMMWV (High-Mobility Multi Purpose Wheeled Vehicle)", "xe bánh hơi đa năng cơ động cao"),
    (1509, "HMRT (heavy material recovery team)", "đội cứu kéo trang bị nặng"),
    (1509, "HMS (Her Majesty's ship)", "tàu hải quân vương quốc Anh"),
    (1509, "HMTT (high mobility tactical truck)", "xe vận tải chiến thuật cơ động cao"),
    (1509, "HMW (health, morale, and welfare)", "thuộc về sức khỏe, tinh thần và phúc lợi"),

    # ---------------- idx0745 / page 1510 ----------------
    (1510, "HN (host nation)", "nước chủ nhà"),
    (1510, "HNS (host-nation support)", "sự hỗ trợ của nước chủ nhà"),
    (1510, "HO (hydrographic office)", "cơ quan thuỷ văn"),
    (1510, "HOB (height of burst)", "độ cao của vụ nổ hạt nhân"),
    (1510, "HOC (human intelligence operations cell)", "tổ hoạt động tình báo về con người"),
    (1510, "HOCC (Humanitarian Operations Coordination Center)", "(US) trung tâm hiệp đồng hoạt động nhân đạo (Mỹ)"),
    (1510, "HOD (head of delegation)", "trưởng đoàn đại biểu"),
    (1510, "HOGE (hover out of ground effect)", "(hq) chao đảo do hiệu ứng của mặt đất"),
    (1510, "HOIS (hostile intelligence service)", "ngành tình báo của địch"),
    (1510, "HOM (head of mission)", "trưởng phái đoàn"),
    (1510, "horiz stblz (horizontal stabilizer)", "thiết bị giữ ổn định thăng bằng ngang"),
    (1510, "hosp (hospital)", "viện quân y"),
    (1510, "Hosp Tr (hospital train)", "đoàn xe quân y"),
    (1510, "HOSTAC (helicopter operations from ships other than aircraft carriers (USN publication))", "các hoạt động (tác chiến) của máy bay trực thăng từ các tàu không phải là tàu sân bay (tài liệu của hải quân Mỹ)"),
    (1510, "HOTASA (hands on throttle and stick aid)", "thiết bị điều khiển (đặt) trên cần lái và tay ga, thiết bị HOTAS"),
    (1510, "HOTOL (horizontal take-off & landing)", "cất hạ cánh (ở thể) bay bằng, cất hạ cánh (ở thể) nằm ngang (phương tiện vũ trụ)"),
    (1510, "HOTPHOTOREP (hot photo interpretation report)", "sự báo cáo kết quả phân tích ảnh sơ bộ; giải đoán ảnh nóng"),
    (1510, "how sec (howitzer section)", "phân đội lựu pháo; (Mỹ) khẩu đội lựu pháo; bộ phận hoả lực của đại đội lựu pháo"),
    (1510, "how bn, SP (howitzer battalion, self-propelled)", "tiểu đoàn lựu pháo tự hành"),
    (1510, "How; how (howitzer)", "lựu pháo; pháo nòng ngắn, đại bác ngắn nòng"),
    (1510, "HP (high power)", "công suất cao; uy lực lớn"),
    (1510, "HP (high pressure)", "cao áp"),
    (1510, "HP; hp (horsepower)", "mã lực"),
    (1510, "Hp (hospital)", "viện quân y"),
    (1510, "HPA (high power amplifier)", "máy khuếch đại công suất cao"),
    (1510, "HPD (hard point defense)", "căn cứ phòng thủ tên lửa được thiết bị phòng chống hạt nhân"),
    (1510, "HPFP (High-Performance Fragmentation Projectile)", "đạn văng mảnh có hiệu quả (sát thương) cao"),
    (1510, "HPI (high position indicator)", "khí cụ chỉ độ cao, đồng hồ chỉ độ cao (của máy bay)"),
    (1510, "HPMSK (high priority mission support kit)", "bộ dụng cụ hỗ trợ nhiệm vụ được ưu tiên cao"),
    (1510, "HPS (Helmet Pointing System (or Sight))", "hệ thống chỉ thị (hoặc ngắm bắn) lắp trên mũ sắt"),
    (1510, "HPT (high-payoff target)", "mục tiêu có giá trị cao, mục tiêu quan trọng"),
    (1510, "hpt (high point)", "điểm cao"),
    (1510, "HQ (HAVE QUICK)", "tốc độ cao; hoàn thành nhanh"),
    (1510, "HQ (headquarters)", "sở chỉ huy; trụ sở bộ tư lệnh; bộ chỉ huy; ban chỉ huy; bộ tham mưu"),
    (1510, "Hq Abn Gr (headquarters, airborne group)", "sở chỉ huy liên đoàn nhảy dù"),
    (1510, "hq and hq co (headquarters and headquarters company)", "sở chỉ huy và đại đội chỉ huy, sở chỉ huy và đại đội tham mưu"),
    (1510, "HQ and Serv Co (headquarters and service company)", "sở chỉ huy và đại đội phục vụ"),
    (1510, "hq and svc btry (headquarters and service battery)", "đại đội tham mưu và bảo đảm pháo binh"),
    (1510, "hq btry (headquarters battery)", "đại đội tham mưu pháo binh"),
    (1510, "HQ co (headquarters company)", "đại đội tham mưu"),

    # ---------------- idx0746 / page 1511 ----------------
    (1511, "HQ COMD USAF (Headquarters Command, USAF)", "bộ chỉ huy không quân (Mỹ)"),
    (1511, "HQ COMDT; Hq Comdt (headquarters commandant)", "tư lệnh (trưởng) sở chỉ huy"),
    (1511, "HQ det (headquarters detachment)", "đội tham mưu"),
    (1511, "hq sec (headquarters section)", "phân đội chỉ huy; bộ phận tham mưu"),
    (1511, "hq tk sec (headquarters tank section)", "phân đội xe tăng chỉ huy"),
    (1511, "HQC; HQCo (headquarters company)", "đại đội chỉ huy; đại đội tham mưu - chỉ huy"),
    (1511, "HQDA (Headquarters, Department of the Army)", "(Mỹ) tổng hành dinh bộ lục quân"),
    (1511, "HQFM-net (HAVE QUICK frequency modulation net)", "mạng điều biến tần số truyền tin tốc độ cao"),
    (1511, "HQFMT-net (HAVE QUICK frequency modulation training net)", "mạng điều biến tần số truyền thông tin tốc độ cao dùng trong huấn luyện"),
    (1511, "HQMC (Headquarters, Marine Corps)", "bộ tư lệnh binh chủng thủy quân lục chiến"),
    (1511, "HQMSS (headquarters mission support system)", "hệ thống bảo đảm tác chiến (của) sở chỉ huy"),
    (1511, "HQRA (headquarters, Royal Artillery)", "(Anh) bộ chỉ huy pháo binh; bộ tham mưu pháo binh; sở chỉ huy pháo binh"),
    (1511, "Hqs (headquarters)", "sở chỉ huy, hành dinh, bản doanh"),
    (1511, "HQU (headquarters unit)", "phân đội tham mưu"),
    (1511, "HRD (human resource development)", "sự xây dựng và huấn luyện lực lượng"),
    (1511, "HRI (high range indicator)", "khí cụ chỉ báo độ cao và tầm xa"),
    (1511, "HRJTF (humanitarian relief joint task force)", "lực lượng đặc nhiệm liên quân trong hoạt động cứu trợ nhân đạo"),
    (1511, "HRN (helicopter radio net)", "mạng vô tuyến điện của máy bay trực thăng"),
    (1511, "HRP (highway regulation point)", "trạm điều chỉnh giao thông đường bộ"),
    (1511, "HRP (holding and reconsignment point)", "điểm lựa chọn và chuyển tải"),
    (1511, "HRS (horizon reference system)", "hệ thống quy chiếu đường chân trời"),
    (1511, "HRT (hostage rescue team)", "toán giải cứu con tin; đội giải cứu con tin"),
    (1511, "HRU (heading reference unit)", "khối quy chiếu hướng đi (máy bay, hạm tàu)"),
    (1511, "HS (helicopter antisubmarine warfare squadron)", "(Navy) phi đội máy bay trực thăng tác chiến chống tàu ngầm (hải quân)"),
    (1511, "HS (Home Service)", "(UK) bộ nội vụ (Anh)"),
    (1511, "HS (homing single-unit)", "thiết bị tự dẫn đơn"),
    (1511, "HSB (high speed boat)", "thuyền cao tốc"),
    (1511, "HSCDM (high speed cable driver modem)", "môđem điều khiển đường truyền tốc độ cao"),
    (1511, "HSD (human intelligence support detachment)", "đội bảo đảm tình báo khai thác và sử dụng con người"),
    (1511, "HSDB (high-speed databus)", "đường truyền dữ liệu tốc độ cao"),
    (1511, "HSE (headquarters support element)", "phân đội bảo đảm sở chỉ huy"),
    (1511, "HSE (human intelligence support element)", "phân đội bảo đảm tình báo khai thác và sử dụng con người"),
    (1511, "HSEP (hospital surgical expansion package)", "(USAF) bộ dụng cụ phẫu thuật mở rộng của bệnh viện (không quân Mỹ)"),
    (1511, "HSI (horizontal situation indicator)", "đồng hồ chỉ thị trạng thái nằm ngang"),
    (1511, "HSI (hyperspectral imagery)", "hình ảnh siêu quang phổ"),
    (1511, "HSLS (health service logistic support)", "sự bảo đảm hậu cần phục vụ sức khỏe quân nhân"),
    (1511, "HSPR (high speed pulse restorer)", "thiết bị hồi phục xung tốc độ cao"),
    (1511, "HSS (health service support)", "bảo đảm phục vụ sức khỏe quân nhân"),
    (1511, "HST (helicopter support team)", "toán chi viện (cho) máy bay trực thăng; phân đội bảo đảm (cho) máy bay lên thẳng"),

    # ---------------- idx0747 / page 1512 ----------------
    (1512, "HT (hatch team)", "đội xếp dỡ hàng trên tàu biển"),
    (1512, "ht (height)", "độ cao"),
    (1512, "HT (high treason)", "sự phản bội tổ quốc"),
    (1512, "HT (hospital train)", "đoàn xe quân y"),
    (1512, "HTA acft (heavier-than-air aircraft)", "thiết bị bay nặng hơn không khí"),
    (1512, "HTERRCAS (hostile terrorist casualty)", "thương vong do khủng bố thù địch"),
    (1512, "HTG (hard target graphic)", "sơ đồ mục tiêu kiên cố"),
    (1512, "HTH (high test hypochlorite)", "chất thử mạnh hipoclorit"),
    (1512, "HTNS (helicopter tactical navigation system)", "hệ thống dẫn đường chiến thuật cho máy bay trực thăng"),
    (1512, "HTOL (horizontal-take-off-and-landing)", "cất hạ cánh nằm ngang"),
    (1512, "HTOVL (horizontal take-off, vertical landing)", "sự cất cánh (ở thể) nằm ngang (và) hạ cánh (ở thể) thẳng đứng"),
    (1512, "HTRK (half-track)", "(thuộc) bán xích, (thuộc) nửa xích"),
    (1512, "HTRP (highway traffic regulation post)", "trạm điều hành giao thông đường bộ"),
    (1512, "HTT (heavy tactical transport)", "vận tải chiến thuật hạng nặng"),
    (1512, "HTT (heavy tracked tractor)", "xe kéo bánh xích hạng nặng"),
    (1512, "HTTB (High-Technology TestBed)", "(US) giàn thử nghiệm công nghệ cao (Mỹ)"),
    (1512, "HU (hospital unit)", "đơn vị quân y; trạm quân y"),
    (1512, "HUD (head-up display)", "(màn) hiển thị lắp trên tầm mắt"),
    (1512, "HUDWAC (head-up display and weapon aiming computer)", "màn hình hiển thị lắp trên tầm mắt (phi công) và máy tính lấy đường ngắm"),
    (1512, "HUK (hunter killer)", "vũ khí tìm diệt; phương tiện tìm diệt quân địch; tàu tìm diệt tàu địch"),
    (1512, "HUMINT (human intelligence)", "tình báo khai thác và sử dụng con người"),
    (1512, "HUMINT (human resources intelligence)", "tình báo khai thác và sử dụng nguồn lực lượng"),
    (1512, "HUMRO (humanitarian relief operation)", "hoạt động cứu trợ nhân đạo"),
    (1512, "HUMRRO (Human Resources Research Office)", "cơ quan nghiên cứu nguồn lực (quân nhân)"),
    (1512, "HUNTER (head-up navigation and targeting equipment for retrofit)", ""),
    (1512, "HUS (hardened unique storage)", "kho trang bị kỹ thuật được thiết bị kiên cố"),
    (1512, "Hv (heavy)", "hạng nặng"),
    (1512, "HV (high velocity)", "có vận tốc lớn, có tốc độ lớn"),
    (1512, "hv bmr (heavy bomber)", "máy bay ném bom hạng nặng"),
    (1512, "hv mort plat (heavy mortar platoon)", "trung đội súng cối hạng nặng"),
    (1512, "HV Tk (heavy tank)", "xe tăng hạng nặng"),
    (1512, "Hv W (heavy weapons)", "vũ khí hạng nặng"),
    (1512, "Hv W Co; Hv Wpns Co (heavy weapons company)", "đại đội pháo hạng nặng"),
    (1512, "HVAA (high value airborne asset)", "phân đội biệt kích đổ bộ đường không có giá trị đặc biệt"),
    (1512, "HVAP (hight-velocity armour-piercing)", "(đạn) xuyên giáp dưới cỡ, (đạn) cao tốc xuyên thép"),
    (1512, "HVAP (hypervelocity armor-piercing)", "(đạn) xuyên thép dưới cỡ siêu tốc, (đạn) siêu tốc xuyên giáp"),
    (1512, "HVAPDS (high-velocity, armor-piercing, discarding sabot)", "(đạn) tách vỏ xuyên thép cao tốc; (thuộc) cao tốc xuyên giáp dưới cỡ có đáy rời"),
    (1512, "HVAPDSFS (hypervelocity armor-piercing discarding sabot fin-stabilized)", "(đạn) tách vỏ xuyên thép cao tốc có cánh đuôi ổn định; (thuộc) cao tốc xuyên giáp dưới cỡ có đáy rời được ổn định bằng cánh đuôi"),
    (1512, "HVAPDS-T (hight-velocity armour-piercing discarding sabot-tracer)", "đạn cao tốc tách vỏ xuyên thép vạch đường; đạn xuyên giáp dưới cỡ vạch đường có đáy rời cao tốc"),

    # ---------------- idx0748 / page 1513 ----------------
    (1513, "HVAPFSDS (high-velocity armour-piercing fin-stabilised discarding sabot)", "(đạn) cao tốc tách vỏ xuyên thép được ổn định bằng cánh đuôi"),
    (1513, "HVAP-T (high-velocity armor-piercing tracer)", "(đạn) cao tốc xuyên thép vạch đường"),
    (1513, "HVAP-T (hypervelocity armor-piercing with tracer)", "đạn siêu tốc xuyên thép vạch đường"),
    (1513, "HVAR (high-velocity aircraft rocket)", "tên lửa hàng không có tốc độ bay lớn; tên lửa cao tốc (lắp) trên máy bay"),
    (1513, "HvArty (heavy artillery)", "pháo hạng nặng, pháo cỡ lớn"),
    (1513, "HVAT (high-velocity antitank)", "(đạn) chống tăng có sơ tốc lớn; (thuộc) chống tăng cao tốc"),
    (1513, "HVAT (hypervelocity antitank)", "(đạn) chống tăng siêu tốc"),
    (1513, "HVM (Hypervelocity Missile)", "tên lửa siêu tốc"),
    (1513, "HVSW (Hypervelocity Support Weapon)", "vũ khí chi viện hoả lực siêu tốc"),
    (1513, "HVT (high-value target)", "mục tiêu có giá trị cao, mục tiêu trọng yếu"),
    (1513, "Hvtk (heavy-gun tank)", "xe tăng hạng nặng, xe tăng trang bị pháo hạng nặng"),
    (1513, "HVTP-T (high-velocity target practice-tracer)", "đạn vạch đường tập bắn mục tiêu tốc độ cao"),
    (1513, "Hvy (heavy)", "nặng; (thuộc) hạng nặng"),
    (1513, "Hvy Wpn Co (heavy weapons company)", "đại đội vũ khí nặng"),
    (1513, "HW (heavy weapons)", "vũ khí hạng nặng, vũ khí nặng"),
    (1513, "HWLS (hostile weapons locating system)", "hệ thống định vị vũ khí địch"),
    (1513, "HWM (high water mark)", "đánh dấu mức (ngấn) nước cao"),
    (1513, "HWT (heavy-weight torpedo)", "ngư lôi hạng nặng"),
    (1513, "Hwy (highway)", "quốc lộ, đại lộ, xa lộ"),
    (1513, "hy (heavy)", "nặng, (thuộc) hạng nặng"),
    (1513, "Hyg (hygiene)", "(phép) vệ sinh"),
    (1513, "Hz (Hertz)", "héc (đơn vị tần số)"),

    # ---------------- idx0749 / page 1514 ----------------
    (1514, "I (ignition)", "(k.hiệu) (mồi) nổ"),
    (1514, "I (immediate)", "ngay lập tức"),
    (1514, "I (incendiary)", "(k.hiệu) cháy"),
    (1514, "I (individual)", "(thuộc) cá nhân; (thuộc) riêng; (thuộc) độc lập; (thuộc) đơn lẻ"),
    (1514, "I (interceptor)", "(k.hiệu) máy bay đánh chặn; tên lửa đánh chặn"),
    (1514, "I&R (intelligence and reconnaissance)", "tình báo và trinh sát; trinh sát; (thuộc) trinh sát"),
    (1514, "I&W (indications and warning)", "các chỉ dẫn và báo động"),
    (1514, "i.c.e. (internal-combustion engine)", "động cơ đốt trong"),
    (1514, "i.p. (ignition point)", "điểm bốc cháy"),
    (1514, "I.V. (initial velocity)", "sơ tốc; tốc độ đầu"),
    (1514, "I/B (inboard)", "bên trong tàu thuỷ; bên trong máy bay"),
    (1514, "I/I (inventory and inpection (report))", "bản phúc trình thanh tra"),
    (1514, "I/O (input/output)", "đầu vào/ đầu ra; nhập/xuất dữ liệu"),
    (1514, "I/R (internment/resettlement)", "sự giam giữ/ sự tái định cư"),
    (1514, "IA (information assurance)", "sự bảo đảm thông tin"),
    (1514, "IA (initial assessment)", "sự đánh giá ban đầu; sự đánh giá sơ bộ"),
    (1514, "IA (intelligence assessment)", "sự đánh giá tin tình báo"),
    (1514, "IAC (instrument approach and landing)", "tiếp cận và hạ cánh bằng thiết bị"),
    (1514, "IAC (Irish Air Corps)", "quân đoàn không quân Ailen"),
    (1514, "IADB (Inter-American Defense Board)", "hội đồng quốc phòng các nước châu Mỹ"),
    (1514, "IADC (Inter-American Defense College)", "trường đại học quốc phòng các nước châu Mỹ"),
    (1514, "IADS (Integrated Air Defense System)", "hệ thống phòng không hợp nhất"),
    (1514, "IADT (integrated automatic detection & tracking)", "hệ thống tự động bắt bám (mục tiêu) hợp nhất"),
    (1514, "IAEA (International Atomic Energy Agency)", "cơ quan năng lượng nguyên tử quốc tế"),
    (1514, "IAF (initial approach fix)", "mốc tiếp cận ban đầu; sự xác định vị trí tiếp cận ban đầu"),
    (1514, "IAFV (infantry armoured fighting vehicle)", "xe chiến đấu bộ binh bọc thép"),
    (1514, "IAGS (improved aircraft gun system)", "hệ thống súng pháo trên máy bay cải tiến"),
    (1514, "IAI (Israel Aircraft Industries)", "ngành công nghiệp hàng không Ixraen"),
    (1514, "IAMS (Integrated armament management system)", "hệ thống quản lý vũ khí trang bị hợp nhất"),
    (1514, "IANEC (Inter-American Nuclear Energy Commission)", "uỷ ban năng lượng hạt nhân các nước châu Mỹ"),

    # ---------------- idx0750 / page 1515 ----------------
    (1515, "IAP (instrument approach procedure)", "phương thức tiếp cận bằng thiết bị"),
    (1515, "IAP (international airport)", "sân bay quốc tế"),
    (1515, "IAPSO (Inter-Agency Procurement Services office)", "(UN) văn phòng dịch vụ mua sắm liên ngành (Liên hiệp quốc)"),
    (1515, "IAR (Interoperability assessment report)", "sự báo cáo đánh giá khả năng phối hợp tác chiến; báo cáo đánh giá khả năng tác nghiệp chung (vũ khí trang bị)"),
    (1515, "IAS (indicated airspeed)", "tốc độ bay biểu kiến"),
    (1515, "IAS (Institute of American Strategy)", "viện chiến lược Mỹ"),
    (1515, "IASC (Inter-Agency Standing Committee)", "ủy ban thường trực liên ngành (Liên hợp quốc)"),
    (1515, "IASD (Instant Ammunition Selection Device)", "thiết bị lựa chọn đạn dược tức thời"),
    (1515, "IASU (Inter-agency Support Unit)", "(UN) cơ quan hỗ trợ liên ngành (Liên hợp quốc)"),
    (1515, "iat (inside air temperature)", "nhiệt độ không khí bên trong"),
    (1515, "IAT (Institute for Applied Technology)", "viện công nghệ ứng dụng"),
    (1515, "IATA (International Air Transport Association)", "hiệp hội vận tải hàng không quốc tế"),
    (1515, "IATACS (Improved Army Tactical Communications System)", "hệ thống thông tin liên lạc chiến thuật cải tiến của lục quân"),
    (1515, "IATO (interim authority to operate)", "thẩm quyền hành động lâm thời"),
    (1515, "iaw (in accordance with)", "tương ứng với, phù hợp với"),
    (1515, "IAZ (inner artillery zone)", "vùng bên trong của hỏa lực pháo phòng không"),
    (1515, "IB; ib (incendiary bomb)", "bom cháy"),
    (1515, "IBCT (interim brigade combat team)", "cụm chiến đấu lâm thời cấp lữ đoàn"),
    (1515, "IBES (Intelligence budget estimate submission)", "tiểu ban dự toán ngân sách tình báo"),
    (1515, "IBH; IBHD (initial beachhead)", "bãi xuất phát đổ bộ (của quân đổ bộ đường biển)"),
    (1515, "IBM (intercontinental ballistic missile)", "tên lửa đạn đạo vượt đại châu"),
    (1515, "IBMT (intensive basic military training)", "sự huấn luyện quân sự cơ bản cấp tốc"),
    (1515, "IBRL (initial bomb release line)", "tuyến xuất phát ném bom"),
    (1515, "IBS (Integrated Broadcast System)", "hệ thống phát thanh truyền hình hợp nhất"),
    (1515, "IC (incident commander)", "người chỉ huy giải quyết sự cố"),
    (1515, "IC (information center)", "trung tâm tin tức"),
    (1515, "IC (intelligence community)", "cộng đồng tình báo"),
    (1515, "IC (intercept)", "đánh chặn"),
    (1515, "IC (internal combustion)", "sự đốt trong, sự cháy trong"),
    (1515, "IC eng (internal combustion engine)", "động cơ đốt trong"),
    (1515, "IC/EXCOM (Intelligence Community Executive Committee)", "ủy ban quản trị cộng đồng tình báo"),
    (1515, "ICA (individual combat actions (exercise))", "bài tập huấn luyện chiến thuật cá nhân"),
    (1515, "ICAF (Industrial College of the Armed Forces)", "trường đại học công nghiệp của lực lượng vũ trang"),
    (1515, "ICAO (International Civil Aviation Organisation)", "tổ chức hàng không dân dụng quốc tế"),
    (1515, "ICBM (IBM) (intercontinental ballistic missile)", "tên lửa đạn đạo xuyên lục địa, tên lửa đạn đạo vượt đại châu"),
    (1515, "ICC (information co-ordination centre)", "trung tâm phối hợp thông tin; trung tâm điều phối thông tin"),
    (1515, "ICC (intelligence coordination center)", "(USCG) trung tâm hiệp đồng tình báo (cảnh giới bờ biển Mỹ)"),
    (1515, "ICC (International Criminal Court)", "toà án tội phạm quốc tế"),
    (1515, "ICC (inventory control center)", "trung tâm quản lý kiểm kê"),

    # ---------------- idx0751 / page 1516 ----------------
    (1516, "ICCPR (International Covenant on Civil and Political Rights)", "hiệp ước quốc tế về các quyền dân sự và chính trị"),
    (1516, "ICE (internal combustion engine)", "động cơ đốt trong"),
    (1516, "ICESCR (International Covenant on Economic, Social and Cultural Rights)", "hiệp ước quốc tế về các quyền kinh tế, xã hội và văn hoá"),
    (1516, "ICG (International Crisis Group)", "nhóm giải quyết khủng hoảng quốc tế"),
    (1516, "ICGM (intercontinental guided missile)", "tên lửa có điều khiển vượt đại châu, tên lửa có điều khiển xuyên lục địa"),
    (1516, "ICL (instrument controlled landing)", "sự hạ cánh bằng thiết bị điều khiển"),
    (1516, "ICM (Improved conventional munition)", "đạn dược thông thường cải tiến"),
    (1516, "ICM (Increased capability missile)", "tên lửa đa năng hoá"),
    (1516, "ICM (intercontinental missile)", "tên lửa vượt đại châu, tên lửa xuyên lục địa"),
    (1516, "ICMS (Integrated countermeasures suite)", "bộ thiết bị chống tác chiến điện tử hợp nhất"),
    (1516, "ICN (Idle channel noise)", "tiếng ồn kênh"),
    (1516, "ICN (interface control net)", "mạng kiểm soát giao diện"),
    (1516, "ICNIA (Integrated communications, navigation and identification avionics)", "các ngành khoa học điện tử thông tin liên lạc dẫn đường và nhận biết hợp nhất"),
    (1516, "ICOD (intelligence cutoff data)", "dữ liệu giới hạn tình báo"),
    (1516, "ICON (imagery communications and operations node)", "đầu mối thông tin liên lạc hình ảnh và tác chiến"),
    (1516, "ICON (intermediate coordination node)", "đầu mối hiệp đồng trung gian"),
    (1516, "ICP (incident control point)", "địa điểm khắc phục hậu quả do sự cố gây ra"),
    (1516, "ICP (intertheater communications security (COMSEC) package)", "bộ trang thiết bị an ninh thông tin liên lạc liên chiến trường"),
    (1516, "ICRC (International Committee of the Red Cross)", "ủy ban chữ thập đỏ quốc tế"),
    (1516, "ICS (incident command system)", "hệ thống chỉ huy giải quyết sự cố"),
    (1516, "ICS (integrated communications system)", "hệ thống thông tin liên lạc hợp nhất"),
    (1516, "ICS (internal communications system)", "hệ thống thông tin liên lạc nội bộ"),
    (1516, "ICS (internal countermeasures set)", "bộ thiết bị chống tác chiến điện tử bên trong"),
    (1516, "ICS (inter-service chaplain support)", "sự hỗ trợ tuyên uý liên quân binh chủng"),
    (1516, "ICSAR (interagency committee on search and rescue)", "uỷ ban tìm kiếm và cứu nạn liên ngành"),
    (1516, "ICTOC (independent corps tactical operations center)", "trung tâm độc lập chỉ huy tác chiến của quân đoàn"),
    (1516, "ICTP (Intensified Combat Training Program)", "chương trình huấn luyện chiến đấu cấp tốc"),
    (1516, "ICU (intensive care unit)", "đơn vị bảo dưỡng tăng cường"),
    (1516, "ICU (interface control unit)", "bộ kiểm soát giao diện"),
    (1516, "ICUS (inside continental United States)", "ở phần lục địa Mỹ"),
    (1516, "ICV (Infantry Combat Vehicle)", "xe chiến đấu bộ binh"),
    (1516, "ICVA (International Council of Voluntary Agencies)", "hội đồng quốc tế của các cơ quan tình nguyện"),
    (1516, "ICWAR (Improved continuous wave acquisition radar)", "rađa bắt bám mục tiêu bằng sóng canh liên tục cải tiến"),
    (1516, "ID (identification)", "sự nhận biết; sự nhận dạng; nét nhận dạng"),
    (1516, "ID (inside diameter)", "đường kính trong"),
    (1516, "ID (Intelligence Department)", "cục tình báo"),
    (1516, "IDAD (internal defense and development)", "phòng thủ, xây dựng và phát triển lực lượng trong nước"),
    (1516, "IDB (Integrated database)", "cơ sở dữ liệu hợp nhất"),

    # ---------------- idx0752 / page 1517 ----------------
    (1517, "IDC (Imperial Defence College)", "trường đại học quốc phòng"),
    (1517, "IDDF (intermediate data distribution facility)", "phương tiện bảo đảm phân phối dữ liệu trung gian"),
    (1517, "IDEAS (Intelligence Data Elements Authorized Standards)", "tiêu chí phê chuẩn các yếu tố dữ liệu tình báo"),
    (1517, "ident (identification)", "sự nhận biết, sự nhận dạng; nét nhận dạng"),
    (1517, "IDEX (imagery data exploitation system)", "hệ thống khai thác dữ liệu ảnh"),
    (1517, "IDF (indicating direction finder)", "máy đo phương vị kiểu quang học"),
    (1517, "IDF (initial defense force)", "lực lượng phòng thủ ban đầu"),
    (1517, "IDF (intermediate distribution frame)", "khung phân phối trung gian"),
    (1517, "IDF (Israel Defence Forces)", "hoả lực phòng ngự Ixraen"),
    (1517, "IDG (integrated-drive generator)", "khối máy phát dẫn động từ động cơ"),
    (1517, "IDHS (intelligence data handling system)", "hệ thống quản lý dữ liệu tình báo"),
    (1517, "IDLH (immediately dangerous to life or health)", "nguy hiểm trực tiếp đến tính mạng và sức khỏe"),
    (1517, "IDNDR (International Decade for Natural Disaster Reduction)", "(UN) thập kỷ quốc tế về giảm nhẹ thiên tai (Liên hiệp quốc)"),
    (1517, "IDO (installation deployment officer)", "sĩ quan triển khai lắp đặt (thiết bị kho quân sự)"),
    (1517, "IDP (imminent danger pay)", "phụ cấp nguy hiểm"),
    (1517, "IDP (integrated data processing)", "xử lý tổ hợp dữ liệu"),
    (1517, "IDP (internally displaced persons)", "người tản cư nội địa"),
    (1517, "IDR (Infantry Drill Regulations)", "điều lệnh huấn luyện bộ binh; điều lệnh đội ngũ bộ binh"),
    (1517, "IDS (Individual deployment site)", "vị trí triển khai cá nhân"),
    (1517, "IDS (Integrated deployment system)", "hệ thống triển khai hợp nhất"),
    (1517, "IDS (interface design standards)", "tiêu chí thiết kế giao diện"),
    (1517, "IDS (intrusion detection system)", "hệ thống phát hiện xâm nhập"),
    (1517, "IDSS (interoperability decision support system)", "hệ thống bảo đảm hạ quyết tâm phối hợp tác chiến"),
    (1517, "IDT (Inactive duty training)", "sự huấn luyện dự bị động viên"),
    (1517, "IDW (individual defence weapon)", "vũ khí tự vệ cá nhân"),
    (1517, "IDZ (inner defense zone)", "khu vực phòng ngự bên trong"),
    (1517, "IE (intelligence estimate)", "đánh giá tình hình theo dữ kiện trinh sát"),
    (1517, "IED (improvised explosive device)", "thiết bị nổ tự tạo; bom mìn tự tạo"),
    (1517, "IEFR (International Emergency Food Reserve)", "lượng dự trữ lương thực quốc tế cho tình trạng khẩn cấp"),
    (1517, "IEL (illustrative evaluation scenario)", "tưởng định đánh giá minh họa"),
    (1517, "IEMATS (improved emergency message automatic transmission system)", "hệ thống truyền tin điện tự động khẩn cấp cải tiến"),
    (1517, "IEPG (Independent European Program Group)", "nhóm chương trình châu Âu độc lập"),
    (1517, "IER (information exchange requirement)", "yêu cầu trao đổi thông tin"),
    (1517, "IES (imagery exploitation system)", "hệ thống khai thác tin tức ảnh"),
    (1517, "IESS (imagery exploitation support system)", "hệ thống hỗ trợ khai thác tin tức ảnh"),
    (1517, "IEW (integrated electronic warfare)", "tác chiến điện tử hợp nhất"),
    (1517, "IEW (intelligence and electronic warfare)", "chiến tranh tình báo và điện tử"),
    (1517, "IEWCS (intelligence and electronic warfare common sensors)", "xenxơ chung cho tình báo và tác chiến điện tử"),
    (1517, "IF (impact fuze)", "ngòi chạm nổ"),
]

fieldnames = [
    "source_page", "dictionary_name", "word", "phonetic",
    "part_of_speech_raw", "part_of_speech_code", "meaning_vi",
    "is_subentry", "example_en", "example_vi", "image_path", "reviewed",
]

rows = []
for page, word, meaning in entries:
    rows.append({
        "source_page": page,
        "dictionary_name": "Military Dictionary",
        "word": word,
        "phonetic": "",
        "part_of_speech_raw": "",
        "part_of_speech_code": "",
        "meaning_vi": meaning,
        "is_subentry": "FALSE",
        "example_en": "",
        "example_vi": "",
        "image_path": f"img_{page}.jpg",
        "reviewed": "FALSE",
    })

out_path = "docs/db/import/tudien_abbr_chunks/chunk_0738_0752.csv"
with open(out_path, "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote {len(rows)} entries to {out_path}")
