# -*- coding: utf-8 -*-
"""
Build chunk_0753_0767.csv from manual vision-based transcription of
docs/db/import/tudien_abbr_pages/idx0753.png .. idx0767.png
(PDF page indices 753-767, printed pages 1518-1532).

This is a RETRY (3rd attempt) at this exact page range. Data below was
transcribed by reading each page image directly (not OCR).
"""
import csv

# Each tuple: (printed_page, word, meaning_vi)
ENTRIES = [
    # ---------------- 1518 (idx0753) ----------------
    (1518, "IF (Instrument flying)", "sự bay bằng khí tài"),
    (1518, "IF (intermediate frequency)", "tần số trung gian"),
    (1518, "IF/FCS (Integrated fire/flight control system)", "hệ thống chỉ huy hỏa lực và điều khiển bay hợp nhất"),
    (1518, "IFC (Integrated fire control)", "(hệ thống) điều khiển hoả lực hợp nhất"),
    (1518, "IFC (Intelligence fusion center)", "trung tâm liên kết tình báo"),
    (1518, "IFCS (Improved Fire-Control System)", "hệ thống điều khiển hoả lực cải tiến"),
    (1518, "IFCS (Integrated Fire-Control System)", "hệ thống điều khiển hoả lực hợp nhất"),
    (1518, "IFF (identification friend or foe)", "sự nhận biết ta - địch; sự nhận biết máy bay ta - địch"),
    (1518, "IFF/SIF (identification, friend or foe/selective identification feature)", "đặc điểm nhận biết lựa chọn/ nhận biết ta - địch"),
    (1518, "IFFN (identification, friend, foe, or neutral)", "sự nhận biết ta - địch hoặc lực lượng trung lập"),
    (1518, "IFICS (In-flight Interceptor Communications System)", "hệ thống thông tin liên lạc của tổ hợp đánh chặn (tên lửa đạn đạo) trên đường bay"),
    (1518, "IFM (Infantry Field Manual)", "điều lệnh chiến đấu bộ binh"),
    (1518, "IFMCS (Integrated fire & maneuver control system)", "hệ thống chỉ huy hỏa lực và cơ động hợp nhất"),
    (1518, "IFMU (integrated flight management unit)", "thiết bị quản lí bay hợp nhất"),
    (1518, "IFOBL (In-flight operable bomb lock)", "khóa bom (có thể) tác nghiệp trong khi bay"),
    (1518, "IFOR (Implementation Force (NATO))", "lực lượng thi hành (của liên quân NATO)"),
    (1518, "IFR (indirect fire simulator)", "thiết bị mô phỏng hỏa lực gián tiếp"),
    (1518, "IFR (instrument flight rules)", "quy tắc bay bằng thiết bị"),
    (1518, "IFR (Intelligence file report)", "đặc điểm trinh sát của mục tiêu, đặc điểm mục tiêu trinh sát"),
    (1518, "IFS (inshore fire support ship)", "tàu pháo cối; tàu chi viện hỏa lực pháo binh (cho quân đổ bộ)"),
    (1518, "IFT (indirect fire trainer)", "thiết bị huấn luyện bắn gián tiếp"),
    (1518, "IFT (instructor flown target)", "mục tiêu bay theo sự điều khiển của giáo viên"),
    (1518, "IFV (infantry fighting vehicle)", "xe chiến đấu bộ binh"),
    (1518, "IFVwICM (Infantry Fighting Vehicle with Integrated Countermeasures (US))", "xe chiến đấu bộ binh có sử dụng các phương tiện đối phó (điện tử) hợp nhất (Mỹ)"),
    (1518, "IFWES (Indirect fire weapon effect simulation)", "sự mô phỏng hiệu quả của vũ khí bắn gián tiếp"),
    (1518, "IG (inspector general)", "tổng thanh tra"),
    (1518, "IGCC (Institute of Global Conflict and Cooperation)", "viện nghiên cứu về xung đột và hợp tác toàn cầu"),
    (1518, "IGLS (individual grenade launcher system)", "tổ hợp phóng lựu cá nhân"),
    (1518, "IGS (internal gun system)", "tổ hợp pháo trong (tháp tăng)"),
    (1518, "IGSM (interim ground station module (JSTARS))", "môđun trạm mặt đất tạm thời (của hệ thống rada trinh sát tiến công mục tiêu liên quân)"),
    (1518, "IGTM (inertial guided tactical missile)", "tên lửa chiến thuật có hệ thống dẫn đường quán tính"),
    (1518, "IHADSS (integrated helmet and display sight system (Army))", "tổ hợp mũ sắt và màn hình đường ngắm hợp nhất (lục quân)"),
    (1518, "IHADSS (Integrated helmet and display sighting system)", "hệ thống ngắm bắn có màn hiển thị gắn trên mũ bay; tổ hợp mũ sắt và màn hiển thị ngắm bắn hợp nhất"),
    (1518, "IHAS (integrated helicopter attack system)", "tổ hợp vũ khí tiến công hợp nhất dùng cho máy bay trực thăng"),
    (1518, "IHAS (integrated helicopter avionics system)", "hệ thống điện tử hàng không hợp nhất dùng cho máy bay trực thăng"),

    # ---------------- 1519 (idx0754) ----------------
    (1519, "IHP (indicated horse power)", "mã lực lý thuyết"),
    (1519, "II (intelligence information)", "thông tin tình báo"),
    (1519, "IIB (interagency information bureau)", "cục thông tin liên ngành"),
    (1519, "III (incapacitating illness or injury)", "bệnh tật hoặc thương tật làm mất khả năng (chiến đấu)"),
    (1519, "IIM (intelligence information management)", "(hệ thống) quản lý thông tin tình báo"),
    (1519, "IIP (interoperability improvement program)", "chương trình hoàn thiện khả năng phối hợp tác chiến"),
    (1519, "IIR (imagery interpretation report)", "bản báo cáo kết quả phân tích trinh sát ảnh"),
    (1519, "IIR (imaging infrared)", "thiết bị hình ảnh hồng ngoại"),
    (1519, "IIR (intelligence information report)", "báo cáo tin tức tình báo"),
    (1519, "IISS (International Institute for Strategic Studies)", "viện quốc tế nghiên cứu về chiến lược"),
    (1519, "IJC3S (initial joint command, control, and communications system)", "hệ thống chỉ huy, kiểm soát và thông tin liên lạc liên quân ban đầu"),
    (1519, "IJC3S (Integrated Joint Command, Control, and Communications System)", "hệ thống chỉ huy, kiểm soát và thông tin liên lạc liên quân hợp nhất"),
    (1519, "IJMS (Interim JTIDS message specification)", "việc xác định tin điện của hệ thống cung cấp thông tin chiến thuật liên quân lâm thời"),
    (1519, "IJN (Imperial Japanese Navy)", "hải quân Nhật hoàng"),
    (1519, "IKBS (intelligence knowledge-based system)", "hệ thống tình báo dựa trên thông tin đã biết trước"),
    (1519, "IKW (intercept & kill weapon)", "vũ khí đánh chặn và tiêu diệt"),
    (1519, "IL (initial line)", "tuyến xuất phát"),
    (1519, "IL (instrument landing)", "sự hạ cánh bằng thiết bị"),
    (1519, "IL (intermediate location)", "vị trí trung gian"),
    (1519, "ILAAS (integrated low altitude attack subsystem)", "phân hệ hợp nhất tiến công tầm thấp"),
    (1519, "ILAD (inner layer air defence system)", "hệ thống phòng không vòng trong"),
    (1519, "ILL (illuminating)", "sự chiếu sáng"),
    (1519, "ILLUM (illumination)", "sự chiếu sáng"),
    (1519, "ILMS (Improved Launcher Mechanical System)", "tổ hợp cơ cấu phóng cải tiến"),
    (1519, "ILO (in lieu of)", "thay vì ..."),
    (1519, "ILO (intelligence liaison officer)", "sĩ quan thông tin liên lạc trinh sát; sĩ quan thông tin liên lạc ngành tình báo"),
    (1519, "ILOC (internal line(s) of communication)", "các tuyến thông tin liên lạc nội địa; tuyến thông tin liên lạc nội bộ"),
    (1519, "ILOUE (in lieu of until exhausted)", "thay thế cho ... đến hết"),
    (1519, "ILS (instrument landing system)", "hệ thống (điều khiển) hạ cánh bằng khí tài"),
    (1519, "ILS (Integrated Logistic Support)", "sự bảo đảm hậu cần tập trung (hoá), sự bảo đảm hậu cần hợp nhất"),
    (1519, "ILSS (integrated logistic support system)", "hệ thống bảo đảm hậu cần tập trung"),
    (1519, "IM (information management)", "quản lý thông tin"),
    (1519, "IM (insensitive munitions)", "đạn không nhạy nổ, đạn trơ"),
    (1519, "IM (interceptor missile)", "tên lửa đánh chặn"),
    (1519, "IMA (individual mobilization augmentee)", "người được nâng cấp động viên cá nhân"),
    (1519, "IMAAWS (infantry man-portable anti-armor/assault weapon system)", "tổ hợp vũ khí bộ binh mang vác xung kích và chống tăng thiết giáp"),
    (1519, "IMAIS (integrated magnetic & acoustic influence sweep)", "sự rà quét thủy lôi hợp nhất từ tính và âm thanh"),
    (1519, "IMB (International Maritime Bureau)", "cục hàng hải quốc tế"),

    # ---------------- 1520 (idx0755) ----------------
    (1520, "IMBPRC (International Maritime Bureau Piracy Reporting Center)", "trung tâm thông báo về cướp biển thuộc cục hàng hải quốc tế"),
    (1520, "IMC (instrument meteorological conditions)", "điều kiện khí tượng bay thiết bị"),
    (1520, "IMDC (interceptor missile direction center)", "trung tâm điều khiển tên lửa phòng không; trung tâm chỉ huy tên lửa đánh chặn; trung tâm điều khiển tên lửa chống tên lửa"),
    (1520, "IMET (International military education and training)", "sự huấn luyện và đào tạo quân sự quốc tế"),
    (1520, "IMETS (Integrated Meteorological System)", "hệ thống khí tượng hợp nhất"),
    (1520, "IMEWS (integrated missile early warning system)", "hệ thống cảnh báo sớm tên lửa hợp nhất"),
    (1520, "IMI (international military information)", "thông tin quân sự quốc tế"),
    (1520, "IMICS (integrated mine-hunting combat system)", "hệ thống săn mìn hợp nhất; (hq) hệ thống rà quét thủy lôi hợp nhất"),
    (1520, "IMINT (imagery intelligence)", "tình báo ảnh; tin tức tình báo bằng hình ảnh"),
    (1520, "IMIT (international military information team)", "đội thu thập tin tức quân sự quốc tế"),
    (1520, "IMK (Increased maneuverability kit)", "khối thiết bị làm tăng khả năng cơ động"),
    (1520, "IMM (Integrated materiel management)", "sự quản lý trang bị kỹ thuật hợp nhất, sự quản lý vũ khí trang bị tập trung (hóa)"),
    (1520, "IMMDELREQ (immediate delivery required)", "yêu cầu cấp phát tức thời"),
    (1520, "immed (immediate)", "tức thì; trực tiếp, gần; trước mắt; ban đầu"),
    (1520, "IMMLC (Improved Medium Mobility Load Carrier)", "xe vận tải cơ động hạng trung cải tiến"),
    (1520, "IMO (information management officer)", "sĩ quan quản lý thông tin"),
    (1520, "IMO (International Maritime Organization)", "tổ chức hàng hải quốc tế"),
    (1520, "IMOSAR (search and rescue manual, international maritime organisation)", "cẩm nang tìm kiếm và cứu nạn của tổ chức hàng hải quốc tế"),
    (1520, "imp (improved)", "cải tiến; nâng cấp"),
    (1520, "Impgal (Imperial gallon)", "galông (bằng 4,54 lít)"),
    (1520, "IMS (information management system)", "hệ thống quản lý thông tin"),
    (1520, "IMS (Integrated multiplex system)", "hệ thống đa lộ (thông tin) hợp nhất"),
    (1520, "IMS (international military staff)", "cơ quan tham mưu quân sự quốc tế"),
    (1520, "IMS (international military standardization)", "tiêu chuẩn hoá quân sự quốc tế"),
    (1520, "IMSS (Imaginary Intelligence Support System)", "hệ thống bảo đảm tin tức tình báo bằng hình ảnh"),
    (1520, "IMSS (integrated multi-sensor system)", "hệ thống tích hợp đa xenxơ"),
    (1520, "IMSU (Installation medical support unit)", "đơn vị bảo đảm quân y cơ quan; phân đội bảo đảm quân y đơn vị"),
    (1520, "IMT (International Military Tribunal)", "tòa án quân sự quốc tế"),
    (1520, "IMU (inertial measuring unit)", "đơn vị đo quán tính"),
    (1520, "IMUA (Interservice Materiel Utilization Agency)", "cơ quan liên bộ về sử dụng trang bị kỹ thuật"),
    (1520, "IN (Air Force component intelligence officer (staff))", "sĩ quan tình báo (bộ tham mưu) không quân hợp thành"),
    (1520, "IN (impulse noise)", "tiếng ồn xung"),
    (1520, "In (inch)", "inxơ (bằng 25,4mm)"),
    (1520, "IN (instructor)", "giảng viên; huấn luyện viên; hướng dẫn viên"),
    (1520, "In sit (initial situation)", "tình hình ban đầu; tình huống ban đầu"),
    (1520, "inact (inactive)", "không hoạt động, thiếu hoạt động; tình trạng dự bị; trong lực lượng dự bị; không trong biên chế"),
    (1520, "INAS (integrated nav/attack system)", "hệ thống dẫn đường và tiến công hợp nhất"),

    # ---------------- 1521 (idx0756) ----------------
    (1521, "incd (incendiary)", "cháy, đánh lửa"),
    (1521, "incd agt (incendiary agent)", "chất cháy"),
    (1521, "INCL (inclosed)", "bao gồm"),
    (1521, "incl (includes/ including)", "bao gồm"),
    (1521, "INCNR (increment number)", "số tăng thêm; số gia"),
    (1521, "INCSEA (Incidents at sea)", "sự cố trên biển"),
    (1521, "inctd (inducted)", "được gọi nhập ngũ"),
    (1521, "IND (Improvised nuclear device)", "thiết bị nổ hạt nhân tự tạo, vũ khí hạt nhân tự tạo"),
    (1521, "ind (independent)", "sự độc lập; sự không phụ thuộc; sự tự hoạt động"),
    (1521, "IND (indorsement)", "sự ký giao; sự xác nhận"),
    (1521, "indctd (inducted)", "được gọi nhập ngũ"),
    (1521, "indep (Independent)", "sự độc lập; sự không phụ thuộc; sự tự hoạt động"),
    (1521, "indiv (individual)", "(thuộc) cá nhân; (thuộc) riêng; (thuộc) độc lập; (thuộc) đơn lẻ, riêng lẻ"),
    (1521, "INEWS (integrated electronic warfare system)", "tổ hợp tác chiến điện tử hợp nhất; hệ thống chiến tranh điện tử hợp nhất"),
    (1521, "INF; inf (infantry)", "bộ binh"),
    (1521, "inf (information)", "thông tin, tin tức, dữ liệu, dữ kiện"),
    (1521, "INF (Intermediate-range Nuclear Forces)", "lực lượng vũ trang hạt nhân tầm trung"),
    (1521, "inf (Mech) (mechanized infantry)", "bộ binh cơ giới"),
    (1521, "Inf Bn; inf bn (infantry battalion)", "tiểu đoàn bộ binh"),
    (1521, "Inf Brig (infantry brigade)", "lữ đoàn bộ binh"),
    (1521, "Inf Co; Inf Coy (infantry company)", "đại đội bộ binh"),
    (1521, "Inf Div (infantry division)", "sư đoàn bộ binh"),
    (1521, "INF L (inflammable liquids)", "chất lỏng dễ bắt lửa"),
    (1521, "inf (Mech) (infantry, mechanized)", "bộ binh cơ giới hoá"),
    (1521, "Inf Sch (infantry school)", "trường sĩ quan bộ binh, trường sĩ quan lục quân"),
    (1521, "INFLIGHTREP (in-flight report (voice only))", "sự báo cáo trong chuyến bay (bằng âm thanh)"),
    (1521, "info (Information)", "thông tin, tin tức, dữ liệu, dữ kiện"),
    (1521, "Info O (information officer)", "sĩ quan thông tin"),
    (1521, "INFOSEC (information security)", "an ninh thông tin"),
    (1521, "INFOSYS (information system)", "hệ thống thông tin"),
    (1521, "ING (Inactive National Guard)", "lực lượng dự bị cảnh vệ quốc gia"),
    (1521, "INH (improved Nike-Hercules)", "tên lửa cải tiến Naicơ - Hécquyn"),
    (1521, "INID (intercept network in dialing)", "mạng nghe chặn quay số, mạng thính sát quay số"),
    (1521, "INJILL (injured or ill)", "bị thương hoặc ốm"),
    (1521, "INMARSAT (International maritime satellite)", "vệ tinh hàng hải quốc tế"),
    (1521, "INR (Bureau of Intelligence and Research, Department of State)", "cục tình báo và nghiên cứu bộ ngoại giao"),
    (1521, "INREPL (incoming replacement)", "bổ sung quân"),
    (1521, "INREQ (information request)", "yêu cầu thông tin"),
    (1521, "INS (Inertial navigation system)", "hệ thống dẫn đường quán tính; hệ thống đạo hàng quán tính"),
    (1521, "INS (Insurance)", "sự bảo hiểm"),
    (1521, "insbn (insubordination)", "sự không phục tùng, sự không tuân lệnh, sự không chấp hành mệnh lệnh người chỉ huy"),
    (1521, "INSCOM (United States Army Intelligence and Security Command)", "bộ tư lệnh tình báo và an ninh lục quân Mỹ"),
    (1521, "INSE (Institute of Nuclear Science and Engineering)", "viện khoa học và kỹ thuật hạt nhân"),
    (1521, "INSP (inspect)", "thanh tra, kiểm tra, thanh sát"),
    (1521, "insp (inspection)", "sự thanh tra; sự kiểm tra"),
    (1521, "Insp Gen (Inspector General)", "tổng thanh tra"),
    (1521, "instl (installation)", "sự đặt (hệ thống máy móc); đặt ai (vào điều kiện, vị trí ...); lễ nhận chức; cơ sở; đồn bốt, căn cứ; trang thiết bị"),

    # ---------------- 1522 (idx0757) ----------------
    (1522, "INSTR (instruct)", "huấn luyện"),
    (1522, "instr (instruction)", "sự chỉ thị; tài liệu hướng dẫn; sự huấn luyện; chỉ lệnh"),
    (1522, "Int (intelligence)", "tình báo; tin tức tình báo; trinh sát; tin tức trinh sát"),
    (1522, "int O (intelligence officer)", "sĩ quan tình báo; trưởng phòng quân báo; sĩ quan trinh sát; trưởng phòng trinh sát"),
    (1522, "Int Sum (intelligence summary)", "báo cáo tổng hợp tin tức tình báo; báo cáo tổng hợp tin tức trinh sát"),
    (1522, "INTAC (individual terrorism awareness course)", "khoá huấn luyện cá nhân về nhận biết chủ nghĩa khủng bố"),
    (1522, "INTACS (integrated tactical communications system)", "hệ thống thông tin liên lạc chiến thuật hợp nhất"),
    (1522, "INTC (Intelligence Corps)", "ngành tình báo"),
    (1522, "INTCP; intcp (intercept)", "sự đánh chặn; sự bắt chặn sóng vô tuyến; sự nghe trộm vô tuyến"),
    (1522, "intel (intelligence)", "tình báo; tin tức tình báo; trinh sát; tin tức trinh sát"),
    (1522, "intel off (intelligence officer)", "sĩ quan tình báo; trưởng phòng quân báo; sĩ quan trinh sát; trưởng ban trinh sát"),
    (1522, "intel spt (intelligence support)", "sự bảo đảm tình báo"),
    (1522, "INTELSAT (International Telecommunications Satellite Organization)", "tổ chức vệ tinh thông tin liên lạc quốc tế"),
    (1522, "INTELSITSUM (intelligence situation summary)", "bản tổng hợp tình hình của tình báo"),
    (1522, "intercom(n) (intercommunication)", "thông tin liên lạc hai chiều; thông tin liên lạc nội bộ (trong xe tăng, máy bay...)"),
    (1522, "intmed (intermediate)", "trung gian; trung bình; phụ; bổ trợ; chuyển tiếp; tiếp sức"),
    (1522, "intmed obj (intermediate objective)", "mục tiêu trung gian"),
    (1522, "intpr (interpret)", "phiên dịch"),
    (1522, "INTR (in transit)", "thông qua"),
    (1522, "INTREPT (intelligence report)", "bản báo cáo tình báo; sự báo cáo tình báo; báo cáo tin tức trinh sát"),
    (1522, "INTSUM (Intelligence summary)", "bản tổng hợp tin tình báo"),
    (1522, "INU (inertial navigation unit)", "bộ dẫn đường bằng quán tính"),
    (1522, "INU (integration unit)", "đơn vị hợp nhất"),
    (1522, "INV (invalid)", "thương phế binh"),
    (1522, "INVES (investigate)", "điều tra"),
    (1522, "INVOL (involuntary)", "không tự nguyện"),
    (1522, "IO (information objectives)", "các mục tiêu thông tin"),
    (1522, "IO (information officer)", "sĩ quan thông tin; sĩ quan tin học"),
    (1522, "IO (information operations)", "tác chiến thông tin"),
    (1522, "IO (intelligence officer)", "sĩ quan tình báo; trưởng phòng tình báo; sĩ quan trinh sát; trưởng ban trinh sát"),
    (1522, "IO (intelligence operations)", "tác chiến tình báo; các hoạt động tình báo"),
    (1522, "IO (intelligence oversight)", "giám sát tình báo"),
    (1522, "IO (international organization)", "tổ chức quốc tế"),
    (1522, "IOC (Industrial Operations Command)", "bộ chỉ huy điều hành hoạt động công nghiệp"),
    (1522, "IOC (initial operational capability)", "khả năng tác chiến ban đầu"),
    (1522, "IOC (Integrated Operations Center)", "trung tâm chỉ huy tác chiến hợp nhất"),
    (1522, "IOC (intelligence operations center)", "trung tâm chỉ huy tác chiến tình báo"),
    (1522, "IOC (investigations operations center)", "trung tâm chỉ huy hoạt động điều tra"),
    (1522, "IOH (Items on hand)", "trang bị hiện có, trang bị có sẵn trong tay"),
    (1522, "IOI (injured other than hostilities or illness)", "bị thương tật không phải do chiến đấu hoặc ốm đau, thương tật do tai nạn"),
    (1522, "IOP (interface operating procedure)", "quy trình vận hành giao diện"),

    # ---------------- 1523 (idx0758) ----------------
    (1523, "IOR (immediate operations requirement)", "nhu cầu tác chiến trước mắt"),
    (1523, "IOS (integrated observation system)", "hệ thống quan sát hợp nhất"),
    (1523, "IOU (input/output unit)", "đơn vị đầu vào/đầu ra; đơn vị nhập/xuất dữ liệu"),
    (1523, "IP (fuel)", "nhiên liệu (dùng cho động cơ phản lực)"),
    (1523, "IP (identification of position)", "sự nhận biết vị trí"),
    (1523, "IP (impact point)", "điểm rơi; điểm trúng đích; điểm chạm; điểm tiếp đất"),
    (1523, "IP (information provider)", "nguồn cung cấp thông tin"),
    (1523, "IP (initial phase)", "pha ban đầu"),
    (1523, "IP (initial point)", "địa điểm xuất phát cơ động; (kq) khởi đầu đường bay"),
    (1523, "IP (initial position)", "vị trí ban đầu"),
    (1523, "IP (instructor pilot)", "phi công huấn luyện bay"),
    (1523, "IPA (intelligence production agency)", "cục sản xuất tin tình báo"),
    (1523, "IPB (intelligence preparation of the battlefield)", "sự chuẩn bị tin tình báo về địch"),
    (1523, "IPB (intelligence preparation of the battlespace)", "sự chuẩn bị trinh sát bảo đảm tác chiến vũ trụ"),
    (1523, "IPBD (intelligence program budget decision)", "sự quyết định ngân sách cho kế hoạch tình báo"),
    (1523, "IPBM (interplanetary ballistic missile)", "tên lửa đạn đạo liên hành tinh"),
    (1523, "IPC (interagency planning cell)", "bộ phận lập kế hoạch liên quân chủng"),
    (1523, "IPCP (improved command post)", "trạm chỉ huy cải tiến"),
    (1523, "IPCS (International Program on Chemical Safety (UN))", "chương trình quốc tế về an toàn hoá học (Liên hiệp quốc)"),
    (1523, "IPD (improved point defence)", "sự phòng thủ (mục tiêu) điểm cải tiến"),
    (1523, "IPDM (intelligence program decision memorandum)", "bản ghi nhớ về quyết định chương trình hoạt động tình báo"),
    (1523, "IPDP (inland petroleum distribution plan)", "kế hoạch phân phối xăng dầu trong đất liền"),
    (1523, "IPDS (imagery processing and dissemination system)", "hệ thống xử lý và phổ biến tin tức (trinh sát) ảnh"),
    (1523, "IPDS (inland petroleum distribution system)", "hệ thống phân phối xăng dầu trong đất liền"),
    (1523, "IPDSMS (improved point defense surface missile system)", "hệ thống tên lửa mặt đất phòng thủ (mục tiêu) cố định cải tiến"),
    (1523, "IPE (individual protective equipment)", "trang bị phòng hộ cá nhân"),
    (1523, "IPE (industrial plant equipment)", "thiết bị nhà máy công nghiệp"),
    (1523, "IPF (Initial Production Facility)", "điều kiện sản xuất quốc phòng ban đầu"),
    (1523, "IPIR (initial photo interpretation report)", "bản báo cáo kết quả phân tích ảnh ban đầu"),
    (1523, "IPO (International Programme Office)", "văn phòng chương trình quốc tế"),
    (1523, "IPOM (intelligence program objective memorandum)", "bản ghi nhớ mục tiêu chương trình hoạt động tình báo"),
    (1523, "IPP (impact point prediction)", "sự dự đoán về điểm rơi"),
    (1523, "IPP (industrial preparedness program)", "kế hoạch chuẩn bị công nghiệp sẵn sàng cho chiến tranh"),
    (1523, "IPR (intelligence periodic report)", "sự báo cáo tin tức tình báo khẩn; báo cáo tình báo khẩn cấp"),
    (1523, "IPR (intelligence production requirement)", "nhu cầu sản xuất tin tình báo"),
    (1523, "IPRG (intelligence program review group)", "nhóm duyệt chương trình hoạt động tình báo"),
    (1523, "IPS (illustrative planning scenario)", "tưởng định minh hoạ lập kế hoạch"),
    (1523, "IPS (interoperability planning system)", "hệ thống lập kế hoạch phối hợp tác chiến"),
    (1523, "IPSG (intelligence program support group)", "nhóm hỗ trợ chương trình hoạt động tình báo"),

    # ---------------- 1524 (idx0759) ----------------
    (1524, "IPSP (intelligence priorities for strategic planning)", "những ưu tiên (sử dụng) tình báo cho lập kế hoạch chiến lược"),
    (1524, "IPT (integrated planning team)", "đội lập kế hoạch hợp nhất"),
    (1524, "IPT (Integrated process team)", "đội xử lý tin tức tình báo hợp nhất"),
    (1524, "IPW (interrogation prisoner of war)", "sự lấy cung tù binh, sự thẩm vấn tù binh"),
    (1524, "IQ (intelligence quotient)", "(kh.ngữ) mưu trí"),
    (1524, "IR (incident report)", "báo cáo sự cố"),
    (1524, "IR (information rate)", "nhịp độ thông tin"),
    (1524, "IR (information requirement)", "nhu cầu thông tin"),
    (1524, "IR (infrared (Radiation))", "bức xạ hồng ngoại"),
    (1524, "IR (intelligence and reconnaissance)", "tình báo và trinh sát; quân báo; trinh sát"),
    (1524, "IR (interrogator-responsor radar)", "rada hỏi - đáp"),
    (1524, "IR pointer (infrared pointer)", "thiết bị chỉ thị mục tiêu bằng hồng ngoại"),
    (1524, "ir radn (infrared radiation)", "bức xạ hồng ngoại"),
    (1524, "ir equip (infrared equipment)", "thiết bị hồng ngoại"),
    (1524, "IRA (Irish Republican Army)", "quân đội cộng hoà Ailen"),
    (1524, "IRAC (information resource and analysis centre)", "trung tâm lưu giữ và phân tích thông tin"),
    (1524, "IRAC (interdepartment radio advisory committee)", "uỷ ban cố vấn vô tuyến điện liên quân chủng"),
    (1524, "IRAN (inspection and repair as necessary)", "kiểm tra và sửa chữa những chỗ cần thiết"),
    (1524, "IRAS (interdiction/reconnaissance attack system)", "hệ thống trinh sát tiến công và chia cắt"),
    (1524, "IRAWS (infrared attack weapon system)", "tổ hợp vũ khí tiến công hồng ngoại"),
    (1524, "IRBM (intermediate-range ballistic missile)", "tên lửa đạn đạo tầm trung"),
    (1524, "IRC (information retrieval center)", "trung tâm tìm kiếm thông tin"),
    (1524, "IRC (International Red Cross)", "hội chữ thập đỏ quốc tế"),
    (1524, "IRC (International Rescue Committee)", "uỷ ban cứu nạn quốc tế"),
    (1524, "IRCCM (infrared counter countermeasures)", "các biện pháp chống đối phó hồng ngoại; phương tiện chống đối phó hồng ngoại"),
    (1524, "IRCM (infrared countermeasures)", "các biện pháp chống tác chiến hồng ngoại của địch"),
    (1524, "IRDS (infrared detection set)", "khối phát hiện bằng hồng ngoại"),
    (1524, "IRDU (infrared detection unit)", "thiết bị kỹ thuật hồng ngoại dò tìm (mục tiêu), thiết bị phát hiện (mục tiêu) bằng hồng ngoại"),
    (1524, "IREW (infrared electronic warfare)", "tác chiến điện tử hồng ngoại"),
    (1524, "IREWS (infrared electronic warfare system)", "hệ thống tác chiến điện tử hồng ngoại"),
    (1524, "IRF (Immediate Reaction Forces (NATO))", "các lực lượng phản ứng tức thời (của NATO)"),
    (1524, "IRINT (infrared intelligence)", "trinh sát bằng thiết bị hồng ngoại"),
    (1524, "IRIS (infrared intruder system)", "hệ thống hồng ngoại phát hiện máy bay xâm nhập"),
    (1524, "IRLS (Infrared line scan)", "cảm biến hồng ngoại quét dòng"),
    (1524, "IRLS (interrogation, recording and location system)", "hệ thống hỏi, ghi và định vị"),
    (1524, "IRNF (intermediate range nuclear force)", "lực lượng hạt nhân tầm trung"),
    (1524, "IRO (International relief organization)", "tổ chức trợ giúp quốc tế"),
    (1524, "IROF (improved rate of fire)", "tăng nhịp bắn (súng pháo)"),
    (1524, "IRPTC (international register of potentially toxic chemicals)", "số đăng ký quốc tế về các chất độc hóa học tiềm tàng"),
    (1524, "IRR (individual ready reserve)", "quân nhân dự bị sẵn sàng động viên"),
    (1524, "IRR (integral rocket/ramjet)", "động cơ liên hợp rôcket / phản lực (không khí)"),
    (1524, "IRR (integrated readiness report)", "sự báo cáo tổng hợp về trạng thái sẵn sàng chiến đấu"),

    # ---------------- 1525 (idx0760) ----------------
    (1525, "IRRAD (infrared range and detection equipment)", "rada hồng ngoại phát hiện và định tầm (mục tiêu), thiết bị phát hiện và định tầm (mục tiêu) bằng hồng ngoại"),
    (1525, "IRS (inertial reference system)", "hệ quy chiếu quán tính"),
    (1525, "IRST (infrared search and track)", "tìm kiếm và bám sát mục tiêu bằng hồng ngoại, tìm bám mục tiêu bằng hồng ngoại"),
    (1525, "IRSTS (infrared search and track sensor)", "xenxơ hồng ngoại tìm kiếm và bám sát mục tiêu; xenxơ hồng ngoại tìm bám mục tiêu"),
    (1525, "IRSTS (infrared research and tracking system)", "hệ thống tìm kiếm và bám sát mục tiêu theo bức xạ hồng ngoại"),
    (1525, "IRT (Initial Response Team)", "đội phản ứng ban đầu"),
    (1525, "IRTC (infantry replacement training center)", "trung tâm huấn luyện bổ sung cho các đơn vị bộ binh"),
    (1525, "IRU (inertial reference unit)", "khối quy chiếu quán tính (tên lửa)"),
    (1525, "IRV (improved recovery vehicle)", "xe cứu kéo cải tiến"),
    (1525, "IRWR (infrared warning receiver)", "máy thu cảnh báo hồng ngoại"),
    (1525, "IS (information system)", "hệ thống thông tin"),
    (1525, "IS (integrated satellite)", "vệ tinh kết hợp, vệ tinh trinh sát và giám sát"),
    (1525, "IS (internal security)", "an ninh nội bộ; đội cảnh giới vòng trong (đội hình)"),
    (1525, "IS (interswitch)", "tổng đài"),
    (1525, "ISA (inter-service agreement)", "sự thoả thuận liên quân chủng"),
    (1525, "ISA (International Standard Atmosphere)", "khí quyển tiêu chuẩn quốc tế"),
    (1525, "ISAF (International Security Assistance Force)", "lực lượng trợ giúp an ninh quốc tế"),
    (1525, "ISB (intermediate staging base)", "căn cứ triển khai trung gian"),
    (1525, "ISC (infantry section carrier)", "xe (chuyên) chở tiểu đội bộ binh"),
    (1525, "ISC (Joint Steering Committee)", "uỷ ban lãnh đạo liên quân"),
    (1525, "ISCOMAZORES (Island Commander, Azores)", "tư lệnh (trưởng) phòng vệ quần đảo Axo"),
    (1525, "ISCOMBERMUDA (Island Commander, Bermuda)", "tư lệnh (trưởng) phòng vệ quần đảo Bécmuda"),
    (1525, "ISCOMFAEROES (Island Commander Faeroes)", "tư lệnh (trưởng) phòng thủ quần đảo Farâu"),
    (1525, "ISCOMGREENLAND (Island Commander, Greenland)", "tư lệnh (trưởng) phòng thủ Grinlen"),
    (1525, "ISCOMICELAND (Island Commander Iceland)", "tư lệnh (trưởng) phòng thủ Ailen"),
    (1525, "ISCS (integrated submarine combat system)", "hệ thống chiến đấu chống (tàu) ngầm hợp nhất"),
    (1525, "ISDB (integrated satellite communications (SATCOM) database)", "cơ sở dữ liệu thông tin liên lạc vệ tinh hợp nhất"),
    (1525, "ISDS (interior surface decontamination apparatus)", "thiết bị tiêu tẩy (độc) mặt trong (tàu xe)"),
    (1525, "ISE (intelligence support element)", "bộ phận bảo đảm tình báo; phân đội bảo đảm tình báo"),
    (1525, "ISF (integrated support facility)", "phương tiện bảo đảm hợp nhất"),
    (1525, "ISGU (infrared sight guidance unit)", "cơ cấu ngắm dẫn (hướng) hồng ngoại"),
    (1525, "ISIS (Institute of Strategic International Studies)", "viện nghiên cứu chiến lược quốc tế"),
    (1525, "ISMMP (integrated continental United States (CONUS) medical mobilization plan)", "kế hoạch động viên y tế hợp nhất phần lục địa nước Mỹ"),
    (1525, "ISO (isolation)", "sự cô lập (mục tiêu); sự cách ly"),
    (1525, "ISOO (Information Security Oversight Office)", "phòng giám sát an ninh thông tin"),

    # ---------------- 1526 (idx0761) ----------------
    (1526, "ISOPREP (isolated personnel report)", "(bản) báo cáo về tình hình quân nhân bị cách ly"),
    (1526, "ISR (identification-safety range)", "cự ly an toàn không bị nhận dạng"),
    (1526, "ISR (information storage and research)", "sự nghiên cứu và lưu trữ thông tin"),
    (1526, "ISR (intelligence, surveillance, and reconnaissance)", "tình báo, do thám và trinh sát"),
    (1526, "ISSA (inter-service support agreement)", "sự thoả thuận chi viện liên quân chủng"),
    (1526, "ISSM (information system security manager)", "người chỉ huy an ninh hệ thống thông tin"),
    (1526, "ISSO (information systems security organization)", "tổ chức bảo đảm an ninh các hệ thống thông tin"),
    (1526, "ISSR (independent secondary surveillance radar)", "rada quan sát định vị độc lập thứ cấp"),
    (1526, "IST (integrated system test)", "sự thử nghiệm tổ hợp vũ khí hợp nhất"),
    (1526, "IST (interswitch trunk)", "tổng đài chuyển tiếp"),
    (1526, "ISTPS (Joint Strategic Target Planning Staff)", "bộ tham mưu lập kế hoạch các mục tiêu chiến lược liên quân"),
    (1526, "ISU (Integrated Sight Unit)", "cơ cấu ngắm hợp nhất"),
    (1526, "ISUM (intelligence summary)", "bản báo cáo tổng hợp tin tức tình báo; báo cáo tổng hợp tin tức trinh sát"),
    (1526, "ISV (Internal Security Vehicle)", "xe cảnh giới vòng trong (đội hình)"),
    (1526, "ISZ (international security zone)", "khu vực an ninh quốc tế"),
    (1526, "IT (Italy)", "nước Ý"),
    (1526, "ITA (international telegraphic alphabet)", "hệ thống chữ cái điện thoại quốc tế"),
    (1526, "ITAC (intelligence and threat analysis center (Army))", "trung tâm hoạt động tình báo và phân tích các mối đe doạ (lục quân)"),
    (1526, "ITACS (intergrated tactical air-control system)", "hệ thống hợp nhất dẫn đường máy bay chiến thuật"),
    (1526, "ITALD (improved tactical air-launched decoy)", "tên lửa nghi binh chiến thuật hàng không cải tiến"),
    (1526, "ITAR (international traffic in arms regulation (coassembly))", "(nhóm phối hợp) điều chỉnh quy chế chống buôn lậu vũ khí quốc tế"),
    (1526, "ITC (infantry training center)", "trung tâm huấn luyện bộ binh"),
    (1526, "ITCS (integrated target control system)", "hệ thống hợp nhất điều khiển bia"),
    (1526, "ITEWS (integrated tactical electronic warfare system)", "hệ thống tác chiến điện tử chiến thuật hợp nhất"),
    (1526, "ITF (intelligence task force (DIA))", "lực lượng đặc vụ (thuộc cơ quan tình báo quốc phòng)"),
    (1526, "ITL (integrate-transfer-launch)", "lắp ráp, đặt và phóng"),
    (1526, "ITM (interceptor tactical missile)", "tên lửa chiến thuật phòng không có điều khiển"),
    (1526, "ITNS (integrated tactical navigation subsystem)", "phân hệ dẫn đường chiến thuật hợp nhất"),
    (1526, "ITO (installation transportation officer)", "sĩ quan chỉ huy vận tải thiết bị kho tàng"),
    (1526, "ITPIAL (infrared target point/illuminator/aiming laser (Mỹ))", "thiết bị lade chiếu, chỉ thị và ngắm mục tiêu (bằng) hồng ngoại, lade ITPIAL"),
    (1526, "ITRO (Inter-service training organization)", "tổ chức huấn luyện liên quân chủng"),
    (1526, "ITS (integrated target system)", "hệ thống bia hợp nhất"),
    (1526, "ITSS (integrated tactical surveillance system)", "hệ thống hợp nhất giám sát chiến đấu"),
    (1526, "ITU (International Telecommunications Union)", "liên đoàn thông tin liên lạc viễn thông quốc tế"),
    (1526, "ITV (Improved TOW Vehicle (US))", "xe bọc thép trang bị tên lửa chống tăng phóng từ ống, dẫn bằng dây, bám quang học cải tiến, xe bọc thép trang bị tên lửa chống tăng TOW"),

    # ---------------- 1527 (idx0762) ----------------
    (1527, "ITV (in-transit visibility)", "tầm nhìn xa qua khí tài"),
    (1527, "ITW/AA (integrated tactical warning and attack assessment)", "sự phân tích tổng hợp thông báo và tiến công đường không chiến thuật"),
    (1527, "IUS (inertial upper stage)", "tầng quán tính trên cùng (của tên lửa phóng tàu vũ trụ)"),
    (1527, "IUSS (integrated undersea surveillance system (Mỹ))", "hệ thống hợp nhất giám sát ngầm dưới biển"),
    (1527, "IUWG (inshore undersea warfare group)", "cụm tác chiến ngầm gần bờ"),
    (1527, "IVPDL (Inter-Vehicle Positioning and Data Link (US))", "sự liên kết dữ liệu và định vị giữa các xe (Mỹ); sự định vị và kết nối dữ liệu giữa các phương tiện mang phóng"),
    (1527, "IVSN (Initial Voice Switched Network)", "mạng thông tin liên lạc đàm thoại ban đầu"),
    (1527, "IW (individual weapon)", "vũ khí cá nhân, vũ khí bộ binh"),
    (1527, "IW (information warfare)", "chiến tranh thông tin; tác chiến thông tin"),
    (1527, "IWAC (integrated weapon-aiming system)", "hệ thống ngắm hợp nhất (dùng) cho vũ khí"),
    (1527, "IWC (integrated weapon complex)", "tổ hợp vũ khí hợp nhất"),
    (1527, "IWD (integrated weapon display)", "(bộ) hiển thị hợp nhất (trên) vũ khí"),
    (1527, "IWD (interactive weapon display)", "(bộ) hiển thị tương tác (trên) vũ khí"),
    (1527, "IW-D (defensive information warfare)", "tác chiến phòng thủ thông tin"),
    (1527, "IWESS (infantry weapon effects simulation system)", "hệ thống mô phỏng tác động (của) vũ khí bộ binh"),
    (1527, "IWG (intelligence working group)", "nhóm công tác tình báo"),
    (1527, "IWISTK (issue while in stock)", "phân phối đến hết hàng trong kho"),
    (1527, "IWS (Improved Weapon System)", "hệ thống vũ khí cải tiến; hệ thống hoả lực cải tiến"),
    (1527, "IWS (Individual weapon sight)", "thiết bị ngắm (trên) vũ khí cá nhân, cơ cấu ngắm của vũ khí bộ binh"),
    (1527, "IWS (inland waterway service)", "ngành vận tải thuỷ"),
    (1527, "IWS (integrated weapon system)", "hệ thống vũ khí hợp nhất"),
    (1527, "IWS (Interception Weapons School)", "trường sĩ quan tên lửa phòng không có điều khiển"),
    (1527, "IWSC (Information Warfare Support Center)", "trung tâm bảo đảm tác chiến thông tin"),
    (1527, "IWSDB (integrated weapon system data base)", "cơ sở dữ liệu (về) hệ thống vũ khí hợp nhất"),

    # ---------------- 1528 (idx0763) - letter "J" divider page ----------------
    (1528, "J and WO (jettison and washing overboard)", "ném xuống biển"),
    (1528, "J.S.S. Coll (Joint Services Staff College)", "trường tham mưu liên quân chủng, trường tham mưu quân chủng hợp thành"),
    (1528, "J1", "phòng quân lực; trưởng phòng quân lực (bộ tham mưu liên quân)"),
    (1528, "J1 (joint staff officer for personnel)", "(k.hiệu) sĩ quan quân lực bộ tham mưu liên quân"),
    (1528, "J2", "phòng trinh sát; trưởng phòng trinh sát (bộ tham mưu liên quân)"),
    (1528, "J2 (joint staff officer for intelligence)", "(k.hiệu) sĩ quan tình báo bộ tham mưu liên quân"),
    (1528, "J3", "phòng tác chiến và huấn luyện chiến đấu; trưởng phòng tác chiến và huấn luyện chiến đấu (bộ tham mưu liên quân)"),
    (1528, "J3 (joint staff officer for operations)", "(k.hiệu) sĩ quan tác chiến bộ tham mưu liên quân"),
    (1528, "J4", "phòng hậu cần; trưởng phòng hậu cần (bộ tham mưu liên quân)"),
    (1528, "J4 (joint staff officer for logistics)", "(k.hiệu) sĩ quan hậu cần bộ tham mưu liên quân"),
    (1528, "J5", "phòng kế hoạch quân sự; trưởng phòng kế hoạch quân sự (của bộ tham mưu liên quân)"),
    (1528, "J5 (joint staff officer for planning)", "(k.hiệu) sĩ quan kế hoạch bộ tham mưu liên quân"),
    (1528, "J6", "phòng thông tin liên lạc và kỹ thuật điện tử; trưởng phòng thông tin liên lạc và kỹ thuật điện tử (bộ tham mưu liên quân)"),
    (1528, "J6 (joint staff officer for command, control, communication and computer)", "(k.hiệu) sĩ quan bảo đảm chỉ huy, kiểm soát thông tin liên lạc và máy tính bộ tham mưu liên quân"),
    (1528, "J-3 (operations directorate of a joint staff)", "cục tác chiến bộ tham mưu liên quân"),
    (1528, "J-4 (logistics directorate of a joint staff)", "cục hậu cần bộ tham mưu liên quân"),
    (1528, "J-5 (plans directorate of a joint staff)", "cục kế hoạch bộ tham mưu liên quân"),
    (1528, "J-6 (command, control, communications, and computer systems directorate of a joint staff)", "cục về các hệ thống chỉ huy, kiểm soát thông tin liên lạc và máy tính bộ tham mưu liên quân"),
    (1528, "J-7 (Operational Plans and Joint Force Development Directorate, Joint Staff)", "cục kế hoạch tác chiến và phát triển lực lượng bộ tham mưu liên quân"),
    (1528, "J-8 (Director for Force Structure, Resource, and Assessment, Joint Staff)", "cục về cơ cấu lực lượng, nguồn lực và đánh giá bộ tham mưu liên quân"),
    (1528, "JA (judge advocate)", "thẩm phán; cố vấn pháp luật"),
    (1528, "JA/ATT (joint airborne/ air transportability training)", "huấn luyện cơ động đường không/ khả năng vận tải đường không liên quân"),

    # ---------------- 1529 (idx0764) ----------------
    (1529, "JAAF (Japanese Army Air Force)", "lực lượng không quân Nhật Bản, không quân Nhật Bản"),
    (1529, "JAAP (joint airborne advance party)", "đội tiền trạm cơ động đường không liên quân"),
    (1529, "JAAR (joint after-action report)", "báo cáo kết quả tác chiến liên quân"),
    (1529, "JAARS (joint after-action reporting system)", "hệ thống báo cáo kết quả tác chiến liên quân"),
    (1529, "JAAT (joint air attack team)", "đội tiến công đường không liên quân"),
    (1529, "JAATT (joint air attack team tactics)", "chiến thuật không kích tập thể của liên quân"),
    (1529, "JAC (joint analysis center)", "trung tâm phân tích kết quả tác chiến liên quân"),
    (1529, "JACC (joint airspace control center)", "trung tâm kiểm soát không gian vũ trụ liên quân"),
    (1529, "JACC/CP (joint airborne communications center/ command post)", "trung tâm thông tin liên lạc cơ động đường không của sở chỉ huy liên quân"),
    (1529, "JACCC (joint airlift coordination and control cell)", "bộ phận hiệp đồng và kiểm soát cầu hàng không liên quân"),
    (1529, "JACO (Joint Actions Control Office)", "phòng chỉ huy những hoạt động phối hợp; cơ quan kiểm soát hoạt động phối hợp"),
    (1529, "JADO (joint air defense operations)", "tác chiến phòng không liên quân"),
    (1529, "JADOC (Joint Air Defense Operation Center)", "trung tâm chỉ huy phòng không liên quân"),
    (1529, "JAG (Judge Advocate General)", "chánh án toà án quân sự"),
    (1529, "JAGC (Judge Advocate General's Corps)", "ngành toà án quân sự"),
    (1529, "JAI (joint administrative instruction)", "chỉ thị về hoạt động hành chính quản trị liên quân"),
    (1529, "JAI (joint airdrop inspection)", "sự thanh tra hoạt động đổ bộ đường không liên quân"),
    (1529, "JAIC (joint air intelligence center)", "trung tâm tình báo đường không liên quân; trung tâm trinh sát đường không liên quân"),
    (1529, "JAIEG (Joint Atomic Information Exchange Group)", "nhóm trao đổi thông tin về các vấn đề hạt nhân của liên quân"),
    (1529, "JAMAG (Joint American Military Advisory Group)", "nhóm cố vấn quân sự Mỹ của liên quân"),
    (1529, "JAMPO (Joint Allied Military Petroleum Office)", "cơ quan cung cấp dầu mỡ của lực lượng liên quân"),
    (1529, "JAMPS (Joint Interoperability of Tactical Command and Control Systems (JINTACCS) automated message preparation system)", "hệ thống soạn thảo điện văn tự động thuộc các hệ thống chỉ huy và kiểm soát phối hợp tác chiến liên quân"),
    (1529, "JAN (joint army-navy)", "lục quân và hải quân hợp nhất, sự thống nhất đối với lực lượng lục quân và hải quân"),
    (1529, "JANAF (Joint Army-Navy Air Force)", "không quân của lực lượng lục quân và hải quân hợp nhất"),
    (1529, "JANAP (Joint Army-Navy-Air Force Publication)", "xuất bản phẩm của liên quân hải - lục - không quân"),
    (1529, "JANAST (Joint Army-Navy-Air Force Sea Transport)", "vận tải biển của liên quân hải - lục - không quân"),
    (1529, "JANB (Joint Army and Navy Board)", "hội đồng liên quân lục quân và hải quân"),
    (1529, "JANPC (Joint Army and Navy Planning Committee)", "uỷ ban liên quân về lập kế hoạch hiệp đồng tác chiến giữa lục quân và hải quân"),
    (1529, "JAO (joint air operations)", "tác chiến đường không liên quân; tác chiến không quân quân chủng hợp thành"),

    # ---------------- 1530 (idx0765) ----------------
    (1530, "JAOC (Joint Air Operation Center)", "trung tâm chỉ huy hoạt động của không quân liên quân"),
    (1530, "JAPC (Joint Air Photo Center)", "trung tâm ảnh hàng không liên quân, trung tâm không ảnh liên quân"),
    (1530, "JAPO (joint area petroleum office)", "phòng xăng dầu khu vực liên quân"),
    (1530, "JAR (joint activity report)", "sự báo cáo hoạt động của liên quân"),
    (1530, "JAR (Joint Airworthiness Requirements)", "các yêu cầu khả phi liên kết (do tất cả các nước chủ yếu thuộc khối cộng đồng chung châu Âu thoả thuận)"),
    (1530, "JARCC (joint air reconnaissance control center)", "trung tâm chỉ huy trinh sát đường không liên quân"),
    (1530, "JARS (joint automated readiness system)", "hệ thống sẵn sàng chiến đấu tự động hoá liên quân"),
    (1530, "JASC (joint action steering committee)", "uỷ ban chỉ đạo hoạt động liên quân"),
    (1530, "JASDF (Japan Air Self-Defence Force)", "lực lượng phòng vệ đường không Nhật Bản"),
    (1530, "JASSM (Joint Air-to-surface Standoff Missile)", "tên lửa không đối mặt (đất, biển) dự phòng liên quân"),
    (1530, "JAT (joint acceptance test)", "sự thử nghiệm (để) phê chuẩn liên quân"),
    (1530, "JATACS (joint advanced tactical cryptological support)", "sự bảo đảm mật mã chiến thuật tiên tiến liên quân"),
    (1530, "JATF (joint amphibious task force)", "lực lượng đặc nhiệm lội nước đổ bộ liên quân"),
    (1530, "JATO (jet-assisted take-off)", "cất cánh có sự trợ giúp của tên lửa đẩy, cất cánh bằng động cơ phản lực đẩy hỗ trợ"),
    (1530, "JAWS (jamming and warning system)", "hệ thống gây nhiễu và báo động"),
    (1530, "JAWS (joint attack weapon system (Mỹ))", "tổ hợp vũ khí tiến công liên quân"),
    (1530, "jb (jet bomb)", "bom phản lực"),
    (1530, "JB (junction box)", "cái chuyển mạch; tổng đài"),
    (1530, "JBP (Joint Blood Program)", "chương trình máu liên quân"),
    (1530, "JBPO (Joint Blood Program Office)", "văn phòng chương trình máu liên quân"),
    (1530, "Jc (junction)", "chỗ nối lại; điểm giao cắt, ngã đường"),
    (1530, "JC2WC (joint command and control warfare center)", "trung tâm chiến tranh chỉ huy và kiểm soát liên quân, trung tâm tác chiến chỉ huy và kiểm soát liên quân"),
    (1530, "JCA (Joint Communications Agency)", "cục thông tin liên lạc liên quân"),
    (1530, "JCAB (Japan Civil Airworthiness Board)", "hội đồng khả phi dân dụng Nhật Bản"),
    (1530, "JCAE (Joint Committee for Atomic Energy)", "uỷ ban liên quân về năng lượng hạt nhân"),
    (1530, "JCASREP (joint casualty report)", "sự báo cáo thương vong của liên quân, báo cáo tổn thất của liên quân"),
    (1530, "JCAT (joint crisis action team)", "lực lượng hành động liên quân đối phó với khủng hoảng"),
    (1530, "JCC (joint command center)", "trung tâm chỉ huy liên quân"),
    (1530, "JCC (joint communication center)", "trung tâm thông tin liên lạc liên quân"),
    (1530, "JCCB (Joint Configuration Control Board)", "hội đồng kiểm soát cấu hình liên quân"),
    (1530, "JCCC (joint combat camera center)", "trung tâm camêra tác chiến liên quân"),
    (1530, "JCCC (joint communications control center)", "trung tâm kiểm soát thông tin liên lạc liên quân"),
    (1530, "JCCP (joint casualty collection point)", "điểm tập kết quân số thương vong của liên quân"),
    (1530, "JCEOI (joint communications - electronics operating instructions)", "hướng dẫn vận hành thông tin liên lạc - điện tử liên quân"),
    (1530, "JCET (joint combined exercise for training)", "diễn tập huấn luyện binh chủng hợp thành"),

    # ---------------- 1531 (idx0766) ----------------
    (1531, "JCEWS (joint force commander's electronic warfare staff)", "ban tham mưu tác chiến điện tử của tư lệnh (trưởng) lực lượng liên quân"),
    (1531, "JCGRO (joint central graves registration office)", "phòng đăng ký mộ chí trung ương liên quân"),
    (1531, "JCI (Joint Communications Instruction)", "bản hướng dẫn phối hợp thông tin liên lạc"),
    (1531, "JCIDO (Joint Combat Identification Office)", "phòng nhận dạng chiến đấu liên quân"),
    (1531, "JCIOC (joint counterintelligence operations center)", "trung tâm tác chiến phản tình báo liên quân"),
    (1531, "JCISB (Joint Counterintelligence Support Branch)", "ngành chi viện phản tình báo liên quân"),
    (1531, "JCLL (joint center for lessons learned)", "trung tâm nghiên cứu rút kinh nghiệm chiến đấu liên quân"),
    (1531, "JCMA (joint communications security (COMSEC) monitor activity)", "hoạt động giám sát an ninh thông tin liên lạc liên quân"),
    (1531, "JCMC (joint crisis management capability)", "khả năng quản lý giải quyết khủng hoảng liên quân"),
    (1531, "JCMEB (joint civil-military engineering board)", "hội đồng công trình quân - dân sự liên quân"),
    (1531, "JCMEC (joint captured materiel exploitation center)", "trung tâm khai thác sử dụng các trang bị vũ khí thu được của địch của liên quân"),
    (1531, "JCMOTF (joint civil-military operations task force)", "lực lượng đặc nhiệm hoạt động quân - dân sự liên quân"),
    (1531, "JCMPO (Joint Cruise Missile Project Office)", "văn phòng dự án tên lửa hành trình liên quân"),
    (1531, "JCMT (joint collection management tools)", "công cụ quản lý thu thập tin tức liên quân"),
    (1531, "JCN (joint communications network)", "mạng thông tin liên lạc liên quân"),
    (1531, "JCS (Joint Chiefs of Staff (Mỹ))", "hội đồng tham mưu trưởng liên quân"),
    (1531, "JCSAN (Joint Chiefs of Staff Alerting Network)", "hệ thống thông tin liên lạc báo động của hội đồng tham mưu trưởng liên quân, mạng thông tin liên lạc cảnh báo của hội đồng tham mưu trưởng liên quân"),
    (1531, "JCSAR (joint combat search and rescue)", "tìm kiếm và giải cứu chiến đấu liên quân"),
    (1531, "JCSC (joint communications satellite center)", "trung tâm vệ tinh thông tin liên lạc liên quân"),
    (1531, "JCSE (joint communications support element)", "phân đội bảo đảm thông tin liên lạc liên quân"),
    (1531, "JCSM (Joint Chiefs of Staff memorandum)", "bản ghi nhớ của hội đồng tham mưu trưởng liên quân"),
    (1531, "JCSS (joint communications support squadron)", "phi đội không quân bảo đảm thông tin liên lạc liên quân"),
    (1531, "JCTN (joint composite track network)", "mạng bám mục tiêu hỗn hợp của liên quân"),
    (1531, "jd (joined)", "được nối lại, nối liền; liên quân, kết hợp; nhập vào"),
    (1531, "JDA (Japan Defence Agency)", "cục phòng vệ Nhật Bản"),
    (1531, "JDA (joint duty assignment)", "sự giao nhiệm vụ liên quân"),
    (1531, "JDAL (Joint Duty Assignment List)", "danh sách giao nhiệm vụ liên quân"),
    (1531, "JDAM (joint direct attack munitions)", "đạn dược tiến công trực tiếp của liên quân (có độ chính xác cao, được điều khiển thông qua hệ thống định vị toàn cầu)"),
    (1531, "JDAMIS (Joint Duty Assignment management Information System)", "hệ thống thông tin về quản lý giao nhiệm vụ liên quân"),
    (1531, "JDC (joint deployment community)", "cộng đồng triển khai liên quân"),

    # ---------------- 1532 (idx0767) ----------------
    (1532, "JDC (Joint Doctrine Center)", "trung tâm học thuyết tác chiến liên quân"),
    (1532, "JDEC (joint document exploitation center)", "trung tâm khai thác tài liệu liên quân"),
    (1532, "JDIG (Joint Drug Intelligence Group)", "cụm tình báo chống ma tuý liên quân"),
    (1532, "JDISS (joint deployable intelligence support system)", "hệ thống bảo đảm tình báo phục vụ triển khai liên quân"),
    (1532, "JDN (joint data network)", "mạng dữ liệu liên quân"),
    (1532, "JDSS (Joint Decision Support System)", "hệ thống bảo đảm hạ quyết tâm liên quân"),
    (1532, "JDSSC (Joint Data Systems Support Center)", "trung tâm hỗ trợ các hệ thống dữ liệu liên quân"),
    (1532, "JDST (joint decision support tools)", "công cụ bảo đảm hạ quyết tâm chiến đấu liên quân"),
    (1532, "JDTC (joint deployment training center)", "trung tâm huấn luyện triển khai liên quân"),
    (1532, "JDWP (Joint Doctrine Working Party)", "tổ soạn thảo các nguyên tắc tác chiến cơ bản liên quân"),
    (1532, "JEAP (Joint Electronic Intelligence (ELINT) Analysis Program)", "chương trình phân tích tin tức tình báo điện tử liên quân"),
    (1532, "JECG (joint exercise control group)", "nhóm điều khiển diễn tập liên quân"),
    (1532, "JECPO (joint electronic commerce program office)", "văn phòng chương trình thương mại điện tử liên quân"),
    (1532, "JEEP (Joint Emergency Evacuation Plan)", "kế hoạch sơ tán khẩn cấp liên quân"),
    (1532, "JEL (Joint Electronic Library)", "thư viện điện tử liên quân"),
    (1532, "JEM (joint exercise manual)", "sổ tay diễn tập liên quân"),
    (1532, "JEMP (joint exercise management package)", "bộ tài liệu quản lý diễn tập liên quân"),
    (1532, "JEOCN (Joint European Operational Communications Network)", "mạng thông tin liên lạc tác chiến châu Âu thống nhất"),
    (1532, "JEPES (Joint Engineer Planning and Execution System)", "hệ thống lập kế hoạch và thực hành công binh công trình liên quân"),
    (1532, "JEPS (joint exercise planning staff)", "bộ tham mưu lập kế hoạch huấn luyện liên quân"),
    (1532, "JET (Joint Operation Planning and Execution System (JOPES) editing tool)", "công cụ biên tập xuất bản của hệ thống lập kế hoạch và thực hành tác chiến liên quân"),
    (1532, "JETP (jet propelled)", "(thuộc) tên lửa; có động cơ tên lửa; đẩy bằng phản lực"),
    (1532, "JEWC (Joint Electronic Warfare Center)", "trung tâm chiến tranh điện tử liên quân; trung tâm tác chiến điện tử liên quân"),
    (1532, "JEZ (joint engagement zone)", "khu vực giao chiến liên quân"),
    (1532, "JFA (joint field activity)", "hoạt động dã ngoại liên quân"),
    (1532, "JFACC (joint force air component commander)", "tư lệnh (trưởng) thành phần không quân trong lực lượng hợp thành liên quân"),
    (1532, "JFAST (joint flow and analysis system for transportation)", "hệ thống nguồn cung cấp và phân tích vận tải liên quân"),
    (1532, "JFC (joint force commander)", "tư lệnh (trưởng) lực lượng liên quân"),
    (1532, "JFCOM (Joint Force Command)", "bộ tư lệnh lực lượng liên quân"),
    (1532, "JFE (joint fires element)", "thành phần hoả lực liên quân"),
    (1532, "JFHQ (joint forces headquarters)", "sở chỉ huy lực lượng liên quân, trụ sở bộ chỉ huy lực lượng quân chủng hợp thành"),
    (1532, "JFLCC (joint force land component commander)", "tư lệnh (trưởng) thành phần lục quân trong lực lượng liên quân"),
    (1532, "JFMCC (joint force maritime component commander)", "tư lệnh (trưởng) thành phần hải quân trong lực lượng liên quân"),
]


def main():
    out_path = "docs/db/import/tudien_abbr_chunks/chunk_0753_0767.csv"
    fieldnames = [
        "source_page", "dictionary_name", "word", "phonetic",
        "part_of_speech_raw", "part_of_speech_code", "meaning_vi",
        "is_subentry", "example_en", "example_vi", "image_path", "reviewed",
    ]
    with open(out_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for page, word, meaning in ENTRIES:
            writer.writerow({
                "source_page": page,
                "dictionary_name": "Military Dictionary",
                "word": word,
                "phonetic": "",
                "part_of_speech_raw": "",
                "part_of_speech_code": "",
                "meaning_vi": meaning,
                "is_subentry": "FALSE",
                "example_en": "",
                "example_vi": "",
                "image_path": f"img_{page}.jpg",
                "reviewed": "FALSE",
            })
    print(f"Wrote {len(ENTRIES)} entries to {out_path}")


if __name__ == "__main__":
    main()
