"""Sinh pilot_tudien_vision_abbr.csv tu du lieu doc truc tiep bang vision (KHONG
qua OCR) tren 10 trang dau muc Viet tat cua Tu_dien.pdf (PDF idx 598-607,
trang in 1363-1372). Doi chieu voi Tu_dien.csv (phien lam viec khac tao ra,
bao phu trang 764-1344) cho thay huong doc anh truc tiep chinh xac hon han
Tesseract OCR (xem ocr_pilot_tudien_bold.py) - vd trang 823 khop 100% dau
tieng Viet trong khi OCR sai rai rac. Script nay ap dung cach lam tuong tu
cho doan tiep theo (muc Viet tat) ma Tu_dien.csv chua bao phu.

Quy uoc cot "word": "VIET_TAT (dang day du tieng Anh)" - gop chung theo y
nguoi dung (viet tat tieng Anh thi de thang vao truong tu tieng Anh, khong
tach rieng cot abbr/expansion) nhung van giu dang day du de phan biet cac
muc dung chung 1 viet tat (vd AFC xuat hien 4 lan voi 4 nghia khac nhau).

is_subentry = FALSE cho tat ca: khac voi phan tu dien A-Z chinh (dung "~" the
cho headword trang, vd "mobile"), muc trong phan viet tat KHONG chia se
headword goc - moi muc doc lap.

DAY LA BAN NHAP DE NGUOI DUNG DOI CHIEU TAY (chua sua/doan lai OCR/in loi
cua nguyen ban, vd "AFSOUTH ... Southern Europe ... Bac Au" giu nguyen nhu
sach in du co ve mau thuan Southern/Bac).
"""

from __future__ import annotations

import csv

DICTIONARY_NAME = "Military Dictionary"

# (printed_page, [(word, meaning_vi), ...])
PAGES: list[tuple[int, list[tuple[str, str]]]] = [
    (1363, [
        ("aero sct plat (aeroscout platoon)", "trung đội trinh sát đường không"),
        ("AEROFLOT (Aero Flotilla, Soviet Air Lines)", "(Nga) hãng hàng không Liên Xô (cũ)"),
        ("aeromed (aeromedical)", "chuyển thương đường không"),
        ("AES (aeromedical evacuation squadron)", "phi đội chuyển thương đường không"),
        ("AES (aeromedical evacuation system)", "hệ thống chuyển thương đường không"),
        ("AETC (Air Education and Training Command)", "bộ chỉ huy huấn luyện và đào tạo không quân"),
        ("AETF (air and space expeditionary task force)", "cụm không quân chiến dịch (lâm thời) viễn chinh không gian và vũ trụ, lực lượng đặc nhiệm viễn chinh hàng không vũ trụ"),
        ("AEU (assign essential user bypass)", "xác định đường vòng tránh cho các đơn vị quan trọng"),
        ("AEV (armored engineer vehicle)", "xe công binh công trình bọc thép"),
        ("AEW (air expeditionary wing)", "phi đoàn không quân viễn chinh"),
        ("AEW (airborne early warning)", "sự phát hiện từ xa bằng trạm báo động trên không; sự cảnh báo sớm máy bay địch; sự cảnh báo sớm đường không"),
        ("AEW&C (airborne early warning and control)", "(máy bay) kiểm soát và cảnh báo sớm đường không"),
        ("AEWS (advanced earth satellite weapons system)", "hệ thống vũ khí vệ tinh trái đất cải tiến"),
        ("a-f (audio-frequency)", "âm tần"),
        ("AF (Air Force)", "không quân, lực lượng không quân"),
        ("AF (amphibious force)", "lực lượng tác chiến thủy bộ, lực lượng đổ bộ đường biển"),
        ("AF (Army form)", "mẫu văn kiện cho lục quân"),
        ("AF HQ (air force headquarters)", "bộ chỉ huy không quân, sở chỉ huy không quân"),
        ("AF HQ (Allied Forces Headquarters)", "bộ chỉ huy quân đồng minh, sở chỉ huy liên quân"),
        ("AF Res (Air Force Reserve)", "lực lượng dự bị không quân"),
        ("AF/DP (Deputy Chief of Staff for Personnel, United States Air Force)", "phó tham mưu trưởng về quân lực của không quân Mỹ"),
        ("AF/IL (Deputy Chief of Staff for Installations and Logistics, USAF)", "phó tham mưu trưởng về hậu cần và kho tàng của không quân Mỹ"),
        ("AF/XO (Deputy Chief of Staff for Plans and Operations, United States Air Force)", "phó tham mưu trưởng về kế hoạch và tác chiến của không quân Mỹ"),
        ("AF/XOI (Air Force Director of Intelligence, Surveillance, and Reconnaissance)", "tổng cục trưởng tổng cục tình báo, do thám và trinh sát của không quân Mỹ"),
        ("AF/XOO (Director of Operations, United States Air Force)", "cục trưởng cục tác chiến của không quân Mỹ"),
        ("afa (audio-frequency amplifier)", "máy khuếch đại âm tần"),
        ("AFAARS (Air Force After Action Reporting System)", "hệ thống báo cáo kết quả hoạt động của không quân"),
        ("AFAFC (Air Force Accounting and Finance Center)", "trung tâm thống kê và tài chính không quân"),
        ("AFAITC (Armed Forces Air Intelligence Training Center)", "trung tâm huấn luyện tình báo đường không của quân đội"),
        ("AFAK (Armed Forces assistance in Korea)", "sự giúp đỡ từ phía lực lượng vũ trang ở Triều Tiên"),
        ("AFAP (artillery-fired atomic projectile)", "đạn pháo nguyên tử"),
        ("AFARN (Air Force air request net)", "mạng thông tin yêu cầu không quân chi viện"),
        ("AFAS (Advanced Field Artillery System)", "hệ thống pháo binh dã chiến tiên tiến; tổ hợp pháo binh dã chiến cải tiến"),
    ]),
    (1364, [
        ("AFASE (Association for Applied Solar Energy)", "hội ứng dụng năng lượng mặt trời"),
        ("AFATDS (Advanced Field Artillery Tactical Data System)", "hệ thống dữ liệu chiến thuật pháo binh dã chiến cải tiến"),
        ("AFB (Air Force base, USA)", "căn cứ không quân (Mỹ)"),
        ("AFBM (Air Force ballistic missile)", "tên lửa đạn đạo không quân"),
        ("AFBMC (Air Force Ballistic Missile Center)", "trung tâm tên lửa đạn đạo không quân"),
        ("AFBMC (Air Force Ballistic Missile Committee)", "uỷ ban tên lửa đạn đạo không quân"),
        ("AFBMD (Air Force Ballistic Missile Division)", "cục tên lửa đạn đạo không quân"),
        ("AFBMTC (Air Force Ballistic Missile Training Center)", "trung tâm huấn luyện tên lửa đạn đạo không quân"),
        ("AFBSD (Air Force Ballistic Systems Division)", "cục hệ thống tên lửa đạn đạo không quân"),
        ("AFC (area frequency coordinator)", "sĩ quan phối hợp tần số (thông tin liên lạc) khu vực"),
        ("AFC (army field code)", "(mật) mã dã chiến"),
        ("AFC (army finance center)", "trung tâm tài chính quân đội"),
        ("AFC (automatic frequency control)", "sự điều chỉnh tần số tự động; sự kiểm soát tần số tự động"),
        ("AFCA (Air Force Communications agency)", "cục thông tin liên lạc không quân"),
        ("AFCA (Armed Forces contract augmentation program)", "chương trình hợp đồng tăng cường lực lượng vũ trang"),
        ("AFCAP (Air Force contract augmentation Program)", "chương trình hợp đồng nâng cấp không quân"),
        ("AFCC (air force combat command)", "bộ tư lệnh không quân chiến đấu"),
        ("AFCC (Air Force Communications Center)", "trung tâm thông tin liên lạc không quân"),
        ("AFCC (Air Force Component Commander)", "tư lệnh (trưởng) không quân thành phần hợp thành lực lượng liên quân"),
        ("AFCent; AFCENT (Allied Forces, Central Europe, NATO)", "lực lượng liên quân (NATO) ở Trung Âu"),
        ("AFCERT (Air Force computer emergency response team)", "đội phản ứng nhanh với tình trạng máy tính không quân"),
        ("AFCS (Air Force Communications Service)", "ngành thông tin liên lạc không quân"),
        ("AFCS (artillery fire-control system)", "hệ thống chỉ huy hoả lực pháo binh"),
        ("AFCS (Automatic Fire-Control Systems)", "các hệ thống chỉ huy hoả lực tự động; tổ hợp thiết bị tự động điều khiển hoả lực"),
        ("AFCS (automatic flight control system)", "hệ thống điều khiển bay tự động, hệ thống tự động kiểm soát bay"),
        ("AFD (army field depot)", "kho dã chiến lục quân"),
        ("AFD (automatic feeding device)", "thiết bị tự động nạp đạn, cơ cấu nạp đạn tự động; thiết bị cung cấp nhiên liệu tự động"),
        ("AFDB (floating dry dock)", "xưởng sửa chữa tàu chiến nổi"),
        ("AFDC (Air Force Doctrine Center)", "trung tâm phát triển học thuyết không quân; trung tâm nghiên cứu những nguyên tắc cơ bản về sử dụng không quân"),
        ("AFDIGS (Air Force digital graphics system)", "hệ thống đồ hoạ kỹ thuật số của không quân"),
        ("AFEES (Armed Forces Examining and Entrance Station)", "trạm khám sức khoẻ và tuyển quân của lực lượng vũ trang"),
        ("AFEM (Armed Forces Expeditionary Medal)", "huy chương “Vì phục vụ trong lực lượng viễn chinh”"),
        ("AFETR (Air Force Eastern Test Range)", "trường bắn thử Phương Đông của không quân"),
        ("AFF (army field forces)", "lực lượng lục quân dã chiến"),
    ]),
    (1365, [
        ("AFFE (Air Force, Far East)", "lực lượng không quân khu vực Viễn Đông"),
        ("AFFE (Allied Forces, Far East)", "lực lượng đồng minh khu vực Viễn Đông"),
        ("AFFIS (Air Facilities File Information System)", "hệ thống thông tin hồ sơ về các phương tiện bảo đảm của không quân"),
        ("AFFMA (Air Force Frequency Management Agency)", "cơ quan điều hành tần số của không quân"),
        ("AFFOR (Air Force forces)", "các lực lượng của không quân"),
        ("AFG (anti-frogman grenade)", "lựu đạn chống người nhái"),
        ("AFIC (Air Force Intelligence Center)", "trung tâm tình báo không quân"),
        ("AFID (anti-fratricide identification device)", "dụng cụ nhận dạng chống sát thương quân mình"),
        ("AFIRB (Armed Forces Identification Review Board)", "phòng nghiên cứu về nhận dạng của lực lượng vũ trang"),
        ("AFIT (Air Force Institute of Technology)", "viện công nghệ không quân"),
        ("AFIWC (Air Force Information Warfare Center)", "trung tâm tác chiến tin học của không quân"),
        ("AFJMAN (Air Force Joint Manual)", "điều lệnh liên quân của không quân"),
        ("AFL (Aeroflot, Soviet Air Lines)", "(Nga) hãng hàng không Liên Xô"),
        ("AFLANT (Air Forces, Atlantic Command)", "bộ chỉ huy không quân Mỹ ở Đại Tây Dương"),
        ("AFLC (Air Force Logistic Command)", "bộ chỉ huy bảo đảm trang bị kỹ thuật không quân, bộ tư lệnh hậu cần không quân"),
        ("afld (airfield)", "sân bay"),
        ("AFLE (Air Force Liaison Element)", "phân đội thông tin liên lạc (hiệp đồng) của không quân"),
        ("AFLNO (Air Force liaison officer)", "sĩ quan thông tin liên lạc (hiệp đồng) của không quân"),
        ("AFM (Air Force Manual)", "điều lệnh không quân"),
        ("AFMAN (Air Force Manual)", "điều lệnh không quân"),
        ("AFMC (Air Force Materiel Command)", "bộ tư lệnh vật chất và khí tài không quân; bộ tư lệnh bảo đảm trang bị kỹ thuật không quân"),
        ("AFMD (Air Force Missile Division)", "sư đoàn tên lửa có điều khiển của lực lượng không quân"),
        ("AFMDC (Air Force Missile Development Center)", "trung tâm nghiên cứu cải tiến tên lửa không quân"),
        ("AFME (Armed Forces medical examiner)", "bác sĩ khám sức khoẻ của lực lượng vũ trang"),
        ("AFMED (Allied Forces, Mediterranean)", "lực lượng liên quân NATO khu vực Địa Trung Hải"),
        ("AFMIC (Armed Forces Medical Intelligence Center)", "trung tâm tình báo y học của lực lượng vũ trang"),
        ("AFMLO (Air Force Medical Logistics Office)", "phòng hậu cần quân y không quân"),
        ("AFMS (Air Force Medical Service)", "ngành quân y không quân"),
        ("AFMS (automatic flight management system)", "hệ thống quản lý bay tự động; hệ thống tự động quản lí bay"),
        ("AFMTC (Air Force Missile Test Center)", "trung tâm thử nghiệm tên lửa không quân"),
        ("AFN (American Forces Network, in Europe)", "mạng liên lạc vô tuyến của quân Mỹ (ở châu Âu)"),
        ("AFNE (Allied Forces, Northern Europe)", "lực lượng liên quân NATO khu vực Bắc Âu"),
        ("AFNORTH (Allied Forces, Northern Europe)", "lực lượng liên quân NATO khu vực Bắc Âu"),
        ("AFNSEP (Air Force National Security and Emergency Preparedness Agency)", "cơ quan chuẩn bị sẵn sàng cho tình trạng khẩn cấp và an ninh quốc gia của không quân"),
    ]),
    (1366, [
        ("AFOAT (Air Force Office for Atomic Energy)", "cơ quan năng lượng nguyên tử của không quân"),
        ("AFOE (assault follow-on echelon)", "thê đội xung phong tiếp theo (thê đội 2 trong tiến công)"),
        ("AFOSI (Air Force Office of Special Investigations)", "phòng điều tra đặc biệt của không quân"),
        ("AFOSR (Air Force Office of Scientific Research)", "cơ quan nghiên cứu khoa học của không quân"),
        ("AFP (Armed Forces Police)", "quân cảnh, hiến binh, cảnh sát quân sự"),
        ("AFP (assault fire platoon)", "trung đội hoả lực xung kích"),
        ("AFPAM (Air Force pamphlet)", "sổ tay thông tin về không quân"),
        ("AFPC (Air Force Personnel Center)", "trung tâm quân lực không quân"),
        ("AFPD (Air Force Policy Directive)", "chỉ thị (chỉ lệnh) về chính sách của không quân"),
        ("AFPD (Armed Forces Police Detachment)", "đội cảnh sát quân sự, đội quân cảnh"),
        ("AFPEO (Armed Forces Professional Entertainment Overseas)", "chương trình giải trí nghiệp vụ của lực lượng vũ trang ở hải ngoại"),
        ("AFPS (Armed Forces Press Service)", "ngành báo chí của lực lượng vũ trang"),
        ("AFR (Air Force Regulation)", "điều lệnh không quân"),
        ("AFR (Air Force Reserve)", "lực lượng dự bị không quân"),
        ("AFR (assign frequency for networking)", "sự phân bố tần số lập mạng thông tin liên lạc"),
        ("AFRC (Air Force Reserve Command)", "bộ tư lệnh lực lượng dự bị không quân"),
        ("AFRC (Armed Forces Recreation Center)", "trung tâm giải trí của lực lượng vũ trang"),
        ("AFRCC (Air Force rescue coordination center)", "trung tâm hiệp đồng giải cứu của không quân"),
        ("AFRM (Armed Forces Reserve Medal)", "huy chương quân dự bị"),
        ("AFROTC (Air Force Reserve Officer's Training Corps)", "cục huấn luyện sĩ quan dự bị không quân"),
        ("AFRRI (Armed Forces Radiobiology Research Institute)", "viện nghiên cứu sinh học và phóng xạ của lực lượng vũ trang"),
        ("AFRTS (Armed Forces Radio and Television Service)", "ngành phát thanh và truyền hình lực lượng vũ trang"),
        ("AFS (Air Force speciality)", "chuyên ngành không quân"),
        ("AFS (automatic flight system)", "hệ thống điều khiển bay tự động, hệ thống tự động điều khiển bay"),
        ("AFSATCOM (Air Force satellite communications)", "mạng thông tin liên lạc vệ tinh của không quân, phương tiện thông tin liên lạc vệ tinh của không quân"),
        ("AFSC (Air Force Systems Command)", "bộ chỉ huy hệ thống của không quân, bộ tư lệnh hệ thống của không quân"),
        ("AFSC (Armed Forces Staff College)", "trường sĩ quan tham mưu của lực lượng vũ trang"),
        ("AFSC (United States Air Force specialty code)", "mã đặc biệt của không quân Mỹ"),
        ("AFSN (Air Force Service Number)", "số hiệu quân nhân không quân"),
        ("AFSOB (Air Force special operations base)", "căn cứ tác chiến đặc biệt của không quân"),
        ("AFSOC (Air Force Special Operations Command)", "bộ chỉ huy tác chiến đặc biệt của không quân"),
        ("AFSOC (Air Force special operations component)", "thành phần tác chiến đặc biệt không quân (trong lực lượng hợp thành)"),
        ("AFSOCC (Air Force special operations control center)", "trung tâm chỉ huy tác chiến đặc biệt của không quân"),
    ]),
    (1367, [
        ("AFSOD (Air Force special operations detachment)", "đội biệt phái của lực lượng tác chiến đặc biệt không quân"),
        ("AFSOE (Air Force special operations element)", "phân đội tác chiến đặc biệt của không quân; thành phần tác chiến đặc biệt của không quân"),
        ("AFSOF (Air Force special operations forces)", "các lực lượng tác chiến đặc biệt của không quân"),
        ("AFSOUTH (Allied Forces, Southern Europe)", "lực lượng đồng minh khu vực Bắc Âu, lực lượng liên quân NATO khu vực Bắc Âu"),
        ("AFSPACE (United States Space Command Air Force)", "không quân thuộc bộ chỉ huy vũ trụ Mỹ"),
        ("AFSPC (Air Force Space Command, Mỹ)", "bộ chỉ huy vũ trụ của không quân"),
        ("AFSPOC (Air Force Space Operations Center, Mỹ)", "trung tâm chỉ huy tác chiến trên vũ trụ của không quân"),
        ("AFSSC (Armed Forces Supply Support Center)", "trung tâm bảo đảm hậu cần của lực lượng vũ trang"),
        ("AFSTC (Air Force Space Test Center)", "trung tâm thử nghiệm vũ trụ của không quân"),
        ("AFSV (Armoured Fire Support Vehicle)", "xe bọc thép chi viện hoả lực, xe thiết giáp chi viện hoả lực"),
        ("AFSWA (Armed Forces Special Weapons Agency)", "cục vũ khí đặc biệt của quân đội"),
        ("AFSWC (Air Force Special Weapons Center)", "trung tâm vũ khí đặc biệt của không quân"),
        ("AFV (armored fighting vehicle)", "xe chiến đấu bọc thép"),
        ("AFTAC (Air Force Technical Applications Center)", "trung tâm ứng dụng kỹ thuật của không quân"),
        ("AFTE (afterburning)", "sự cháy dư; sự đốt tăng lực (trong động cơ phản lực quạt nén hoặc động cơ tua bin phản lực)"),
        ("AFTH (Air Force Theater Hospital)", "quân y viện chiến trường của không quân"),
        ("AFTN (Aeronautical Fixed Telecommunications Network)", "mạng thông tin liên lạc viễn thông hàng không"),
        ("AFTO (Air Force technical order)", "mệnh lệnh về công tác kỹ thuật của không quân"),
        ("AFUS (Air force-United States)", "không lực Hoa Kỳ, không quân Mỹ"),
        ("AFV (Armored Family of Vehicle, US)", "hệ xe bọc thép (Mỹ), họ xe chiến đấu bọc thép (Mỹ)"),
        ("AFV (armored fighting vehicle)", "xe chiến đấu bọc thép"),
        ("AFW (Air Force wing)", "phi đội không quân; không đoàn; liên đoàn không quân"),
        ("AFWAR (Air Force personnel on duty with Army)", "các đơn vị không quân tăng cường cho lục quân; lính không quân bổ sung cho lục quân"),
        ("AFWCF (Air Force working capital fund)", "ngân sách cơ bản cho hoạt động của không quân"),
        ("AFWL (Air Force Weapons Laboratory)", "phòng thí nghiệm vũ khí không quân"),
        ("AFWN (Air Force with the Navy)", "các đơn vị không quân bổ sung cho hải quân"),
        ("AFWOFS (Air Force Weather Observing and Forecasting System)", "hệ thống quan sát và dự báo thời tiết của không quân"),
        ("AFWS (Air Force weapon system)", "hệ thống vũ khí không quân"),
        ("AFWTR (Air Force Western Test Range)", "trường bắn thử nghiệm miền Tây của lực lượng không quân"),
        ("AG (Adjutant General)", "chủ nhiệm quản lý hành chính (từ cấp sư đoàn trở lên)"),
        ("AG (advanced guard)", "lực lượng tiền vệ; đội cảnh giới phía trước"),
        ("AG (air gunner)", "xạ thủ trên máy bay, pháo thủ trên máy bay"),
        ("AG (air-to-ground)", "không đối đất"),
        ("a-g (anti-gas)", "phòng chống hơi độc"),
        ("AG (assault gun)", "pháo công phá; pháo tự hành; bệ pháo tự hành"),
    ]),
    (1368, [
        ("AG (assistance gunner)", "pháo thủ phụ; pháo thủ số 2"),
        ("AG (Australia Group)", "nhóm Ôxtrâylia (nhóm 33 nước cam kết kiểm soát và cắt giảm vũ khí)"),
        ("AG (automatic gun)", "pháo nòng dài tự động"),
        ("AGA (Adjutant General of the Army)", "chủ nhiệm quản lý hành chính quân đội; chủ nhiệm quản lý hành chính lục quân"),
        ("agacs (automatic ground-air communication system)", "hệ thống thông tin liên lạc tự động đất - không"),
        ("AGARD (Advisory Group for Aeronautical Research and Development)", "nhóm cố vấn NATO về nghiên cứu và phát triển hàng không"),
        ("AGARD (Advisory Group for Aerospace Research and Development)", "nhóm cố vấn về nghiên cứu và phát triển không gian vũ trụ"),
        ("AGC (automatic gain control)", "(thiết bị) tự động điều khiển độ khuếch đại"),
        ("AGC (Adjutant General Corps)", "ngành hành chính quản trị; ngành quản lý hành chính; đoàn sĩ quan quản lý hành chính"),
        ("AGCA (automatic ground - controlled approach)", "sự tiếp cận tự động được điều khiển từ mặt đất"),
        ("agcl (automatic ground-controlled landing)", "sự hạ cánh tự động điều khiển từ mặt đất"),
        ("agcy (agency)", "cục; cơ quan (ngang bộ)"),
        ("AGE (aerospace ground equipment)", "thiết bị hỗ trợ phương tiện hàng không vũ trụ từ mặt đất"),
        ("AGF (Adjutant General to the Forces)", "chủ nhiệm quản lý hành chính lục quân"),
        ("AGF (Army Ground Forces)", "lục quân; lực lượng mặt đất"),
        ("AGG (radar picket ship)", "hạm tàu rada cảnh giới"),
        ("AGHS (hydrographic survey vessel)", "tàu nghiên cứu thuỷ văn"),
        ("AGI (annual general inspection)", "sự thanh tra toàn diện hàng năm (các đơn vị, binh đoàn)"),
        ("AGI (intelligence collection vessel)", "tàu thu thập tin tức tình báo"),
        ("AGIC (Air-Ground Information Center)", "trung tâm thông tin hợp nhất không quân và lục quân"),
        ("AGIL (airborne general illuminating light)", "chiếu sáng chung từ trên không"),
        ("AGIL (airborne general illumination lightshelf)", "giàn đèn chiếu sáng đa dụng từ trên không"),
        ("AGL (above ground level)", "tầm trên mức mặt đất"),
        ("AGL (automatic grenade launcher)", "súng phóng lựu tự động"),
        ("AGLS (Automatic Gun Laying System)", "hệ thống ngắm tự động của pháo, tổ hợp tự động lấy hướng pháo"),
        ("AGM (air-to-ground missile)", "tên lửa không đối đất"),
        ("AGM-28A (Hound Dog, k.hiệu)", "tên lửa không đối đất AGM-28A mang tên “Chó săn”"),
        ("AGM-65 (Maverick, k.hiệu)", "tên lửa không đối đất AGM-65 Maverick"),
        ("AGM-69 (short range attack missile)", "tên lửa tiến công tầm gần AGM-69"),
        ("AGM-86D (deep bunker penetrating air-launched cruise missile)", "tên lửa hành trình không đối đất xuyên phá hầm ngầm AGM-86D"),
        ("AGO (Adjutant General's Office)", "văn phòng chủ nhiệm quản lý hành chính"),
        ("AGOR (oceanographic research vessel)", "tàu nghiên cứu hải dương học"),
        ("AGOS (air ground operations system)", "hệ thống bảo đảm hiệp đồng tác chiến giữa không quân và lục quân; hệ thống bảo đảm hiệp đồng tác chiến không - bộ"),
        ("AGOS (ocean surveillance vessel)", "tàu do thám đại dương"),
    ]),
    (1369, [
        ("AGR (Active Guard and Reserve)", "lực lượng cảnh vệ tại ngũ và dự bị"),
        ("AGRA (Army Group, Royal Artillery, Anh)", "cụm pháo binh dã chiến lục quân"),
        ("AGRE (Army Group, Royal Engineers, Anh)", "cụm công binh lục quân"),
        ("AGREE (Advisory Group on Reliability in Electronic Equipment)", "nhóm cố vấn về độ tin cậy của thiết bị điện tử"),
        ("AGRS (American Graves Registration Service, Mỹ)", "dịch vụ đăng ký mai táng quân nhân Mỹ"),
        ("AGS (aeronautical ground station)", "trạm mặt đất dẫn đường không quân"),
        ("AGS (air ground section)", "bộ phận không quân - mặt đất; bộ phận tác chiến không - bộ"),
        ("AGS (Army General Staff)", "tổng tham mưu trưởng quân đội"),
        ("AGS (armored gun system, Mỹ)", "tổ hợp pháo nòng dài đặt trên xe bọc thép, tổ hợp pháo nòng dài bọc thép tự hành"),
        ("AGSCC (army general supplies commodity center)", "trung tâm bảo đảm hàng tiếp tế của lục quân; trung tâm bảo đảm hàng tiếp tế của quân đội"),
        ("AGSL (satellite launching ship)", "tàu phóng vệ tinh"),
        ("AGTS (air gunnery target system)", "hệ thống hiển thị mục tiêu xạ kích trên không"),
        ("AGV (Assault Gun Vehicle)", "pháo công phá, pháo xung kích"),
        ("AGZ (actual ground zero)", "chấn tâm thực của vụ nổ hạt nhân"),
        ("AH (airfield heliport)", "bãi máy bay trực thăng (ở sân bay); bãi trực thăng"),
        ("Ah (Ampère hours)", "Ampe giờ"),
        ("AH (hospital ship)", "tàu quân y"),
        ("AH-64 (Apeché, k.hiệu)", "máy bay trực thăng vũ trang AH-64 Apátchơ"),
        ("AHC (Army Hospital Corps, Anh)", "ngành quân y viện lục quân (trong thành phần của ngành quân y)"),
        ("ahd (airhead)", "đầu cầu hàng không, đầu cầu đổ bộ đường không"),
        ("AHE (ammunition handling equipment)", "thiết bị xử lí đạn (dược)"),
        ("AHM (anti-helicopter mine)", "mìn chống máy bay trực thăng"),
        ("AHQ (advanced headquarters)", "bộ chỉ huy tiền phương; bộ tham mưu tuyến một"),
        ("AHQ (Air Headquarters)", "bộ chỉ huy không quân, sở chỉ huy không quân"),
        ("AHQ (Allied Headquarters)", "bộ chỉ huy liên minh, sở chỉ huy liên quân"),
        ("AHQ (army headquarters)", "bộ tham mưu tập đoàn quân; bộ chỉ huy tập đoàn quân"),
        ("AHRS (Attitude/heading reference system)", "hệ thống so sánh độ cao bay"),
        ("ahsr (air height-surveillance radar)", "rada cảnh giới cao không"),
        ("AI (airborne intercept)", "đánh chặn mục tiêu trên không (từ vị trí trực trên không)"),
        ("AI (air interdiction)", "sự cấm bay; chia cắt bằng không quân"),
        ("AI (airborne interceptor)", "tên lửa đánh chặn phóng từ máy bay"),
        ("AI (area of interest)", "khu vực (cần) chú ý, khu vực trinh sát và cơ động tiếp theo (của binh đoàn)"),
        ("AI (army intelligence)", "tình báo lục quân; trinh sát lục quân"),
        ("AI (artificial intelligence)", "tin tức tình báo giả định (nội dung về đối tượng dự kiến được lập trình bằng máy tính)"),
        ("AIA (Air Intelligence Agency)", "cục tình báo không quân"),
        ("AIAA (American Institute of Aeronautics and Astronautics)", "viện hàng không và du hành vũ trụ Mỹ"),
        ("AIB (armored infantry battalion)", "tiểu đoàn bộ binh cơ giới (trong sư đoàn tăng thiết giáp)"),
        ("AIC (air intercept controller)", "sĩ quan dẫn đường đánh chặn trên không"),
    ]),
    (1370, [
        ("AIC (airspace information center)", "trung tâm thông tin không gian vũ trụ"),
        ("AIC (ammunition identification code)", "quy tắc nhận biết đạn dược; mã nhận biết đạn dược"),
        ("AIC (Atlantic Intelligence Command)", "bộ chỉ huy tình báo Đại Tây Dương"),
        ("AICBM; A-ICBM (anti-intercontinental ballistic missile)", "tên lửa chống tên lửa đạn đạo vượt đại châu; tên lửa chống tên lửa"),
        ("AICP (atomic incident control plan)", "kế hoạch kiểm soát sự cố vũ khí hạt nhân; kế hoạch kiểm soát khủng hoảng vũ khí hạt nhân"),
        ("AIDB (anti-intrusion defence barriers)", "hàng rào chống xâm nhập, hàng rào chống đột nhập"),
        ("AIDS (acoustic intelligence data system)", "hệ thống xử lý dữ liệu tình báo âm thanh"),
        ("AIDS (airborne integrated data system)", "hệ thống dữ liệu tích hợp hàng không"),
        ("AIF (Air Intelligence Force)", "lực lượng tình báo không quân, tình báo không quân"),
        ("AIF (automated installation intelligence file)", "hồ sơ lưu giữ tin tức tình báo tự động"),
        ("AIFS (Advanced Indirect Fire System)", "tổ hợp vũ khí bắn gián tiếp cải tiến"),
        ("AIFV (Armored Infantry Fighting Vehicle, US)", "xe chiến đấu bộ binh bọc thép"),
        ("AIG (addressee indicator group)", "nhóm mã số địa chỉ người nhận"),
        ("AII (army intelligence interpreter)", "người phiên dịch của tình báo lục quân"),
        ("AIIRS (automated intelligence information reporting system)", "hệ thống tự động báo cáo thông tin tình báo"),
        ("AIL (airborne instrument laboratory)", "phòng thí nghiệm các thiết bị đo trên máy bay"),
        ("AILS (advanced integrated landing system)", "hệ thống (điều khiển) hạ cánh hợp nhất cải tiến"),
        ("AIM (air intercept missile)", "tên lửa đánh chặn đường không"),
        ("AIM (air interdiction mine)", "mìn ngăn chặn thả từ trên không; (hq) thuỷ lôi ngăn chặn thả từ máy bay"),
        ("AIM (Airman's Information Manual)", "cẩm nang thông tin của binh sĩ không quân"),
        ("AIM (anti-invation mine)", "mìn chống xâm nhập"),
        ("AIMD (aircraft intermediate maintenance department)", "cục trung tu máy bay"),
        ("AIMS (advanced intercontinental missile system)", "tổ hợp tên lửa vượt đại châu cải tiến"),
        ("AIMS (Army Integrated Meteorological System)", "hệ thống khí tượng hợp nhất của lục quân"),
        ("AINS (airborne inertial navigation system)", "hệ thống dẫn đường quán tính (đặt) trên máy bay"),
        ("AIntO (air intelligence officer)", "sĩ quan tình báo không quân"),
        ("AIO (action information organization)", "cơ quan thông báo (tình hình) chiến sự"),
        ("AIP (air independent propulsion)", "(thiết bị) động lực [động cơ] không dùng không khí; lực đẩy không khí độc lập"),
        ("AIPS (Advanced Integrated Propulsion System, US)", "hệ thống lực đẩy hợp nhất cải tiến"),
        ("AIPS (air independent propulsion submarines)", "tàu ngầm có động cơ không dùng không khí"),
        ("AIQC (antiterrorism instructor qualification course)", "khoá đào tạo huấn luyện viên chống khủng bố"),
        ("AIR (air intercept radar)", "rada bắt chặn mục tiêu trên không"),
        ("air cav trp (air cavalry troop)", "đại đội trinh sát kỵ binh bay, đại đội trinh sát cơ động đường không"),
        ("Air Cdre (air commodore, Anh)", "chuẩn tướng không quân"),
        ("air con tm (air control team)", "đội kiểm soát đường không"),
    ]),
    (1371, [
        ("Air spt (air support)", "sự chi viện đường không; sự bảo đảm đường không"),
        ("air survl means (air surveillance means)", "các phương tiện trinh sát bằng quan sát trên không, các phương tiện quan sát từ trên không"),
        ("Air T. Sq. (air transport squadron)", "phi đội vận tải"),
        ("air veh (air vehicle)", "phương tiện bay (máy bay, tên lửa...)"),
        ("AIRBALTAP (Allied Air Forces, Baltic Approaches)", "không quân liên minh NATO ở khu vực vịnh Bantích"),
        ("AIRBM (anti-intermediate range ballistic missile)", "tên lửa chống tên lửa đạn đạo tầm trung"),
        ("AIRCENT (Allied Air Forces, Central Europe)", "(lực lượng) không quân liên minh NATO ở khu vực Trung Âu"),
        ("AIREP (air intelligence report)", "sự báo cáo về trinh sát đường không; bản báo cáo tình hình trinh sát đường không; báo cáo về thám không"),
        ("AIREVACCONFIRM (air evacuation confirmation)", "sự phê chuẩn (quyết định) di tản đường không"),
        ("AIREVACREQ (air evacuation request)", "yêu cầu di tản đường không"),
        ("AIREVACRESP (air evacuation response)", "sự đáp ứng (yêu cầu) di tản đường không"),
        ("AIRLO (air liaison officer)", "sĩ quan thông tin liên lạc không quân"),
        ("airmob div (airmobile division)", "sư đoàn cơ động đường không"),
        ("airmob ops (airmobile operations)", "tác chiến cơ động đường không; chiến dịch cơ động đường không"),
        ("AIRNAG (Air Forces, Northern Army Group)", "(lực lượng) không quân của cụm tập đoàn quân Phương Bắc"),
        ("AIRNORTH (Allied Air Forces, Northern Europe)", "(lực lượng) không quân liên minh NATO ở khu vực Bắc Âu"),
        ("AIRNORTHWEST (Allied Air Forces North West Europe, NATO)", "(lực lượng) không quân liên minh NATO ở Tây Bắc Âu"),
        ("AIROP (airborne operation)", "chiến dịch đổ bộ đường không, tác chiến của lực lượng đổ bộ đường không"),
        ("AIRREQRECON (air request reconnaissance)", "sự trinh sát theo yêu cầu của không quân"),
        ("AIRS (airborne integrated reconnaissance system)", "hệ thống trinh sát hợp nhất trên máy bay"),
        ("AIRSOUTH (Allied Air Forces, Southern Europe)", "(lực lượng) không quân liên minh NATO ở khu vực Nam Âu"),
        ("AIRSUPREQ (air support request)", "yêu cầu chi viện đường không"),
        ("AIS (advanced instrumentation subsystem)", "hệ thống phụ trong khí tài cải tiến, hệ thống bổ trợ trong khí tài cải tiến"),
        ("AIS (Army Intelligence and Security)", "tình báo và an ninh phần gián lục quân"),
        ("AIS (Army Intelligence and Security, Branch)", "ngành tình báo và an ninh lục quân"),
        ("AIS (automated information system)", "hệ thống thông tin tự động hoá"),
        ("AIT (advanced individual training)", "sự huấn luyện cá nhân nâng cao; sự huấn luyện bổ túc cá nhân"),
        ("AIT (Army Individual Test)", "sự trắc nghiệm tâm lý kỹ thuật quân nhân của lục quân"),
        ("AIT (Army intelligence translator)", "người biên dịch của tình báo lục quân"),
        ("AIT (automated identification technology)", "công nghệ nhận dạng tự động hoá, công nghệ tự động nhận dạng"),
        ("AIU (aircraft interface unit)", "khối thiết bị giao diện trên máy bay (chỉ báo tình trạng)"),
        ("AIU (Automatic Digital Network Interface Unit)", "đơn vị giao diện mạng kỹ thuật số tự động"),
    ]),
    (1372, [
        ("AJ/CM (anti-jam control modem)", "môđem điều khiển chống nhiễu"),
        ("AJ; Aj; aj (anti-jamming)", "sự chống nhiễu vô tuyến (tích cực); phương tiện chống nhiễu vô tuyến (tích cực)"),
        ("aja (ajacent)", "đơn vị tiến công bên cạnh; quân bạn"),
        ("AJBPO (Area Joint Blood Program Office)", "văn phòng chương trình hỗ trợ máu của liên quân khu vực"),
        ("AJCC (alternate joint communications center)", "trung tâm thông tin liên lạc dự bị liên quân"),
        ("AJFP (adaptive joint force packaging)", "sự tổ chức lực lượng tác chiến đặc biệt áp dụng chung cho liên quân"),
        ("AJMRO (area joint medical regulating office)", "văn phòng điều hành y tế liên quân khu vực"),
        ("AJNPE (airborne joint nuclear planning element)", "bộ phận lập kế hoạch tác chiến hạt nhân trên không của liên quân"),
        ("AK (Avtomat Kalashnikova, Nga)", "súng tiểu liên AK"),
        ("AK (commercial cargo ship)", "tàu hàng thương mại"),
        ("AKDC/RCU (Automatic Key Distribution Center/Rekeying Control Unit)", "trung tâm phân phối mã tự động/bộ điều khiển đổi mã"),
        ("AKNLDG (acknowledge message)", "điện báo nhận"),
        ("al (airlift)", "vận chuyển đường không, “cầu hàng không”; vận tải đường không; hàng hoá được vận chuyển bằng đường không"),
        ("AL (Alaska)", "tiểu bang Alátxca"),
        ("AL (allied)", "đồng minh; liên minh; liên quân"),
        ("AL (Army List, Anh)", "danh sách sĩ quan quân đội"),
        ("AL plat (airlift platoon)", "trung đội vận tải đường không"),
        ("ALA (army launch area)", "khu vực phóng tên lửa lục quân"),
        ("ALA (assault landing area)", "khu vực đổ bộ tiến công; khu vực đổ bộ thê đội một"),
        ("ALAAVS (Advanced Light Armored/Amphibious Vehicle System, US)", "hệ thống xe bọc thép lội nước hạng nhẹ cải tiến"),
        ("ALAD (automatic liquid agent detector)", "thiết bị tự động phát hiện chất độc thể lỏng"),
        ("ALANF (Army Land Forces)", "lực lượng lục quân, lục quân"),
        ("ALARM (air-launched anti-radiation missile)", "tên lửa chống bức xạ hàng không, tên lửa chống bức xạ phóng từ trên không, tên lửa chống bức xạ phóng từ máy bay"),
        ("Alarms (airborne laser radar mine sensor)", "xenxơ phát hiện thuỷ lôi dạng vô tuyến định vị bằng lade đặt trên máy bay"),
        ("ALBM (air-launched ballistic missile)", "tên lửa đạn đạo hàng không, tên lửa đạn đạo phóng từ máy bay"),
        ("ALCANUS (Alaska, Canada, United States)", "Alátxca, Canada, Mỹ"),
        ("ALCC (airborne launch control centre, Mỹ)", "trạm điều khiển phóng (tên lửa) đặt trên máy bay, máy bay chỉ huy phóng (tên lửa chiến lược)"),
        ("ALCC (airlift control center)", "trung tâm kiểm soát vận tải đường không"),
        ("ALCC (airlift coordination cell)", "bộ phận hiệp đồng vận tải đường không"),
        ("ALCE (airlift control element)", "lực lượng kiểm soát vận tải đường không"),
        ("ALCM (air-launched cruise missile)", "tên lửa hành trình hàng không, tên lửa hành trình phóng từ trên không, tên lửa có cánh phóng từ máy bay"),
        ("ALCM (the Boeing AGM-86B air-to-surface missile)", "tên lửa không đối đất AGM-86B của hãng Bôinh"),
    ]),
    (1373, [
        ("ALCOM (Alaskan Command, Mỹ)", "bộ tư lệnh Alátxca, bộ chỉ huy quân đội Mỹ ở khu vực Alátxca"),
        ("ALCON (all concerned)", "liên quan đến mọi người"),
        ("ALCS (airborne launch control system, Mỹ)", "hệ thống điều khiển phóng (tên lửa) đặt trên máy bay; máy bay điều khiển phóng (tên lửa)"),
        ("ALD (accounting line designator)", "bộ chỉ thị tuyến thống kê"),
        ("ALD (airborne laser designator)", "bộ chỉ thị mục tiêu bằng lade trên máy bay"),
        ("ALD (available-to-load date)", "ngày có sẵn hàng để bốc xếp (lên phương tiện)"),
        ("ALDP (airborne laser designator pod)", "thiết bị chiếu chỉ thị mục tiêu bằng lade (treo) trên máy bay"),
        ("ALE (airlift liaison element)", "đơn vị liên lạc hiệp đồng với lực lượng vận tải đường không"),
        ("ALERFA (alert phase, ICAO)", "giai đoạn báo động cảnh giác (tổ chức hàng không dân dụng quốc tế)"),
        ("ALERT (attack and launch early reporting to theater)", "thông báo sớm về việc tiến công và phóng tên lửa cho mặt trận"),
        ("ALF (Allied Land Force)", "lực lượng lục quân liên quân NATO"),
        ("ALFCE (Allied Land Forces, Central Europe)", "lực lượng lục quân liên quân NATO ở khu vực Trung Âu"),
        ("ALFN (Allied Land Forces, Norway)", "lực lượng lục quân liên quân NATO ở Na Uy"),
        ("ALFSE (Allied Land Forces, Southern Europe)", "lực lượng lục quân liên quân NATO ở khu vực Nam Âu"),
        ("ALFSEE (Allied Land Forces, Southeastern Europe)", "lực lượng lục quân liên quân NATO ở khu vực Đông Nam Âu"),
        ("ALLOREQ (allocation request)", "yêu cầu bổ nhiệm"),
        ("ALM (air-launched missile)", "tên lửa hàng không, tên lửa phóng từ trên không"),
        ("ALMSNSCD (airlift mission schedule)", "kế hoạch nhiệm vụ vận tải đường không"),
        ("ALMT (allotment)", "sự phân phối"),
        ("ALNOT (alert notice)", "yết thị thông báo"),
        ("ALNOT (search and rescue alert notice)", "yết thị thông báo về tìm kiếm và cứu nạn"),
        ("ALO (air liaison officer)", "sĩ quan liên lạc hiệp đồng với không quân"),
        ("ALOC (air lines of communication)", "tuyến giao thông liên lạc đường không; tuyến giao thông đường không"),
        ("ALORD (alert launch order)", "lệnh cảnh báo phóng"),
        ("ALP (air liaison party)", "nhóm liên lạc hiệp đồng với không quân"),
        ("ALP (ambulance loading post)", "trạm bốc xếp y cụ lên xe cứu thương"),
        ("ALQ (airborne active electronic countermeasures systems)", "tổ hợp phương tiện chống tác chiến điện tử tích cực đường không, hệ thống các biện pháp phản tác chiến điện tử tích cực đường không"),
        ("ALQA (automatic link quality analysis)", "sự phân tích chất lượng đường truyền (dữ liệu) tự động; tự động phân tích chất lượng đường truyền"),
        ("ALR (airborne eletronic signal monitoring)", "sự giám sát tín hiệu điện tử đường không"),
        ("ALRAD (airborne laser rangefinder and designator)", "máy chỉ thị mục tiêu và định tầm bằng lade (đặt) trên máy bay"),
        ("ALRI (airborne long-range radar input)", "thiết bị nhập dữ liệu rada tầm xa (đặt) trên máy bay"),
        ("ALS (Advanced Laying System)", "hệ thống lấy hướng pháo cải tiến"),
        ("ALS (air liaison section)", "phân đội liên lạc hiệp đồng với không quân"),
        ("ALS (Air Logistics Service)", "ngành bảo đảm vật chất - kỹ thuật không quân"),
    ]),
    (1374, [
        ("ALS (all-weather landing system)", "hệ thống (điều khiển) hạ cánh mọi thời tiết"),
        ("ALSA (Air Land Sea Application, Center)", "(trung tâm) ứng dụng hải - lục - không quân"),
        ("ALSEAFRON (Alaskan Sea Frontier)", "quân khu hải quân Alátxca"),
        ("ALSS (advanced logistic support site)", "địa điểm bảo đảm hậu cần tiền phương, vị trí bảo đảm hậu cần phía trước"),
        ("ALSV (Armoured Logistics Support Vehicle)", "xe hậu cần bọc thép bảo đảm"),
        ("ALT (airborne laser tracker)", "thiết bị bám mục tiêu bằng lade (đặt) trên máy bay"),
        ("alt (altitude)", "độ cao"),
        ("ALT (alternate)", "người thay thế; người bị thay thế; thay thế; dự phòng"),
        ("ALT (Armoured Launching Turret)", "tháp phóng đặt trên xe bọc thép"),
        ("ALTTSC (alternate Tomahawk strike coordinator)", "sĩ quan hiệp đồng tập kích tên lửa Tômahốc dự bị"),
        ("ALUSLO (United States Naval Liaison officer)", "sĩ quan liên lạc hải quân Mỹ"),
        ("ALUSNA (United States Naval Attaché)", "tuỳ viên hải quân Mỹ"),
        ("ALW (air/land warfare)", "tác chiến (hiệp đồng) không - bộ, tác chiến hiệp đồng không quân và lục quân (không quân làm chủ lực)"),
        ("ALW (allowance)", "lương, phụ cấp; định mức; cơ số"),
        ("ALWT (advanced lightweight torpedo)", "ngư lôi hạng nhẹ cải tiến"),
        ("AM (Air Medal)", "“huy chương không quân”"),
        ("am (ammunition)", "đạn dược"),
        ("AM (amplitude modulation)", "sự điều biến biên độ; sự điều biến"),
        ("AM (anti-matériel)", "phá huỷ trang bị kỹ thuật"),
        ("AM (Army Manual)", "điều lệnh lục quân"),
        ("AM (assembly and maintenance)", "sự lắp ráp và bảo dưỡng kỹ thuật"),
        ("AM (minesweeper)", "tàu quét thuỷ lôi"),
        ("Am. Co (DP) (ammunition company, distribution point)", "đại đội đạn dược (trạm cấp phát)"),
        ("Am/fm (amplitude modulation/frequency modulation)", "điều biến/điều tần"),
        ("AMA (air materiel area)", "khu vực bảo đảm vật chất - kỹ thuật không quân"),
        ("AMAD (airframe-mounted accessory drive)", "cơ cấu lái bổ trợ trên máy bay"),
        ("AMAL (authorized medical allowance list)", "danh sách phụ cấp y tế được phê chuẩn"),
        ("AMB (air mobility branch)", "binh chủng cơ động đường không"),
        ("amb (ambulance)", "phương tiện vận tải cứu thương; xe cứu thương; viện quân y dã chiến; cứu thương; tải thương, chuyển thương"),
        ("Amb (Co) (ambulance company)", "đại đội xe cứu thương"),
        ("AMBUS (ambulance bus)", "xe cứu thương"),
        ("AMC (advance message center)", "trung tâm thu thập báo cáo phía trước; trạm tập hợp báo cáo tiền phương"),
        ("AMC (Advanced Mortar Carrier)", "xe chở súng cối cải tiến; súng cối tự hành (đặt trên xe cải tiến)"),
        ("AMC (Air Mobility Command)", "bộ tư lệnh cơ động đường không; bộ tư lệnh không vận Mỹ"),
        ("AMC (airborne mission commander)", "chỉ huy trưởng phi vụ tác chiến cơ động đường không"),
        ("AMC (Armored Mortar Carrier)", "xe chở súng cối bọc thép; súng cối tự hành (đặt trên xe) bọc thép"),
        ("AMC (Army Materiel Command)", "bộ tư lệnh vật chất - kỹ thuật lục quân; bộ tư lệnh bảo đảm vật chất - kỹ thuật quân đội"),
        ("AMC (Army Medical Center)", "trung tâm quân y"),
        ("AMC (Army Missile Command)", "bộ tư lệnh tên lửa lục quân"),
    ]),
    (1375, [
        ("AMC (at my command)", "theo lệnh tôi"),
        ("AMCC (alternate military command center)", "trung tâm chỉ huy quân sự dự bị"),
        ("AMCCOM (Armament Munitions and Chemical Command)", "bộ tư lệnh vũ khí đạn dược và hoá học"),
        ("AMCM (airborne mine countermeasures)", "phương tiện chống mìn bằng đường không; (hq) các biện pháp chống thuỷ lôi bằng đường không"),
        ("AMCP (Allied Military Communications Panel)", "uỷ ban thông tin liên lạc quân sự liên quân NATO"),
        ("AMCROSS (American National Red Cross)", "hội chữ thập đỏ Mỹ"),
        ("AMCS (airborne missile control system)", "hệ thống điều khiển tên lửa (đặt) trên máy bay; máy bay điều khiển tên lửa"),
        ("AMCS (army mobilization capabilities study)", "sự nghiên cứu khả năng động viên quân đội; sự nghiên cứu khả năng động viên lục quân"),
        ("AMD (air and missile defense)", "phòng chống máy bay và tên lửa"),
        ("AMD (air mobility division)", "cục cơ động đường không"),
        ("AMDC (Army Missile Development Center)", "trung tâm nghiên cứu và thử nghiệm tên lửa của lục quân"),
        ("AmDP (ammunition distributing point)", "trạm cấp phát đạn dược; địa điểm cấp phát đạn dược"),
        ("AMDPCS (Air and Missile Defense Planning and Control System)", "hệ thống lập kế hoạch và chỉ huy phòng chống máy bay và tên lửa"),
        ("AMDR (automatic missile detection radar)", "rada tự động phát hiện tên lửa"),
        ("AMDS (anti-missile discarding sabot)", "đạn dưới cỡ chống tên lửa, đạn chống tên lửa có ốp tự văng"),
        ("AMDS (automatic maneuvering device system)", "tổ hợp thiết bị tự động cơ động"),
        ("AME (aeromedical evacuation)", "sự chuyển thương bằng đường không"),
        ("AME (air mobility element)", "phân đội cơ động đường không"),
        ("AMECZ; amecz (antimechanized)", "(thuộc) chống tăng, (thuộc) chống cơ giới; dùng để chống lực lượng cơ giới"),
        ("AMEDD (Army Medical Department)", "cục quân y lục quân"),
        ("AMEDS; AMS (Army Medical Service)", "ngành quân y lục quân"),
        ("AMETS (artillery meteological system, Anh)", "hệ thống quan trắc khí tượng pháo (binh)"),
        ("AMF (ace mobile force)", "lực lượng cơ động tinh nhuệ"),
        ("AMF (small multinational NATO Force)", "lực lượng bộ binh nhẹ đa quốc gia thuộc liên quân NATO"),
        ("AMF (Atlantic Multilateral Force)", "lực lượng đa quốc gia NATO ở khu vực Đại Tây Dương"),
        ("AMF (Australian Military Forces)", "lực lượng vũ trang Ôxtrâylia; quân đội Ôxtrâylia"),
        ("AMF (multipurpose amphibious vehicle)", "phương tiện lội nước đa dụng, phương tiện lội nước vạn năng"),
        ("AMFCTS (artillery & motar fire control training simulator)", "thiết bị mô phỏng huấn luyện chỉ huy hoả lực pháo cối"),
        ("AMH (automated message handler)", "phương tiện điều khiển xử lý điện văn tự động hoá; thiết bị tự động xử lý tin điện"),
        ("AMHS (automated message handling system)", "hệ thống tự động xử lý tin"),
        ("AMICOM (Army Missile Command)", "bộ tư lệnh tên lửa lục quân, bộ chỉ huy tên lửa lục quân"),
        ("AMIDARS (airborne minefield detection and reconnaissance system)", "hệ thống trinh sát và phát hiện bãi thuỷ lôi (từ) trên máy bay; máy bay trinh sát và phát hiện bãi thuỷ lôi"),
    ]),
    (1376, [
        ("AMIDS (airborne minefield detection system)", "tổ hợp phát hiện bãi mìn từ trên không; (hq) hệ thống phát hiện bãi thuỷ lôi (từ) trên máy bay; máy bay phát hiện bãi thuỷ lôi"),
        ("AMIS (anti-matériel incendiary submunition)", "đạn bộ binh phát cháy phá huỷ phương tiện vật chất"),
        ("AMIS (anti-missile infrared)", "hồng ngoại chống tên lửa"),
        ("AML (light armoured car)", "ô tô bọc thép hạng nhẹ"),
        ("AMLCD (active matrix liquid cristal display)", "màn hình tinh thể lỏng mạng chủ động"),
        ("AMLS (airspace management liaison system)", "hệ thống liên lạc hiệp đồng quản lý không gian vũ trụ"),
        ("AMM (antimissile missile)", "tên lửa chống tên lửa"),
        ("AMMO; ammo (ammunition)", "đạn dược"),
        ("ammo sup pt (ammunition supply point)", "trạm cấp phát đạn dược"),
        ("AMMSDO (Antimissile Missile and Space Defense Office)", "cục tên lửa chống tên lửa và phòng thủ không gian vũ trụ"),
        ("AMOCC (air mobility operations control center)", "trung tâm điều khiển các hoạt động cơ động đường không"),
        ("AMOG (air mobility operations group)", "cụm tác chiến cơ động đường không"),
        ("AMOPES (Army Mobilization and Operations Planning and Execution System)", "hệ thống động viên, lập kế hoạch và thực hành tác chiến lục quân"),
        ("AMOPS (Army mobilization and operations planning system)", "hệ thống lập kế hoạch động viên và tác chiến lục quân"),
        ("AMOPS (Army mobilization operations system)", "hệ thống điều hành hoạt động động viên lục quân"),
        ("AMORS (Asia-pacific Military Operations Symposium)", "hội nghị chuyên đề các hành động quân sự châu Á - Thái Bình Dương"),
        ("AMOS (additionally awarded military occupational specialty)", "chuyên môn quân sự bổ sung"),
        ("AMOS (Advanced Mortar System)", "tổ hợp súng cối cải tiến"),
        ("AMP (allied mining publication)", "nhà xuất bản mìn liên quân NATO"),
        ("AMP (amplifier)", "bộ khuếch đại"),
        ("AMPD (army mobilization program directive)", "chỉ thị về chương trình huấn luyện động viên quân đội; chỉ lệnh về chương trình huấn luyện động viên của lục quân"),
        ("AMPE (automated message-processing exchange)", "sự trao đổi xử lý tin điện tự động hoá, tự động trao đổi xử lý tín điện"),
        ("amph (amphibian)", "phương tiện đổ bộ lội nước, xe lội nước; thuỷ bộ; thuỷ phi cơ"),
        ("AMR (anti-material rifle)", "súng trường chống vật lực (phi sinh lực); hoả khí (rãnh xoắn) phá huỷ trang bị kỹ thuật"),
        ("AMR (Atlantic Missile Range)", "trường bắn thử nghiệm tên lửa ở khu vực Đại Tây Dương"),
        ("AMRAAM (advanced medium range air-to-air missile)", "tên lửa không đối không tầm trung cải tiến"),
        ("AMRAD (automatic message routeing and distribution)", "tạo đường truyền và phân phối tin tự động"),
        ("AMRD-NASC (Army Missiles and Rockets Directorate - NATO Supply Center)", "viện tên lửa của lục quân Mỹ thuộc trung tâm tiếp tế NATO"),
        ("ams (anti-missile surface-to-air missile)", "tên lửa mặt (đất, biển) chống tên lửa đường không, tên lửa mặt (đất, biển) đối không chống tên lửa"),
        ("AMS (Armoured Mortar System)", "tổ hợp súng cối đặt trên xe bọc thép"),
        ("AMS (Army Map Service)", "ngành bản đồ địa hình quân đội; ngành bản đồ địa hình lục quân"),
    ]),
    (1377, [
        ("AMS (Army Medical Service)", "ngành quân y lục quân"),
        ("AMS (automatic meteorological system)", "hệ thống tự động quan trắc khí tượng"),
        ("AMSA (advanced manned strategic aircraft)", "máy bay chiến lược cải tiến có người lái; máy bay ném bom chiến lược hiện đại có người lái"),
        ("AMSA (ammo supply authority)", "cơ quan phụ trách tiếp tế đạn dược"),
        ("AMSC (Army Medical Specialists Corps)", "đoàn chuyên gia quân y; đoàn chuyên gia quân y lục quân"),
        ("amt (amount)", "lượng, số lượng"),
        ("AMTC (Army Missile Test Center)", "trung tâm thử nghiệm tên lửa lục quân; trung tâm thử nghiệm tên lửa của quân đội"),
        ("AMTD (adaptive moving target detection)", "rada tương thích phát hiện mục tiêu (di) động"),
        ("AMTF (air-mobile task force)", "cụm máy bay cánh quạt chiến dịch - chiến thuật; đội đặc nhiệm cơ động đường không"),
        ("AMTI (airborne moving target indicator)", "bộ chỉ thị mục tiêu di động (đặt) trên máy bay"),
        ("AMTK (amphibious tank)", "xe tăng lội nước"),
        ("AMTRAC (amphibious tractor)", "xe kéo lội nước"),
        ("AMU (advanced marksmanship unit)", "đơn vị huấn luyện bắn tỉa nâng cao; phân đội huấn luyện bắn tỉa nâng cao"),
        ("amu (atomic mass unit)", "đơn vị khối lượng nguyên tử"),
        ("AMV (armored maintenance vehicle)", "xe bọc thép bảo dưỡng"),
        ("AMW (air mobility wing)", "phi đoàn cơ động đường không"),
        ("AMW (amphibious warfare)", "tác chiến đổ bộ đường biển"),
        ("AMX (air mobility express)", "cơ động đường không khẩn cấp"),
        ("AMX-10Pa (French infantry tracked fighting vehicle)", "xe chiến đấu bộ binh bánh xích của Pháp"),
        ("AMX-10RC (French wheeled tank destroyer)", "xe bọc thép bánh hơi diệt tăng của Pháp"),
        ("AMX-13 (French light tank)", "xe tăng hạng nhẹ của Pháp"),
        ("AMX-30 (French main battle tank)", "xe tăng chiến đấu chủ lực của Pháp"),
        ("AN (alphanumeric)", "bằng chữ và bằng số"),
        ("AN (analog nonsecure)", "không an toàn về thuật tương tự"),
        ("AN (Army-Navy)", "trang bị cho lực lượng lục quân và hải quân"),
        ("AN (army number)", "số hiệu quân nhân"),
        ("An (normal atmosphere)", "áp suất tiêu chuẩn"),
        ("AN (Soviet aircraft AN, Antonov)", "máy bay AN của Liên Xô"),
        ("AN-22 (Antonov 22, soviet super transport plane, k.hiệu)", "AN-22 (máy bay vận tải hạng nặng của Liên Xô)"),
        ("ANA (army, navy, air force)", "lực lượng lục quân, hải quân và không quân"),
        ("ANACDUTRA (annual active duty for training)", "huấn luyện lực lượng dự bị hàng năm (được tính vào thời hạn phục vụ tại ngũ)"),
        ("ANAF (Army, Navy, Air Force)", "lục quân, hải quân và không quân"),
        ("ANC (ammoium-nitrate carbon)", "amoni-nitrat cácbon (chất nổ)"),
        ("ANC (Army-Navy Civil Aeronautics Committee)", "uỷ ban hàng không dân dụng hải quân và lục quân"),
        ("ANC (Army Nurse Corps)", "ngành y tá quân đội; đoàn y tá lục quân"),
        ("ANCA (Allied Naval Communications Agency)", "cục thông tin liên lạc hải quân liên quân"),
        ("ANCOVS (active night covert vision system)", "hệ thống quan sát hỗ trợ hoạt động ban đêm; hệ thống nhìn đêm chủ động"),
    ]),
    (1378, [
        ("ANDVT (advanced narrowband digital voice terminal)", "thiết bị thông tin liên lạc đầu cuối âm thanh kỹ thuật số băng tần hẹp cải tiến"),
        ("ANF (Allied Naval Force)", "lực lượng hải quân liên quân NATO"),
        ("ANF (Army News Features)", "phim thời sự quân đội; phim thời sự lục quân"),
        ("ANF (Atlantic Nuclear Force)", "lực lượng hạt nhân đa quốc gia của NATO"),
        ("ANFCE (Allied Naval Forces, Central Europe)", "lực lượng hải quân liên quân NATO ở khu vực Trung Âu"),
        ("ANFE (aircraft non-fully equipped)", "máy bay không được trang bị đầy đủ"),
        ("ANFNE (Allied Naval Forces, Northern Europe)", "lực lượng hải quân liên quân NATO ở khu vực Bắc Âu"),
        ("ANG (Air National Guard)", "đội không quân cận vệ quốc gia, không quân cảnh vệ quốc gia"),
        ("ANGLICO (air and naval gunfire liaison company)", "đại đội thông tin liên lạc hiệp đồng hoả lực không quân và hải quân"),
        ("ANGUS (Air National Guard of the United States)", "đội không quân cận vệ quốc gia Mỹ, không quân cảnh vệ của Mỹ"),
        ("ANMCC (Alternate National Military Command Center)", "trung tâm chỉ đạo quốc phòng luân phiên"),
        ("annx (annex)", "phụ lục"),
        ("ANP (aircraft nuclear propulsion)", "động cơ hàng không dùng năng lượng hạt nhân"),
        ("ANPP (Army Nuclear Power Program)", "chương trình nghiên cứu năng lượng hạt nhân phục vụ mục đích quân sự"),
        ("ANR (Alaskan NORAD Region)", "vùng phòng thủ không gian vũ trụ Alátxca"),
        ("ANS (Academy of Natural Science)", "viện hàn lâm khoa học tự nhiên (Mỹ)"),
        ("ANS (airborne navigation system)", "hệ thống dẫn đường (đặt) trên máy bay"),
        ("ANS (answer)", "câu trả lời; trả lời, đáp (mật khẩu)"),
        ("ANS (Army News Service)", "cơ quan thông tấn quân đội"),
        ("ANS (automatic navigation system)", "hệ thống tự động dẫn đường"),
        ("ANSIA (Army-Navy Shipping Information Agency)", "cục thông tin vận chuyển đường biển"),
        ("ANTCOMDUSARCARIB (Antilles Command, United States Army, Caribbean)", "bộ chỉ huy lục quân Mỹ ở quần đảo Antilet khu vực biển Caribê"),
        ("ANVIS (aviator's night vision system)", "hệ thống nhìn đêm của phi công"),
        ("anx (annex)", "phụ lục"),
        ("ANZUS (Australia, New Zealand, United States, mutual security pact)", "hiệp ước an ninh chung Mỹ, Ôxtrâylia và Niu Dilân"),
        ("ANZUS (Australia - New Zealand - United States Treaty)", "hiệp ước (an ninh) Ôxtrâylia - Niu Dilân - Mỹ"),
        ("AO (action officer)", "sĩ quan thừa hành"),
        ("AO (administration officer)", "sĩ quan hành chính quản trị"),
        ("AO (air officer)", "sĩ quan không quân"),
        ("AO (area of operations)", "khu vực tác chiến"),
        ("AO (army order)", "quân lệnh"),
        ("AO (artillery observation)", "quan sát pháo binh; trinh sát pháo binh (sửa bắn)"),
        ("AO (aviation ordnance person)", "nhân viên kỹ thuật pháo binh của không quân, nhân viên quân khí của không quân"),
        ("AO&M (administration, operation, and maintenance)", "hành chính, tác chiến và bảo dưỡng"),
        ("AOA (amphibious objective area)", "khu vực mục tiêu đổ bộ đường biển"),
        ("AOA (angle of attack)", "góc tấn; góc tiến"),
        ("AOB (advanced operations base)", "căn cứ tác chiến tiền phương"),
        ("AOB (air order of battle)", "bố trí và sử dụng lực lượng không quân; đội hình chiến đấu không quân; thế trận không quân"),
    ]),
    (1379, [
        ("AOB (aviation operations branch)", "ngành tác chiến không quân (của lục quân và hải quân)"),
        ("AOC (adaptive optical camouflage)", "nguỵ trang quang học tương thích"),
        ("AOC (air operations center)", "trung tâm tác chiến không quân"),
        ("AOC (army operations center, Mỹ)", "trung tâm điều hành tác chiến lục quân"),
        ("AOCC (air operations control center)", "trung tâm chỉ huy tác chiến không quân"),
        ("AOC-E (Aviation Operations Center - East, USCS)", "trung tâm hoạt động đường không miền Đông (Mỹ)"),
        ("AOCO (Atomic Ordnance Cataloging Office)", "phòng danh mục vũ khí đạn hạt nhân"),
        ("AOCU (analog orderwire control unit)", "bộ điều khiển mạch vòng theo thuật tương tự"),
        ("AOD (Army Ordnance Department)", "cục vũ khí đạn lục quân; cục quân khí lục quân"),
        ("AOE (auxiliary, fuel and ammunition, RAS capacity)", "(tàu) hỗ trợ nhiên liệu và đạn dược có khả năng tiếp tế trên biển"),
        ("AOI (area of interest)", "khu vực (cần) chú ý, khu vực quan tâm; khu vực quan trọng (có ý nghĩa chiến thuật), khu vực trinh sát và cơ động tiếp theo"),
        ("AOL (absense over leave)", "trả phép muộn; vắng mặt không có lý do"),
        ("AOL (American Online)", "trực tuyến (mạng vi tính) Mỹ"),
        ("AOL (area of limitation)", "khu vực hạn chế hoạt động"),
        ("AOP (air observation post)", "trạm quan sát đường không"),
        ("AOP (air operations plan)", "kế hoạch tác chiến đường không"),
        ("AOP (airborne observation post)", "trạm quan sát (đặt) trên máy bay; máy bay quan sát"),
        ("AOP (area of probability)", "vùng xác suất (trúng đích)"),
        ("AOP (armored observation post)", "trạm quan sát đặt trên xe bọc thép; trạm quan sát trên xe tăng"),
        ("AOR (area of responsibility)", "khu vực đảm trách; khu vực thuộc quyền; khu vực khống chế bằng hoả lực"),
        ("AOS (area of separation)", "khu vực thoát ly (dịch)"),
        ("AOS (army officers school)", "trường sĩ quan lục quân"),
        ("AOSS (aviation ordnance safety supervisor)", "thanh sát viên an toàn vũ khí đạn không quân (của lục quân)"),
        ("AOT (tanker without RAS capability)", "tàu chở dầu không có khả năng tiếp dầu ngoài biển"),
        ("AOV (artillery observation vehicle)", "xe trinh sát pháo binh"),
        ("AP (aiming point)", "điểm ngắm"),
        ("AP (airport)", "sân bay"),
        ("AP (ammunition point)", "trạm tiếp tế đạn dược; địa điểm cấp phát đạn dược"),
        ("AP (antipersonnel)", "(thuộc) chống bộ binh, (thuộc) sát thương bộ binh, (thuộc) sát thương sinh lực"),
        ("AP (armor - piercing)", "đạn xuyên thép, đạn chống tăng"),
        ("AP (atomic power)", "năng lượng hạt nhân; sức mạnh hạt nhân; cường quốc hạt nhân"),
        ("AP (automatic pistol)", "súng ngắn tự động; súng ngắn liên thanh"),
        ("ap ctl (autopilot control)", "sự điều khiển lái tự động"),
        ("APA (amphibious transport)", "vận tải đổ bộ (đường biển)"),
        ("APAM (anti-personnel, anti-matériel)", "chống bộ binh và phá huỷ trang bị; sát thương sinh lực và phương tiện; huỷ diệt"),
        ("APAM (antipersonnel-antimateriel)", "chống bộ binh và phá huỷ trang bị; sát thương sinh lực và phương tiện; huỷ diệt"),
        ("APC (aerial port commander)", "chỉ huy trưởng cảng hàng không"),
    ]),
    (1380, [
        ("APC (armored personnel carrier)", "xe bọc thép chở quân; tàu vận tải bọc thép chở quân"),
        ("APC (armour-piercing capped)", "đạn có đầu xuyên thép, đạn có đầu bọc thép, đầu đạn bọc thép"),
        ("APC (Army Pay Corps)", "ngành tài chính quân đội; ngành tài chính lục quân"),
        ("APCBC (armor piercing, capped, ballistic cap)", "đầu đạn hình khí động xuyên thép có chóp siêu rắn"),
        ("APCC (aerial port control center)", "trung tâm kiểm soát cảng hàng không"),
        ("APCM (Asiatic-Pacific Campaign Medal)", "huy chương “Vì phục vụ ở chiến trường châu Á Thái Bình Dương”"),
        ("APC-T (armour-piercing capped-tracer)", "đạn xuyên thép vạch đường có chóp siêu rắn"),
        ("APDS (armour-piercing discarding sabot)", "đạn xuyên thép tách vỏ, đạn xuyên thép dưới cỡ, đạn xuyên giáp có ốp tự văng"),
        ("APDS-T (armor-piercing discarding sabot artillery projectile with tracer)", "đạn pháo xuyên thép vạch đường dưới cỡ có đáy rời"),
        ("APDS-T (armour-piercing discarding sabot-tracer)", "đạn xuyên thép tách vỏ vạch đường, đạn xuyên giáp vạch đường dưới cỡ"),
        ("APE (amphibious front-line reconnaissance vehicle)", "phương tiện trinh sát tiền duyên khu vực đổ bộ"),
        ("APEDS-T (anti-personnel tracer)", "đạn vạch đường sát thương bộ binh"),
        ("APERS; apers (antipersonnel)", "(thuộc) chống bộ binh, (thuộc) sát thương bộ binh, (thuộc) sát thương sinh lực"),
        ("apers obs (antipersonnel obstacle)", "vật cản chống bộ binh"),
        ("APF (afloat pre-positioning force)", "lực lượng tàu nổi triển khai sẵn"),
        ("APFC (airportable fuel container)", "thùng nhiên liệu chở trên máy bay"),
        ("APFD (autopilot flight director)", "thiết bị định hướng bay trong bộ tự động lái"),
        ("APFDS(P) (armour-piercing fin-stabilized discarding sabot, practice)", "đạn xuyên thép tách vỏ có cánh đuôi ổn định (đạn thao tác)"),
        ("APFIDS (armor-piercing fragmentation incendiary discarding sabot)", "đạn cháy xuyên thép phá mảnh dưới cỡ; ống phóng đạn cháy xuyên thép nổ phá mảnh dùng một lần"),
        ("APFSDS (armour-piercing fin-stabilized discarding sabot)", "ống phóng đạn xuyên thép có cánh đuôi ổn định dùng một lần"),
        ("APFSDS-T (armour-piercing fin-stabilized discarding sabot-tracer)", "đạn tách vỏ xuyên thép vạch đường có cánh đuôi ổn định"),
        ("APG (Aberdeen Proving Ground)", "trường bắn thử nghiệm Abecđin"),
        ("APG (Army Planning Group)", "nhóm lập kế hoạch lục quân"),
        ("APGM (Autonomous Precision-Guided Munition)", "đạn tự động điều khiển chính xác; đạn tự dẫn chính xác"),
        ("APHE (armour-piercing high explosive)", "đạn nổ mạnh xuyên thép, đạn nổ lõm xuyên thép"),
        ("API (air-position indicator)", "đồng hồ chỉ báo vị trí bay; rada chỉ báo tư thế máy bay"),
        ("API (armor piercing incendiary ammunition)", "bom đạn cháy xuyên thép"),
        ("API (armour-piercing incendiary)", "đạn cháy xuyên thép"),
        ("APIC (allied press information center)", "trung tâm thông tin báo chí của liên quân"),
        ("APIT (armour-piercing incendiary tracer)", "đạn cháy xuyên thép vạch đường"),
        ("APM (anti-personnel mine)", "mìn chống bộ binh, mìn sát thương bộ binh, mìn sát thương sinh lực"),
        ("APO (afloat pre-positioning operations)", "hoạt động của tàu hải quân triển khai sẵn"),
    ]),
    (1381, [
        ("APO (army post office)", "phòng quân bưu"),
        ("APOBS (anti-personnel obstacle breaching system)", "tổ hợp khắc phục vật cản chống bộ binh"),
        ("APOE (aerial port of embarkation)", "sân bay bốc xếp hàng hoá (quân sự)"),
        ("APORT (aerial port)", "cảng hàng không; sân bay"),
        ("APP (appendix)", "phụ lục"),
        ("app (appointment)", "sự chỉ định; sự bổ nhiệm (chức vụ)"),
        ("APP (army procurement procedure)", "thủ tục mua sắm và trang bị vũ khí cho lục quân"),
        ("APPL (application)", "đơn xin; bản báo cáo; sự áp dụng, sự ứng dụng"),
        ("approx (approximately)", "gần đúng"),
        ("APPS (analytical photogrammetric positioning system)", "hệ thống định vị bằng phân tích đo đạc ảnh (hàng không)"),
        ("appt (appoint)", "chỉ định; bổ nhiệm (chức vụ)"),
        ("APR (air priority)", "quyền ưu tiên không quân"),
        ("Apr (April)", "tháng tư"),
        ("APR (assign primary zone routing)", "quy định lộ trình ở khu vực xuất phát"),
        ("APROP; aprop (appropriate)", "dành riêng (cho mục đích đặc biệt)"),
        ("APRX (aproximate)", "xấp xỉ, gần đúng"),
        ("APS (Advanced Propulsion System)", "hệ thống lực đẩy cải tiến"),
        ("APS (afloat pre-positioning ships)", "các tàu nổi triển khai sẵn"),
        ("APS (aircraft position sensor)", "xenxơ định vị máy bay"),
        ("APS (armor-piercing sabot)", "đạn xuyên thép dưới cỡ, đạn xuyên thép tách vỏ"),
        ("APS (Army Postal Service)", "ngành quân bưu"),
        ("APS (Artillery Pointing System)", "hệ thống chỉ thị mục tiêu cho pháo binh"),
        ("APS (auxiliary power supply)", "nguồn điện phụ"),
        ("APSE (Ada programming support environment)", "môi trường bảo đảm lập trình Ada"),
        ("APSE (armor-piercing secondary effect)", "hiệu ứng phụ của đạn xuyên thép, hiệu ứng xuyên giáp thứ cấp"),
        ("APSE (armour-piercing secondary effect)", "tác dụng phụ của đạn xuyên thép, tác dụng thứ cấp của đạn xuyên thép"),
        ("APSE-T (armour-piercing secondary effect-tracer)", "tác dụng phụ của đầu đạn xuyên thép vạch đường"),
        ("APT (appointed)", "được chỉ định; được bổ nhiệm (chức vụ)"),
        ("APT (appointment)", "sự chỉ định; sự bổ nhiệm"),
        ("APT (armour piercing tracer)", "đạn xuyên thép vạch đường"),
        ("APTC (Army Physical Training Corps)", "ngành huấn luyện thể lực lục quân"),
        ("APU (army postal unit)", "đơn vị quân bưu lục quân"),
        ("APU (auxiliary power unit)", "bộ nguồn phụ, bộ nguồn bổ trợ, thiết bị phát điện hỗ trợ"),
        ("APU (auxiliary power unit, part of aircraft)", "động cơ phụ (bộ phận của máy bay)"),
        ("APV (armoured patrol vehicle)", "xe bọc thép tuần tiễu; tàu bọc thép tuần tiễu"),
        ("APV (autopiloted vehicle)", "máy bay không người lái"),
        ("APWIB (American Prisoner of War Information Bureau)", "cục thông tin về hồ sơ tù binh Mỹ"),
        ("AQ (any quantity)", "số lượng bất kỳ"),
        ("AR (acquisition radar)", "rada phát hiện và chỉ thị mục tiêu; rada cảnh giới"),
        ("AR (aircraft rocket)", "tên lửa hàng không (không điều khiển), tên lửa trên máy bay"),
        ("AR (Army Regulation)", "điều lệ lục quân"),
        ("AR; A/R (all rail movement)", "sự cơ động bằng đường sắt; sự vận chuyển bằng đường sắt"),
    ]),
    (1382, [
        ("AR; Ar (army)", "tập đoàn quân; lục quân; (thuộc) lục quân; (thuộc) quân đội"),
        ("AR (assault rifle)", "súng trường xung kích"),
        ("AR (automatic rifle)", "súng trường tự động"),
        ("AR/AAV (Armored Reconnaissance/Airborne Assault Vehicle, US)", "xe bọc thép trinh sát đổ bộ tiến công đường không"),
        ("ARAAV (armored reconnaissance-airborne assault vehicle)", "xe bọc thép trinh sát đổ bộ tiến công đường không"),
        ("ARADCOM (Army Air Defense Command)", "bộ chỉ huy phòng không tập đoàn quân; bộ tư lệnh phòng không lục quân"),
        ("ARB (alternate recovery base)", "căn cứ sửa chữa và khôi phục dự phòng"),
        ("ARBS (angle rate bombing system)", "hệ thống ném bom theo tốc độ góc"),
        ("ARC (Air Reserve Components)", "các thành phần lực lượng dự bị không quân"),
        ("ARC (Annual Review Committee)", "uỷ ban NATO về tổng hợp xuất bản hàng năm"),
        ("ARC (Army Red Cross)", "hội chữ thập đỏ lục quân"),
        ("ARCE (amphibious river crossing equipment)", "phương tiện đổ bộ vượt sông"),
        ("ARCM (anti-radiation countermeasures)", "biện pháp chống bức xạ; thiết bị chống bức xạ chống rada"),
        ("ARCOM (Army Commendation Medal)", "huy chương “Vì phục vụ trong lực lượng lục quân”"),
        ("ARCP (air refueling control point)", "điểm điều khiển tiếp dầu trên không"),
        ("ARCS (aerial rocket control system)", "hệ thống điều khiển rốcket (trên) máy bay"),
        ("ARCT (air refueling control time)", "thời gian điều khiển tiếp dầu trên không"),
        ("ARD (anti-radar drone)", "máy bay không người lái chống rada"),
        ("ARDEC (Armament Research Development and Engineering Center, Mỹ)", "trung tâm nghiên cứu phát triển vũ khí và trang bị kỹ thuật"),
        ("ARDF (automatic radio direction finding)", "sự tìm phương bằng vô tuyến tự động; tự động tìm phương bằng vô tuyến"),
        ("ARDNOT (Automatic Day/Night Optical Tracker)", "bộ theo dõi tự động ngày và đêm bằng kính quang học"),
        ("ARES (active relief sensor)", "xenxơ chủ động dạng ném thả"),
        ("Ares (Army Reserve)", "lực lượng dự bị lục quân"),
        ("ARETS (Armour Remote Target System)", "hệ thống mục tiêu xe bọc thép điều khiển từ xa, tổ hợp bia xe tăng điều khiển từ xa"),
        ("ARFCOS (Armed Forces Courier Service)", "ngành thông tin liên lạc hoả tốc quân đội"),
        ("ARFOR (Army forces)", "các lực lượng vũ trang"),
        ("ARG (amphibious ready group)", "cụm xe lội nước sẵn sàng đổ bộ"),
        ("ARGMA (Army Rocket and Guided Missile Agency)", "cục nghiên cứu và thử nghiệm tên lửa có điều khiển và không điều khiển lục quân"),
        ("ARGO (automatic ranging grid overlay)", "bản can mạng toạ độ định tầm tự động"),
        ("ARH (anti-radar / radiation homing)", "sự tự dẫn chống bức xạ / chống rada"),
        ("ARINC (Aeronautical Radio Incorporated)", "tổ hợp vô tuyến dẫn đường hàng không"),
        ("ARIP (air refueling inn point)", "điểm bắt đầu tiếp dầu trên không"),
        ("ARLANT (Army Forces, Atlantic Command, Mỹ)", "bộ tư lệnh lục quân ở khu vực Đại Tây Dương"),
        ("ARIC (airborne radio & intercom control system)", "hệ thống điều khiển thiết bị vô tuyến và truyền tin nội bộ (trên) máy bay"),
        ("ARL-M (airborne reconnaissance low-multifunction)", "(máy bay) trinh sát đường không đa năng tầng thấp"),
        ("ARM (anti-radar/radiation missile)", "tên lửa chống bức xạ / chống rada"),
    ]),
]


def main() -> None:
    rows = []
    for printed_page, entries in PAGES:
        for word, meaning_vi in entries:
            rows.append({
                "source_page": printed_page,
                "dictionary_name": DICTIONARY_NAME,
                "word": word,
                "phonetic": "",
                "part_of_speech_raw": "",
                "part_of_speech_code": "",
                "meaning_vi": meaning_vi,
                "is_subentry": "FALSE",
                "example_en": "",
                "example_vi": "",
                "image_path": f"img_{printed_page}.jpg",
                "reviewed": "FALSE",
            })

    fieldnames = [
        "source_page", "dictionary_name", "word", "phonetic",
        "part_of_speech_raw", "part_of_speech_code", "meaning_vi",
        "is_subentry", "example_en", "example_vi", "image_path", "reviewed",
    ]
    out_path = "docs/db/import/pilot_tudien_vision_abbr.csv"
    with open(out_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Done. {len(rows)} entries -> {out_path}")


if __name__ == "__main__":
    main()
